export declare const shorthands: {
    readonly ussel: "userSelect";
    readonly cur: "cursor";
    readonly pe: "pointerEvents";
    readonly col: "color";
    readonly ff: "fontFamily";
    readonly fos: "fontSize";
    readonly fost: "fontStyle";
    readonly fow: "fontWeight";
    readonly ls: "letterSpacing";
    readonly lh: "lineHeight";
    readonly ta: "textAlign";
    readonly tt: "textTransform";
    readonly ww: "wordWrap";
    readonly ac: "alignContent";
    readonly ai: "alignItems";
    readonly als: "alignSelf";
    readonly b: "bottom";
    readonly bg: "backgroundColor";
    readonly bbc: "borderBottomColor";
    readonly bblr: "borderBottomLeftRadius";
    readonly bbrr: "borderBottomRightRadius";
    readonly bbw: "borderBottomWidth";
    readonly blc: "borderLeftColor";
    readonly blw: "borderLeftWidth";
    readonly bc: "borderColor";
    readonly br: "borderRadius";
    readonly bs: "borderStyle";
    readonly brw: "borderRightWidth";
    readonly brc: "borderRightColor";
    readonly btc: "borderTopColor";
    readonly btlr: "borderTopLeftRadius";
    readonly btrr: "borderTopRightRadius";
    readonly btw: "borderTopWidth";
    readonly bw: "borderWidth";
    readonly dsp: "display";
    readonly f: "flex";
    readonly fb: "flexBasis";
    readonly fd: "flexDirection";
    readonly fg: "flexGrow";
    readonly fs: "flexShrink";
    readonly fw: "flexWrap";
    readonly h: "height";
    readonly jc: "justifyContent";
    readonly l: "left";
    readonly m: "margin";
    readonly mah: "maxHeight";
    readonly maw: "maxWidth";
    readonly mb: "marginBottom";
    readonly mih: "minHeight";
    readonly miw: "minWidth";
    readonly ml: "marginLeft";
    readonly mr: "marginRight";
    readonly mt: "marginTop";
    readonly mx: "marginHorizontal";
    readonly my: "marginVertical";
    readonly o: "opacity";
    readonly ov: "overflow";
    readonly p: "padding";
    readonly pb: "paddingBottom";
    readonly pl: "paddingLeft";
    readonly pos: "position";
    readonly pr: "paddingRight";
    readonly pt: "paddingTop";
    readonly px: "paddingHorizontal";
    readonly py: "paddingVertical";
    readonly r: "right";
    readonly shac: "shadowColor";
    readonly shar: "shadowRadius";
    readonly shof: "shadowOffset";
    readonly shop: "shadowOpacity";
    readonly t: "top";
    readonly w: "width";
    readonly zi: "zIndex";
};
export { animations } from './v3-animations';
export { tokens, themes } from '@hanzogui/themes/v3-themes';
export { fonts } from './fonts';
export { media, mediaQueryDefaultActive } from './media';
export declare const selectionStyles: (theme: any) => {
    backgroundColor: any;
    color: any;
} | null;
export declare const config: {
    animations: import("@hanzogui/web").AnimationDriver<{
        '0ms': string;
        '30ms': string;
        '50ms': string;
        '75ms': string;
        '100ms': string;
        '200ms': string;
        '250ms': string;
        '300ms': string;
        '400ms': string;
        '500ms': string;
        superBouncy: string;
        bouncy: string;
        kindaBouncy: string;
        superLazy: string;
        lazy: string;
        medium: string;
        slowest: string;
        slow: string;
        quick: string;
        quickLessBouncy: string;
        tooltip: string;
        quicker: string;
        quickerLessBouncy: string;
        quickest: string;
        quickestLessBouncy: string;
    }>;
    themes: import("@hanzogui/themes/v3-themes").ThemesOut;
    media: {
        xl: {
            maxWidth: number;
        };
        lg: {
            maxWidth: number;
        };
        md: {
            maxWidth: number;
        };
        sm: {
            maxWidth: number;
        };
        xs: {
            maxWidth: number;
        };
        xxs: {
            maxWidth: number;
        };
        gtXs: {
            minWidth: number;
        };
        gtSm: {
            minWidth: number;
        };
        gtMd: {
            minWidth: number;
        };
        gtLg: {
            minWidth: number;
        };
        gtXl: {
            minWidth: number;
        };
    };
    shorthands: {
        readonly ussel: "userSelect";
        readonly cur: "cursor";
        readonly pe: "pointerEvents";
        readonly col: "color";
        readonly ff: "fontFamily";
        readonly fos: "fontSize";
        readonly fost: "fontStyle";
        readonly fow: "fontWeight";
        readonly ls: "letterSpacing";
        readonly lh: "lineHeight";
        readonly ta: "textAlign";
        readonly tt: "textTransform";
        readonly ww: "wordWrap";
        readonly ac: "alignContent";
        readonly ai: "alignItems";
        readonly als: "alignSelf";
        readonly b: "bottom";
        readonly bg: "backgroundColor";
        readonly bbc: "borderBottomColor";
        readonly bblr: "borderBottomLeftRadius";
        readonly bbrr: "borderBottomRightRadius";
        readonly bbw: "borderBottomWidth";
        readonly blc: "borderLeftColor";
        readonly blw: "borderLeftWidth";
        readonly bc: "borderColor";
        readonly br: "borderRadius";
        readonly bs: "borderStyle";
        readonly brw: "borderRightWidth";
        readonly brc: "borderRightColor";
        readonly btc: "borderTopColor";
        readonly btlr: "borderTopLeftRadius";
        readonly btrr: "borderTopRightRadius";
        readonly btw: "borderTopWidth";
        readonly bw: "borderWidth";
        readonly dsp: "display";
        readonly f: "flex";
        readonly fb: "flexBasis";
        readonly fd: "flexDirection";
        readonly fg: "flexGrow";
        readonly fs: "flexShrink";
        readonly fw: "flexWrap";
        readonly h: "height";
        readonly jc: "justifyContent";
        readonly l: "left";
        readonly m: "margin";
        readonly mah: "maxHeight";
        readonly maw: "maxWidth";
        readonly mb: "marginBottom";
        readonly mih: "minHeight";
        readonly miw: "minWidth";
        readonly ml: "marginLeft";
        readonly mr: "marginRight";
        readonly mt: "marginTop";
        readonly mx: "marginHorizontal";
        readonly my: "marginVertical";
        readonly o: "opacity";
        readonly ov: "overflow";
        readonly p: "padding";
        readonly pb: "paddingBottom";
        readonly pl: "paddingLeft";
        readonly pos: "position";
        readonly pr: "paddingRight";
        readonly pt: "paddingTop";
        readonly px: "paddingHorizontal";
        readonly py: "paddingVertical";
        readonly r: "right";
        readonly shac: "shadowColor";
        readonly shar: "shadowRadius";
        readonly shof: "shadowOffset";
        readonly shop: "shadowOpacity";
        readonly t: "top";
        readonly w: "width";
        readonly zi: "zIndex";
    };
    tokens: {
        color: {
            white0: import("@hanzogui/web").Variable<string>;
            white075: import("@hanzogui/web").Variable<string>;
            white05: import("@hanzogui/web").Variable<string>;
            white025: import("@hanzogui/web").Variable<string>;
            black0: import("@hanzogui/web").Variable<string>;
            black075: import("@hanzogui/web").Variable<string>;
            black05: import("@hanzogui/web").Variable<string>;
            black025: import("@hanzogui/web").Variable<string>;
            white1: import("@hanzogui/web").Variable<string>;
            white2: import("@hanzogui/web").Variable<string>;
            white3: import("@hanzogui/web").Variable<string>;
            white4: import("@hanzogui/web").Variable<string>;
            white5: import("@hanzogui/web").Variable<string>;
            white6: import("@hanzogui/web").Variable<string>;
            white7: import("@hanzogui/web").Variable<string>;
            white8: import("@hanzogui/web").Variable<string>;
            white9: import("@hanzogui/web").Variable<string>;
            white10: import("@hanzogui/web").Variable<string>;
            white11: import("@hanzogui/web").Variable<string>;
            white12: import("@hanzogui/web").Variable<string>;
            black1: import("@hanzogui/web").Variable<string>;
            black2: import("@hanzogui/web").Variable<string>;
            black3: import("@hanzogui/web").Variable<string>;
            black4: import("@hanzogui/web").Variable<string>;
            black5: import("@hanzogui/web").Variable<string>;
            black6: import("@hanzogui/web").Variable<string>;
            black7: import("@hanzogui/web").Variable<string>;
            black8: import("@hanzogui/web").Variable<string>;
            black9: import("@hanzogui/web").Variable<string>;
            black10: import("@hanzogui/web").Variable<string>;
            black11: import("@hanzogui/web").Variable<string>;
            black12: import("@hanzogui/web").Variable<string>;
        };
        space: {
            0: import("@hanzogui/web").Variable<number>;
            0.25: import("@hanzogui/web").Variable<number>;
            0.5: import("@hanzogui/web").Variable<number>;
            0.75: import("@hanzogui/web").Variable<number>;
            1: import("@hanzogui/web").Variable<number>;
            1.5: import("@hanzogui/web").Variable<number>;
            2: import("@hanzogui/web").Variable<number>;
            2.5: import("@hanzogui/web").Variable<number>;
            3: import("@hanzogui/web").Variable<number>;
            3.5: import("@hanzogui/web").Variable<number>;
            4: import("@hanzogui/web").Variable<number>;
            true: import("@hanzogui/web").Variable<number>;
            4.5: import("@hanzogui/web").Variable<number>;
            5: import("@hanzogui/web").Variable<number>;
            6: import("@hanzogui/web").Variable<number>;
            7: import("@hanzogui/web").Variable<number>;
            8: import("@hanzogui/web").Variable<number>;
            9: import("@hanzogui/web").Variable<number>;
            10: import("@hanzogui/web").Variable<number>;
            11: import("@hanzogui/web").Variable<number>;
            12: import("@hanzogui/web").Variable<number>;
            13: import("@hanzogui/web").Variable<number>;
            14: import("@hanzogui/web").Variable<number>;
            15: import("@hanzogui/web").Variable<number>;
            16: import("@hanzogui/web").Variable<number>;
            17: import("@hanzogui/web").Variable<number>;
            18: import("@hanzogui/web").Variable<number>;
            19: import("@hanzogui/web").Variable<number>;
            20: import("@hanzogui/web").Variable<number>;
            [-0.25]: import("@hanzogui/web").Variable<number>;
            [-0.5]: import("@hanzogui/web").Variable<number>;
            [-0.75]: import("@hanzogui/web").Variable<number>;
            [-1]: import("@hanzogui/web").Variable<number>;
            [-1.5]: import("@hanzogui/web").Variable<number>;
            [-2]: import("@hanzogui/web").Variable<number>;
            [-2.5]: import("@hanzogui/web").Variable<number>;
            [-3]: import("@hanzogui/web").Variable<number>;
            [-3.5]: import("@hanzogui/web").Variable<number>;
            [-4]: import("@hanzogui/web").Variable<number>;
            "-true": import("@hanzogui/web").Variable<number>;
            [-4.5]: import("@hanzogui/web").Variable<number>;
            [-5]: import("@hanzogui/web").Variable<number>;
            [-6]: import("@hanzogui/web").Variable<number>;
            [-7]: import("@hanzogui/web").Variable<number>;
            [-8]: import("@hanzogui/web").Variable<number>;
            [-9]: import("@hanzogui/web").Variable<number>;
            [-10]: import("@hanzogui/web").Variable<number>;
            [-11]: import("@hanzogui/web").Variable<number>;
            [-12]: import("@hanzogui/web").Variable<number>;
            [-13]: import("@hanzogui/web").Variable<number>;
            [-14]: import("@hanzogui/web").Variable<number>;
            [-15]: import("@hanzogui/web").Variable<number>;
            [-16]: import("@hanzogui/web").Variable<number>;
            [-17]: import("@hanzogui/web").Variable<number>;
            [-18]: import("@hanzogui/web").Variable<number>;
            [-19]: import("@hanzogui/web").Variable<number>;
            [-20]: import("@hanzogui/web").Variable<number>;
        };
        size: {
            $0: import("@hanzogui/web").Variable<number>;
            "$0.25": import("@hanzogui/web").Variable<number>;
            "$0.5": import("@hanzogui/web").Variable<number>;
            "$0.75": import("@hanzogui/web").Variable<number>;
            $1: import("@hanzogui/web").Variable<number>;
            "$1.5": import("@hanzogui/web").Variable<number>;
            $2: import("@hanzogui/web").Variable<number>;
            "$2.5": import("@hanzogui/web").Variable<number>;
            $3: import("@hanzogui/web").Variable<number>;
            "$3.5": import("@hanzogui/web").Variable<number>;
            $4: import("@hanzogui/web").Variable<number>;
            $true: import("@hanzogui/web").Variable<number>;
            "$4.5": import("@hanzogui/web").Variable<number>;
            $5: import("@hanzogui/web").Variable<number>;
            $6: import("@hanzogui/web").Variable<number>;
            $7: import("@hanzogui/web").Variable<number>;
            $8: import("@hanzogui/web").Variable<number>;
            $9: import("@hanzogui/web").Variable<number>;
            $10: import("@hanzogui/web").Variable<number>;
            $11: import("@hanzogui/web").Variable<number>;
            $12: import("@hanzogui/web").Variable<number>;
            $13: import("@hanzogui/web").Variable<number>;
            $14: import("@hanzogui/web").Variable<number>;
            $15: import("@hanzogui/web").Variable<number>;
            $16: import("@hanzogui/web").Variable<number>;
            $17: import("@hanzogui/web").Variable<number>;
            $18: import("@hanzogui/web").Variable<number>;
            $19: import("@hanzogui/web").Variable<number>;
            $20: import("@hanzogui/web").Variable<number>;
        };
        radius: {
            0: import("@hanzogui/web").Variable<number>;
            1: import("@hanzogui/web").Variable<number>;
            2: import("@hanzogui/web").Variable<number>;
            3: import("@hanzogui/web").Variable<number>;
            4: import("@hanzogui/web").Variable<number>;
            true: import("@hanzogui/web").Variable<number>;
            5: import("@hanzogui/web").Variable<number>;
            6: import("@hanzogui/web").Variable<number>;
            7: import("@hanzogui/web").Variable<number>;
            8: import("@hanzogui/web").Variable<number>;
            9: import("@hanzogui/web").Variable<number>;
            10: import("@hanzogui/web").Variable<number>;
            11: import("@hanzogui/web").Variable<number>;
            12: import("@hanzogui/web").Variable<number>;
        };
        zIndex: {
            0: import("@hanzogui/web").Variable<number>;
            1: import("@hanzogui/web").Variable<number>;
            2: import("@hanzogui/web").Variable<number>;
            3: import("@hanzogui/web").Variable<number>;
            4: import("@hanzogui/web").Variable<number>;
            5: import("@hanzogui/web").Variable<number>;
        };
    } & Omit<{
        radius: {
            0: import("@hanzogui/web").Variable<number>;
            1: import("@hanzogui/web").Variable<number>;
            2: import("@hanzogui/web").Variable<number>;
            3: import("@hanzogui/web").Variable<number>;
            4: import("@hanzogui/web").Variable<number>;
            true: import("@hanzogui/web").Variable<number>;
            5: import("@hanzogui/web").Variable<number>;
            6: import("@hanzogui/web").Variable<number>;
            7: import("@hanzogui/web").Variable<number>;
            8: import("@hanzogui/web").Variable<number>;
            9: import("@hanzogui/web").Variable<number>;
            10: import("@hanzogui/web").Variable<number>;
            11: import("@hanzogui/web").Variable<number>;
            12: import("@hanzogui/web").Variable<number>;
        };
        zIndex: {
            0: import("@hanzogui/web").Variable<number>;
            1: import("@hanzogui/web").Variable<number>;
            2: import("@hanzogui/web").Variable<number>;
            3: import("@hanzogui/web").Variable<number>;
            4: import("@hanzogui/web").Variable<number>;
            5: import("@hanzogui/web").Variable<number>;
        };
        space: {
            0: import("@hanzogui/web").Variable<number>;
            0.25: import("@hanzogui/web").Variable<number>;
            0.5: import("@hanzogui/web").Variable<number>;
            0.75: import("@hanzogui/web").Variable<number>;
            1: import("@hanzogui/web").Variable<number>;
            1.5: import("@hanzogui/web").Variable<number>;
            2: import("@hanzogui/web").Variable<number>;
            2.5: import("@hanzogui/web").Variable<number>;
            3: import("@hanzogui/web").Variable<number>;
            3.5: import("@hanzogui/web").Variable<number>;
            4: import("@hanzogui/web").Variable<number>;
            true: import("@hanzogui/web").Variable<number>;
            4.5: import("@hanzogui/web").Variable<number>;
            5: import("@hanzogui/web").Variable<number>;
            6: import("@hanzogui/web").Variable<number>;
            7: import("@hanzogui/web").Variable<number>;
            8: import("@hanzogui/web").Variable<number>;
            9: import("@hanzogui/web").Variable<number>;
            10: import("@hanzogui/web").Variable<number>;
            11: import("@hanzogui/web").Variable<number>;
            12: import("@hanzogui/web").Variable<number>;
            13: import("@hanzogui/web").Variable<number>;
            14: import("@hanzogui/web").Variable<number>;
            15: import("@hanzogui/web").Variable<number>;
            16: import("@hanzogui/web").Variable<number>;
            17: import("@hanzogui/web").Variable<number>;
            18: import("@hanzogui/web").Variable<number>;
            19: import("@hanzogui/web").Variable<number>;
            20: import("@hanzogui/web").Variable<number>;
            [-0.25]: import("@hanzogui/web").Variable<number>;
            [-0.5]: import("@hanzogui/web").Variable<number>;
            [-0.75]: import("@hanzogui/web").Variable<number>;
            [-1]: import("@hanzogui/web").Variable<number>;
            [-1.5]: import("@hanzogui/web").Variable<number>;
            [-2]: import("@hanzogui/web").Variable<number>;
            [-2.5]: import("@hanzogui/web").Variable<number>;
            [-3]: import("@hanzogui/web").Variable<number>;
            [-3.5]: import("@hanzogui/web").Variable<number>;
            [-4]: import("@hanzogui/web").Variable<number>;
            "-true": import("@hanzogui/web").Variable<number>;
            [-4.5]: import("@hanzogui/web").Variable<number>;
            [-5]: import("@hanzogui/web").Variable<number>;
            [-6]: import("@hanzogui/web").Variable<number>;
            [-7]: import("@hanzogui/web").Variable<number>;
            [-8]: import("@hanzogui/web").Variable<number>;
            [-9]: import("@hanzogui/web").Variable<number>;
            [-10]: import("@hanzogui/web").Variable<number>;
            [-11]: import("@hanzogui/web").Variable<number>;
            [-12]: import("@hanzogui/web").Variable<number>;
            [-13]: import("@hanzogui/web").Variable<number>;
            [-14]: import("@hanzogui/web").Variable<number>;
            [-15]: import("@hanzogui/web").Variable<number>;
            [-16]: import("@hanzogui/web").Variable<number>;
            [-17]: import("@hanzogui/web").Variable<number>;
            [-18]: import("@hanzogui/web").Variable<number>;
            [-19]: import("@hanzogui/web").Variable<number>;
            [-20]: import("@hanzogui/web").Variable<number>;
        };
        size: {
            $0: import("@hanzogui/web").Variable<number>;
            "$0.25": import("@hanzogui/web").Variable<number>;
            "$0.5": import("@hanzogui/web").Variable<number>;
            "$0.75": import("@hanzogui/web").Variable<number>;
            $1: import("@hanzogui/web").Variable<number>;
            "$1.5": import("@hanzogui/web").Variable<number>;
            $2: import("@hanzogui/web").Variable<number>;
            "$2.5": import("@hanzogui/web").Variable<number>;
            $3: import("@hanzogui/web").Variable<number>;
            "$3.5": import("@hanzogui/web").Variable<number>;
            $4: import("@hanzogui/web").Variable<number>;
            $true: import("@hanzogui/web").Variable<number>;
            "$4.5": import("@hanzogui/web").Variable<number>;
            $5: import("@hanzogui/web").Variable<number>;
            $6: import("@hanzogui/web").Variable<number>;
            $7: import("@hanzogui/web").Variable<number>;
            $8: import("@hanzogui/web").Variable<number>;
            $9: import("@hanzogui/web").Variable<number>;
            $10: import("@hanzogui/web").Variable<number>;
            $11: import("@hanzogui/web").Variable<number>;
            $12: import("@hanzogui/web").Variable<number>;
            $13: import("@hanzogui/web").Variable<number>;
            $14: import("@hanzogui/web").Variable<number>;
            $15: import("@hanzogui/web").Variable<number>;
            $16: import("@hanzogui/web").Variable<number>;
            $17: import("@hanzogui/web").Variable<number>;
            $18: import("@hanzogui/web").Variable<number>;
            $19: import("@hanzogui/web").Variable<number>;
            $20: import("@hanzogui/web").Variable<number>;
        };
        color: {
            white0: import("@hanzogui/web").Variable<string>;
            white075: import("@hanzogui/web").Variable<string>;
            white05: import("@hanzogui/web").Variable<string>;
            white025: import("@hanzogui/web").Variable<string>;
            black0: import("@hanzogui/web").Variable<string>;
            black075: import("@hanzogui/web").Variable<string>;
            black05: import("@hanzogui/web").Variable<string>;
            black025: import("@hanzogui/web").Variable<string>;
            white1: import("@hanzogui/web").Variable<string>;
            white2: import("@hanzogui/web").Variable<string>;
            white3: import("@hanzogui/web").Variable<string>;
            white4: import("@hanzogui/web").Variable<string>;
            white5: import("@hanzogui/web").Variable<string>;
            white6: import("@hanzogui/web").Variable<string>;
            white7: import("@hanzogui/web").Variable<string>;
            white8: import("@hanzogui/web").Variable<string>;
            white9: import("@hanzogui/web").Variable<string>;
            white10: import("@hanzogui/web").Variable<string>;
            white11: import("@hanzogui/web").Variable<string>;
            white12: import("@hanzogui/web").Variable<string>;
            black1: import("@hanzogui/web").Variable<string>;
            black2: import("@hanzogui/web").Variable<string>;
            black3: import("@hanzogui/web").Variable<string>;
            black4: import("@hanzogui/web").Variable<string>;
            black5: import("@hanzogui/web").Variable<string>;
            black6: import("@hanzogui/web").Variable<string>;
            black7: import("@hanzogui/web").Variable<string>;
            black8: import("@hanzogui/web").Variable<string>;
            black9: import("@hanzogui/web").Variable<string>;
            black10: import("@hanzogui/web").Variable<string>;
            black11: import("@hanzogui/web").Variable<string>;
            black12: import("@hanzogui/web").Variable<string>;
        };
    }, "size" | "color" | "space" | "radius" | "zIndex">;
    fonts: {
        heading: import("@hanzogui/web").FillInFont<{
            size: {
                5: number;
                6: number;
                9: number;
                10: number;
            };
            transform: {
                6: "uppercase";
                7: "none";
            };
            weight: {
                6: string;
                7: string;
            };
            color: {
                6: string;
                7: string;
            };
            letterSpacing: {
                5: number;
                6: number;
                7: number;
                8: number;
                9: number;
                10: number;
                12: number;
                14: number;
                15: number;
            };
            face: {
                700: {
                    normal: string;
                };
                800: {
                    normal: string;
                };
                900: {
                    normal: string;
                };
            };
        }, 9 | 15 | 1 | 10 | 3 | 2 | 5 | 6 | 16 | 11 | 12 | 14 | 4 | 7 | 8 | 13 | "true">;
        body: import("@hanzogui/web").FillInFont<import("@hanzogui/web").GenericFont, 9 | 15 | 1 | 10 | 3 | 2 | 5 | 6 | 16 | 11 | 12 | 14 | 4 | 7 | 8 | 13 | "true">;
        mono: {
            weight: {
                1: string;
            };
            size: {
                1: number;
                2: number;
                3: number;
                4: number;
                5: number;
                6: number;
                7: number;
                8: number;
                9: number;
                10: number;
                11: number;
                12: number;
                13: number;
                14: number;
                15: number;
                16: number;
            };
        };
        silkscreen: import("@hanzogui/web").FillInFont<import("@hanzogui/web").GenericFont, 9 | 15 | 1 | 10 | 3 | 2 | 5 | 6 | 16 | 11 | 12 | 14 | 4 | 7 | 8 | 13>;
    };
    selectionStyles: (theme: any) => {
        backgroundColor: any;
        color: any;
    } | null;
    settings: {
        mediaQueryDefaultActive: {
            xl: boolean;
            lg: boolean;
            md: boolean;
            sm: boolean;
            xs: boolean;
            xxs: boolean;
        };
        defaultFont: string;
        fastSchemeChange: true;
        shouldAddPrefersColorThemes: true;
    };
};
//# sourceMappingURL=v3.d.ts.map