// Ambient declarations for `@hanzogui/lucide-icons-2/icons/<Name>`
// deep-imports. Mirrors apps/admin-tasks/src/lucide-icons.d.ts.

declare module '@hanzogui/lucide-icons-2/icons/Activity' { export const Activity: any }
declare module '@hanzogui/lucide-icons-2/icons/AlertTriangle' { export const AlertTriangle: any }
declare module '@hanzogui/lucide-icons-2/icons/Archive' { export const Archive: any }
declare module '@hanzogui/lucide-icons-2/icons/ArrowUpRight' { export const ArrowUpRight: any }
declare module '@hanzogui/lucide-icons-2/icons/BookOpen' { export const BookOpen: any }
declare module '@hanzogui/lucide-icons-2/icons/Boxes' { export const Boxes: any }
declare module '@hanzogui/lucide-icons-2/icons/Calendar' { export const Calendar: any }
declare module '@hanzogui/lucide-icons-2/icons/Check' { export const Check: any }
declare module '@hanzogui/lucide-icons-2/icons/ChevronDown' { export const ChevronDown: any }
declare module '@hanzogui/lucide-icons-2/icons/ChevronLeft' { export const ChevronLeft: any }
declare module '@hanzogui/lucide-icons-2/icons/ChevronRight' { export const ChevronRight: any }
declare module '@hanzogui/lucide-icons-2/icons/Circle' { export const Circle: any }
declare module '@hanzogui/lucide-icons-2/icons/Clock' { export const Clock: any }
declare module '@hanzogui/lucide-icons-2/icons/Code' { export const Code: any }
declare module '@hanzogui/lucide-icons-2/icons/Copy' { export const Copy: any }
declare module '@hanzogui/lucide-icons-2/icons/CreditCard' { export const CreditCard: any }
declare module '@hanzogui/lucide-icons-2/icons/ExternalLink' { export const ExternalLink: any }
declare module '@hanzogui/lucide-icons-2/icons/FileJson' { export const FileJson: any }
declare module '@hanzogui/lucide-icons-2/icons/GitBranch' { export const GitBranch: any }
declare module '@hanzogui/lucide-icons-2/icons/Github' { export const Github: any }
declare module '@hanzogui/lucide-icons-2/icons/Globe' { export const Globe: any }
declare module '@hanzogui/lucide-icons-2/icons/Heart' { export const Heart: any }
declare module '@hanzogui/lucide-icons-2/icons/History' { export const History: any }
declare module '@hanzogui/lucide-icons-2/icons/Inbox' { export const Inbox: any }
declare module '@hanzogui/lucide-icons-2/icons/Layers' { export const Layers: any }
declare module '@hanzogui/lucide-icons-2/icons/LayoutDashboard' { export const LayoutDashboard: any }
declare module '@hanzogui/lucide-icons-2/icons/ListChecks' { export const ListChecks: any }
declare module '@hanzogui/lucide-icons-2/icons/LogOut' { export const LogOut: any }
declare module '@hanzogui/lucide-icons-2/icons/MessageSquare' { export const MessageSquare: any }
declare module '@hanzogui/lucide-icons-2/icons/Moon' { export const Moon: any }
declare module '@hanzogui/lucide-icons-2/icons/Network' { export const Network: any }
declare module '@hanzogui/lucide-icons-2/icons/Package' { export const Package: any }
declare module '@hanzogui/lucide-icons-2/icons/Play' { export const Play: any }
declare module '@hanzogui/lucide-icons-2/icons/Plug' { export const Plug: any }
declare module '@hanzogui/lucide-icons-2/icons/Plus' { export const Plus: any }
declare module '@hanzogui/lucide-icons-2/icons/Receipt' { export const Receipt: any }
declare module '@hanzogui/lucide-icons-2/icons/RefreshCw' { export const RefreshCw: any }
declare module '@hanzogui/lucide-icons-2/icons/Rocket' { export const Rocket: any }
declare module '@hanzogui/lucide-icons-2/icons/Search' { export const Search: any }
declare module '@hanzogui/lucide-icons-2/icons/Server' { export const Server: any }
declare module '@hanzogui/lucide-icons-2/icons/Settings' { export const Settings: any }
declare module '@hanzogui/lucide-icons-2/icons/ShoppingBag' { export const ShoppingBag: any }
declare module '@hanzogui/lucide-icons-2/icons/Sun' { export const Sun: any }
declare module '@hanzogui/lucide-icons-2/icons/Timer' { export const Timer: any }
declare module '@hanzogui/lucide-icons-2/icons/Trash2' { export const Trash2: any }
declare module '@hanzogui/lucide-icons-2/icons/Upload' { export const Upload: any }
declare module '@hanzogui/lucide-icons-2/icons/User' { export const User: any }
declare module '@hanzogui/lucide-icons-2/icons/Users' { export const Users: any }
declare module '@hanzogui/lucide-icons-2/icons/WifiOff' { export const WifiOff: any }
declare module '@hanzogui/lucide-icons-2/icons/Workflow' { export const Workflow: any }
declare module '@hanzogui/lucide-icons-2/icons/Zap' { export const Zap: any }
