"use strict";
// all exports here for better tree shaking compat
Object.defineProperty(exports, "__esModule", { value: true });
exports.sandDarkA = exports.sageDarkA = exports.redDarkA = exports.purpleDarkA = exports.plumDarkA = exports.pinkDarkA = exports.orangeDarkA = exports.oliveDarkA = exports.mintDarkA = exports.mauveDarkA = exports.limeDarkA = exports.indigoDarkA = exports.greenDarkA = exports.grayDarkA = exports.grassDarkA = exports.goldDarkA = exports.cyanDarkA = exports.crimsonDarkA = exports.brownDarkA = exports.bronzeDarkA = exports.blueDarkA = exports.amberDarkA = exports.yellowDark = exports.violetDark = exports.tomatoDark = exports.tealDark = exports.slateDark = exports.skyDark = exports.sandDark = exports.sageDark = exports.redDark = exports.purpleDark = exports.plumDark = exports.pinkDark = exports.orangeDark = exports.oliveDark = exports.mintDark = exports.mauveDark = exports.limeDark = exports.indigoDark = exports.greenDark = exports.grayDark = exports.grassDark = exports.goldDark = exports.cyanDark = exports.crimsonDark = exports.brownDark = exports.bronzeDark = exports.blueDark = exports.amberDark = void 0;
exports.orangeA = exports.oliveA = exports.mintA = exports.mauveA = exports.limeA = exports.indigoA = exports.greenA = exports.grayA = exports.grassA = exports.goldA = exports.cyanA = exports.crimsonA = exports.brownA = exports.bronzeA = exports.blueA = exports.amberA = exports.yellow = exports.violet = exports.tomato = exports.teal = exports.slate = exports.sky = exports.sand = exports.sage = exports.red = exports.purple = exports.plum = exports.pink = exports.orange = exports.olive = exports.mint = exports.mauve = exports.lime = exports.indigo = exports.green = exports.gray = exports.grass = exports.gold = exports.cyan = exports.crimson = exports.brown = exports.bronze = exports.blue = exports.amber = exports.yellowDarkA = exports.violetDarkA = exports.tomatoDarkA = exports.tealDarkA = exports.slateDarkA = exports.skyDarkA = void 0;
exports.whiteA = exports.blackA = exports.yellowA = exports.violetA = exports.tomatoA = exports.tealA = exports.slateA = exports.skyA = exports.sandA = exports.sageA = exports.redA = exports.purpleA = exports.plumA = exports.pinkA = void 0;
var amber_1 = require("./dark/amber");
Object.defineProperty(exports, "amberDark", { enumerable: true, get: function () { return amber_1.amber; } });
var blue_1 = require("./dark/blue");
Object.defineProperty(exports, "blueDark", { enumerable: true, get: function () { return blue_1.blue; } });
var bronze_1 = require("./dark/bronze");
Object.defineProperty(exports, "bronzeDark", { enumerable: true, get: function () { return bronze_1.bronze; } });
var brown_1 = require("./dark/brown");
Object.defineProperty(exports, "brownDark", { enumerable: true, get: function () { return brown_1.brown; } });
var crimson_1 = require("./dark/crimson");
Object.defineProperty(exports, "crimsonDark", { enumerable: true, get: function () { return crimson_1.crimson; } });
var cyan_1 = require("./dark/cyan");
Object.defineProperty(exports, "cyanDark", { enumerable: true, get: function () { return cyan_1.cyan; } });
var gold_1 = require("./dark/gold");
Object.defineProperty(exports, "goldDark", { enumerable: true, get: function () { return gold_1.gold; } });
var grass_1 = require("./dark/grass");
Object.defineProperty(exports, "grassDark", { enumerable: true, get: function () { return grass_1.grass; } });
var gray_1 = require("./dark/gray");
Object.defineProperty(exports, "grayDark", { enumerable: true, get: function () { return gray_1.gray; } });
var green_1 = require("./dark/green");
Object.defineProperty(exports, "greenDark", { enumerable: true, get: function () { return green_1.green; } });
var indigo_1 = require("./dark/indigo");
Object.defineProperty(exports, "indigoDark", { enumerable: true, get: function () { return indigo_1.indigo; } });
var lime_1 = require("./dark/lime");
Object.defineProperty(exports, "limeDark", { enumerable: true, get: function () { return lime_1.lime; } });
var mauve_1 = require("./dark/mauve");
Object.defineProperty(exports, "mauveDark", { enumerable: true, get: function () { return mauve_1.mauve; } });
var mint_1 = require("./dark/mint");
Object.defineProperty(exports, "mintDark", { enumerable: true, get: function () { return mint_1.mint; } });
var olive_1 = require("./dark/olive");
Object.defineProperty(exports, "oliveDark", { enumerable: true, get: function () { return olive_1.olive; } });
var orange_1 = require("./dark/orange");
Object.defineProperty(exports, "orangeDark", { enumerable: true, get: function () { return orange_1.orange; } });
var pink_1 = require("./dark/pink");
Object.defineProperty(exports, "pinkDark", { enumerable: true, get: function () { return pink_1.pink; } });
var plum_1 = require("./dark/plum");
Object.defineProperty(exports, "plumDark", { enumerable: true, get: function () { return plum_1.plum; } });
var purple_1 = require("./dark/purple");
Object.defineProperty(exports, "purpleDark", { enumerable: true, get: function () { return purple_1.purple; } });
var red_1 = require("./dark/red");
Object.defineProperty(exports, "redDark", { enumerable: true, get: function () { return red_1.red; } });
var sage_1 = require("./dark/sage");
Object.defineProperty(exports, "sageDark", { enumerable: true, get: function () { return sage_1.sage; } });
var sand_1 = require("./dark/sand");
Object.defineProperty(exports, "sandDark", { enumerable: true, get: function () { return sand_1.sand; } });
var sky_1 = require("./dark/sky");
Object.defineProperty(exports, "skyDark", { enumerable: true, get: function () { return sky_1.sky; } });
var slate_1 = require("./dark/slate");
Object.defineProperty(exports, "slateDark", { enumerable: true, get: function () { return slate_1.slate; } });
var teal_1 = require("./dark/teal");
Object.defineProperty(exports, "tealDark", { enumerable: true, get: function () { return teal_1.teal; } });
var tomato_1 = require("./dark/tomato");
Object.defineProperty(exports, "tomatoDark", { enumerable: true, get: function () { return tomato_1.tomato; } });
var violet_1 = require("./dark/violet");
Object.defineProperty(exports, "violetDark", { enumerable: true, get: function () { return violet_1.violet; } });
var yellow_1 = require("./dark/yellow");
Object.defineProperty(exports, "yellowDark", { enumerable: true, get: function () { return yellow_1.yellow; } });
var amberA_1 = require("./dark/amberA");
Object.defineProperty(exports, "amberDarkA", { enumerable: true, get: function () { return amberA_1.amberA; } });
var blueA_1 = require("./dark/blueA");
Object.defineProperty(exports, "blueDarkA", { enumerable: true, get: function () { return blueA_1.blueA; } });
var bronzeA_1 = require("./dark/bronzeA");
Object.defineProperty(exports, "bronzeDarkA", { enumerable: true, get: function () { return bronzeA_1.bronzeA; } });
var brownA_1 = require("./dark/brownA");
Object.defineProperty(exports, "brownDarkA", { enumerable: true, get: function () { return brownA_1.brownA; } });
var crimsonA_1 = require("./dark/crimsonA");
Object.defineProperty(exports, "crimsonDarkA", { enumerable: true, get: function () { return crimsonA_1.crimsonA; } });
var cyanA_1 = require("./dark/cyanA");
Object.defineProperty(exports, "cyanDarkA", { enumerable: true, get: function () { return cyanA_1.cyanA; } });
var goldA_1 = require("./dark/goldA");
Object.defineProperty(exports, "goldDarkA", { enumerable: true, get: function () { return goldA_1.goldA; } });
var grassA_1 = require("./dark/grassA");
Object.defineProperty(exports, "grassDarkA", { enumerable: true, get: function () { return grassA_1.grassA; } });
var grayA_1 = require("./dark/grayA");
Object.defineProperty(exports, "grayDarkA", { enumerable: true, get: function () { return grayA_1.grayA; } });
var greenA_1 = require("./dark/greenA");
Object.defineProperty(exports, "greenDarkA", { enumerable: true, get: function () { return greenA_1.greenA; } });
var indigoA_1 = require("./dark/indigoA");
Object.defineProperty(exports, "indigoDarkA", { enumerable: true, get: function () { return indigoA_1.indigoA; } });
var limeA_1 = require("./dark/limeA");
Object.defineProperty(exports, "limeDarkA", { enumerable: true, get: function () { return limeA_1.limeA; } });
var mauveA_1 = require("./dark/mauveA");
Object.defineProperty(exports, "mauveDarkA", { enumerable: true, get: function () { return mauveA_1.mauveA; } });
var mintA_1 = require("./dark/mintA");
Object.defineProperty(exports, "mintDarkA", { enumerable: true, get: function () { return mintA_1.mintA; } });
var oliveA_1 = require("./dark/oliveA");
Object.defineProperty(exports, "oliveDarkA", { enumerable: true, get: function () { return oliveA_1.oliveA; } });
var orangeA_1 = require("./dark/orangeA");
Object.defineProperty(exports, "orangeDarkA", { enumerable: true, get: function () { return orangeA_1.orangeA; } });
var pinkA_1 = require("./dark/pinkA");
Object.defineProperty(exports, "pinkDarkA", { enumerable: true, get: function () { return pinkA_1.pinkA; } });
var plumA_1 = require("./dark/plumA");
Object.defineProperty(exports, "plumDarkA", { enumerable: true, get: function () { return plumA_1.plumA; } });
var purpleA_1 = require("./dark/purpleA");
Object.defineProperty(exports, "purpleDarkA", { enumerable: true, get: function () { return purpleA_1.purpleA; } });
var redA_1 = require("./dark/redA");
Object.defineProperty(exports, "redDarkA", { enumerable: true, get: function () { return redA_1.redA; } });
var sageA_1 = require("./dark/sageA");
Object.defineProperty(exports, "sageDarkA", { enumerable: true, get: function () { return sageA_1.sageA; } });
var sandA_1 = require("./dark/sandA");
Object.defineProperty(exports, "sandDarkA", { enumerable: true, get: function () { return sandA_1.sandA; } });
var skyA_1 = require("./dark/skyA");
Object.defineProperty(exports, "skyDarkA", { enumerable: true, get: function () { return skyA_1.skyA; } });
var slateA_1 = require("./dark/slateA");
Object.defineProperty(exports, "slateDarkA", { enumerable: true, get: function () { return slateA_1.slateA; } });
var tealA_1 = require("./dark/tealA");
Object.defineProperty(exports, "tealDarkA", { enumerable: true, get: function () { return tealA_1.tealA; } });
var tomatoA_1 = require("./dark/tomatoA");
Object.defineProperty(exports, "tomatoDarkA", { enumerable: true, get: function () { return tomatoA_1.tomatoA; } });
var violetA_1 = require("./dark/violetA");
Object.defineProperty(exports, "violetDarkA", { enumerable: true, get: function () { return violetA_1.violetA; } });
var yellowA_1 = require("./dark/yellowA");
Object.defineProperty(exports, "yellowDarkA", { enumerable: true, get: function () { return yellowA_1.yellowA; } });
var amber_2 = require("./light/amber");
Object.defineProperty(exports, "amber", { enumerable: true, get: function () { return amber_2.amber; } });
var blue_2 = require("./light/blue");
Object.defineProperty(exports, "blue", { enumerable: true, get: function () { return blue_2.blue; } });
var bronze_2 = require("./light/bronze");
Object.defineProperty(exports, "bronze", { enumerable: true, get: function () { return bronze_2.bronze; } });
var brown_2 = require("./light/brown");
Object.defineProperty(exports, "brown", { enumerable: true, get: function () { return brown_2.brown; } });
var crimson_2 = require("./light/crimson");
Object.defineProperty(exports, "crimson", { enumerable: true, get: function () { return crimson_2.crimson; } });
var cyan_2 = require("./light/cyan");
Object.defineProperty(exports, "cyan", { enumerable: true, get: function () { return cyan_2.cyan; } });
var gold_2 = require("./light/gold");
Object.defineProperty(exports, "gold", { enumerable: true, get: function () { return gold_2.gold; } });
var grass_2 = require("./light/grass");
Object.defineProperty(exports, "grass", { enumerable: true, get: function () { return grass_2.grass; } });
var gray_2 = require("./light/gray");
Object.defineProperty(exports, "gray", { enumerable: true, get: function () { return gray_2.gray; } });
var green_2 = require("./light/green");
Object.defineProperty(exports, "green", { enumerable: true, get: function () { return green_2.green; } });
var indigo_2 = require("./light/indigo");
Object.defineProperty(exports, "indigo", { enumerable: true, get: function () { return indigo_2.indigo; } });
var lime_2 = require("./light/lime");
Object.defineProperty(exports, "lime", { enumerable: true, get: function () { return lime_2.lime; } });
var mauve_2 = require("./light/mauve");
Object.defineProperty(exports, "mauve", { enumerable: true, get: function () { return mauve_2.mauve; } });
var mint_2 = require("./light/mint");
Object.defineProperty(exports, "mint", { enumerable: true, get: function () { return mint_2.mint; } });
var olive_2 = require("./light/olive");
Object.defineProperty(exports, "olive", { enumerable: true, get: function () { return olive_2.olive; } });
var orange_2 = require("./light/orange");
Object.defineProperty(exports, "orange", { enumerable: true, get: function () { return orange_2.orange; } });
var pink_2 = require("./light/pink");
Object.defineProperty(exports, "pink", { enumerable: true, get: function () { return pink_2.pink; } });
var plum_2 = require("./light/plum");
Object.defineProperty(exports, "plum", { enumerable: true, get: function () { return plum_2.plum; } });
var purple_2 = require("./light/purple");
Object.defineProperty(exports, "purple", { enumerable: true, get: function () { return purple_2.purple; } });
var red_2 = require("./light/red");
Object.defineProperty(exports, "red", { enumerable: true, get: function () { return red_2.red; } });
var sage_2 = require("./light/sage");
Object.defineProperty(exports, "sage", { enumerable: true, get: function () { return sage_2.sage; } });
var sand_2 = require("./light/sand");
Object.defineProperty(exports, "sand", { enumerable: true, get: function () { return sand_2.sand; } });
var sky_2 = require("./light/sky");
Object.defineProperty(exports, "sky", { enumerable: true, get: function () { return sky_2.sky; } });
var slate_2 = require("./light/slate");
Object.defineProperty(exports, "slate", { enumerable: true, get: function () { return slate_2.slate; } });
var teal_2 = require("./light/teal");
Object.defineProperty(exports, "teal", { enumerable: true, get: function () { return teal_2.teal; } });
var tomato_2 = require("./light/tomato");
Object.defineProperty(exports, "tomato", { enumerable: true, get: function () { return tomato_2.tomato; } });
var violet_2 = require("./light/violet");
Object.defineProperty(exports, "violet", { enumerable: true, get: function () { return violet_2.violet; } });
var yellow_2 = require("./light/yellow");
Object.defineProperty(exports, "yellow", { enumerable: true, get: function () { return yellow_2.yellow; } });
var amberA_2 = require("./light/amberA");
Object.defineProperty(exports, "amberA", { enumerable: true, get: function () { return amberA_2.amberA; } });
var blueA_2 = require("./light/blueA");
Object.defineProperty(exports, "blueA", { enumerable: true, get: function () { return blueA_2.blueA; } });
var bronzeA_2 = require("./light/bronzeA");
Object.defineProperty(exports, "bronzeA", { enumerable: true, get: function () { return bronzeA_2.bronzeA; } });
var brownA_2 = require("./light/brownA");
Object.defineProperty(exports, "brownA", { enumerable: true, get: function () { return brownA_2.brownA; } });
var crimsonA_2 = require("./light/crimsonA");
Object.defineProperty(exports, "crimsonA", { enumerable: true, get: function () { return crimsonA_2.crimsonA; } });
var cyanA_2 = require("./light/cyanA");
Object.defineProperty(exports, "cyanA", { enumerable: true, get: function () { return cyanA_2.cyanA; } });
var goldA_2 = require("./light/goldA");
Object.defineProperty(exports, "goldA", { enumerable: true, get: function () { return goldA_2.goldA; } });
var grassA_2 = require("./light/grassA");
Object.defineProperty(exports, "grassA", { enumerable: true, get: function () { return grassA_2.grassA; } });
var grayA_2 = require("./light/grayA");
Object.defineProperty(exports, "grayA", { enumerable: true, get: function () { return grayA_2.grayA; } });
var greenA_2 = require("./light/greenA");
Object.defineProperty(exports, "greenA", { enumerable: true, get: function () { return greenA_2.greenA; } });
var indigoA_2 = require("./light/indigoA");
Object.defineProperty(exports, "indigoA", { enumerable: true, get: function () { return indigoA_2.indigoA; } });
var limeA_2 = require("./light/limeA");
Object.defineProperty(exports, "limeA", { enumerable: true, get: function () { return limeA_2.limeA; } });
var mauveA_2 = require("./light/mauveA");
Object.defineProperty(exports, "mauveA", { enumerable: true, get: function () { return mauveA_2.mauveA; } });
var mintA_2 = require("./light/mintA");
Object.defineProperty(exports, "mintA", { enumerable: true, get: function () { return mintA_2.mintA; } });
var oliveA_2 = require("./light/oliveA");
Object.defineProperty(exports, "oliveA", { enumerable: true, get: function () { return oliveA_2.oliveA; } });
var orangeA_2 = require("./light/orangeA");
Object.defineProperty(exports, "orangeA", { enumerable: true, get: function () { return orangeA_2.orangeA; } });
var pinkA_2 = require("./light/pinkA");
Object.defineProperty(exports, "pinkA", { enumerable: true, get: function () { return pinkA_2.pinkA; } });
var plumA_2 = require("./light/plumA");
Object.defineProperty(exports, "plumA", { enumerable: true, get: function () { return plumA_2.plumA; } });
var purpleA_2 = require("./light/purpleA");
Object.defineProperty(exports, "purpleA", { enumerable: true, get: function () { return purpleA_2.purpleA; } });
var redA_2 = require("./light/redA");
Object.defineProperty(exports, "redA", { enumerable: true, get: function () { return redA_2.redA; } });
var sageA_2 = require("./light/sageA");
Object.defineProperty(exports, "sageA", { enumerable: true, get: function () { return sageA_2.sageA; } });
var sandA_2 = require("./light/sandA");
Object.defineProperty(exports, "sandA", { enumerable: true, get: function () { return sandA_2.sandA; } });
var skyA_2 = require("./light/skyA");
Object.defineProperty(exports, "skyA", { enumerable: true, get: function () { return skyA_2.skyA; } });
var slateA_2 = require("./light/slateA");
Object.defineProperty(exports, "slateA", { enumerable: true, get: function () { return slateA_2.slateA; } });
var tealA_2 = require("./light/tealA");
Object.defineProperty(exports, "tealA", { enumerable: true, get: function () { return tealA_2.tealA; } });
var tomatoA_2 = require("./light/tomatoA");
Object.defineProperty(exports, "tomatoA", { enumerable: true, get: function () { return tomatoA_2.tomatoA; } });
var violetA_2 = require("./light/violetA");
Object.defineProperty(exports, "violetA", { enumerable: true, get: function () { return violetA_2.violetA; } });
var yellowA_2 = require("./light/yellowA");
Object.defineProperty(exports, "yellowA", { enumerable: true, get: function () { return yellowA_2.yellowA; } });
var blackA_1 = require("./blackA");
Object.defineProperty(exports, "blackA", { enumerable: true, get: function () { return blackA_1.blackA; } });
var whiteA_1 = require("./whiteA");
Object.defineProperty(exports, "whiteA", { enumerable: true, get: function () { return whiteA_1.whiteA; } });
