// all exports here for better tree shaking compat

export { amber as amberDark } from './dark/amber.ts'
export { blue as blueDark } from './dark/blue.ts'
export { bronze as bronzeDark } from './dark/bronze.ts'
export { brown as brownDark } from './dark/brown.ts'
export { crimson as crimsonDark } from './dark/crimson.ts'
export { cyan as cyanDark } from './dark/cyan.ts'
export { gold as goldDark } from './dark/gold.ts'
export { grass as grassDark } from './dark/grass.ts'
export { gray as grayDark } from './dark/gray.ts'
export { green as greenDark } from './dark/green.ts'
export { indigo as indigoDark } from './dark/indigo.ts'
export { lime as limeDark } from './dark/lime.ts'
export { mauve as mauveDark } from './dark/mauve.ts'
export { mint as mintDark } from './dark/mint.ts'
export { olive as oliveDark } from './dark/olive.ts'
export { orange as orangeDark } from './dark/orange.ts'
export { pink as pinkDark } from './dark/pink.ts'
export { plum as plumDark } from './dark/plum.ts'
export { purple as purpleDark } from './dark/purple.ts'
export { red as redDark } from './dark/red.ts'
export { sage as sageDark } from './dark/sage.ts'
export { sand as sandDark } from './dark/sand.ts'
export { sky as skyDark } from './dark/sky.ts'
export { slate as slateDark } from './dark/slate.ts'
export { teal as tealDark } from './dark/teal.ts'
export { tomato as tomatoDark } from './dark/tomato.ts'
export { violet as violetDark } from './dark/violet.ts'
export { yellow as yellowDark } from './dark/yellow.ts'

export { amberA as amberDarkA } from './dark/amberA.ts'
export { blueA as blueDarkA } from './dark/blueA.ts'
export { bronzeA as bronzeDarkA } from './dark/bronzeA.ts'
export { brownA as brownDarkA } from './dark/brownA.ts'
export { crimsonA as crimsonDarkA } from './dark/crimsonA.ts'
export { cyanA as cyanDarkA } from './dark/cyanA.ts'
export { goldA as goldDarkA } from './dark/goldA.ts'
export { grassA as grassDarkA } from './dark/grassA.ts'
export { grayA as grayDarkA } from './dark/grayA.ts'
export { greenA as greenDarkA } from './dark/greenA.ts'
export { indigoA as indigoDarkA } from './dark/indigoA.ts'
export { limeA as limeDarkA } from './dark/limeA.ts'
export { mauveA as mauveDarkA } from './dark/mauveA.ts'
export { mintA as mintDarkA } from './dark/mintA.ts'
export { oliveA as oliveDarkA } from './dark/oliveA.ts'
export { orangeA as orangeDarkA } from './dark/orangeA.ts'
export { pinkA as pinkDarkA } from './dark/pinkA.ts'
export { plumA as plumDarkA } from './dark/plumA.ts'
export { purpleA as purpleDarkA } from './dark/purpleA.ts'
export { redA as redDarkA } from './dark/redA.ts'
export { sageA as sageDarkA } from './dark/sageA.ts'
export { sandA as sandDarkA } from './dark/sandA.ts'
export { skyA as skyDarkA } from './dark/skyA.ts'
export { slateA as slateDarkA } from './dark/slateA.ts'
export { tealA as tealDarkA } from './dark/tealA.ts'
export { tomatoA as tomatoDarkA } from './dark/tomatoA.ts'
export { violetA as violetDarkA } from './dark/violetA.ts'
export { yellowA as yellowDarkA } from './dark/yellowA.ts'

export { amber } from './light/amber.ts'
export { blue } from './light/blue.ts'
export { bronze } from './light/bronze.ts'
export { brown } from './light/brown.ts'
export { crimson } from './light/crimson.ts'
export { cyan } from './light/cyan.ts'
export { gold } from './light/gold.ts'
export { grass } from './light/grass.ts'
export { gray } from './light/gray.ts'
export { green } from './light/green.ts'
export { indigo } from './light/indigo.ts'
export { lime } from './light/lime.ts'
export { mauve } from './light/mauve.ts'
export { mint } from './light/mint.ts'
export { olive } from './light/olive.ts'
export { orange } from './light/orange.ts'
export { pink } from './light/pink.ts'
export { plum } from './light/plum.ts'
export { purple } from './light/purple.ts'
export { red } from './light/red.ts'
export { sage } from './light/sage.ts'
export { sand } from './light/sand.ts'
export { sky } from './light/sky.ts'
export { slate } from './light/slate.ts'
export { teal } from './light/teal.ts'
export { tomato } from './light/tomato.ts'
export { violet } from './light/violet.ts'
export { yellow } from './light/yellow.ts'

export { amberA } from './light/amberA.ts'
export { blueA } from './light/blueA.ts'
export { bronzeA } from './light/bronzeA.ts'
export { brownA } from './light/brownA.ts'
export { crimsonA } from './light/crimsonA.ts'
export { cyanA } from './light/cyanA.ts'
export { goldA } from './light/goldA.ts'
export { grassA } from './light/grassA.ts'
export { grayA } from './light/grayA.ts'
export { greenA } from './light/greenA.ts'
export { indigoA } from './light/indigoA.ts'
export { limeA } from './light/limeA.ts'
export { mauveA } from './light/mauveA.ts'
export { mintA } from './light/mintA.ts'
export { oliveA } from './light/oliveA.ts'
export { orangeA } from './light/orangeA.ts'
export { pinkA } from './light/pinkA.ts'
export { plumA } from './light/plumA.ts'
export { purpleA } from './light/purpleA.ts'
export { redA } from './light/redA.ts'
export { sageA } from './light/sageA.ts'
export { sandA } from './light/sandA.ts'
export { skyA } from './light/skyA.ts'
export { slateA } from './light/slateA.ts'
export { tealA } from './light/tealA.ts'
export { tomatoA } from './light/tomatoA.ts'
export { violetA } from './light/violetA.ts'
export { yellowA } from './light/yellowA.ts'

export { blackA } from './blackA.ts'
export { whiteA } from './whiteA.ts'
