// all exports here for better tree shaking compat

export { amber as amberDark } from './legacy/dark/amber.ts'
export { blue as blueDark } from './legacy/dark/blue.ts'
export { bronze as bronzeDark } from './legacy/dark/bronze.ts'
export { brown as brownDark } from './legacy/dark/brown.ts'
export { crimson as crimsonDark } from './legacy/dark/crimson.ts'
export { cyan as cyanDark } from './legacy/dark/cyan.ts'
export { gold as goldDark } from './legacy/dark/gold.ts'
export { grass as grassDark } from './legacy/dark/grass.ts'
export { gray as grayDark } from './legacy/dark/gray.ts'
export { green as greenDark } from './legacy/dark/green.ts'
export { indigo as indigoDark } from './legacy/dark/indigo.ts'
export { lime as limeDark } from './legacy/dark/lime.ts'
export { mauve as mauveDark } from './legacy/dark/mauve.ts'
export { mint as mintDark } from './legacy/dark/mint.ts'
export { olive as oliveDark } from './legacy/dark/olive.ts'
export { orange as orangeDark } from './legacy/dark/orange.ts'
export { pink as pinkDark } from './legacy/dark/pink.ts'
export { plum as plumDark } from './legacy/dark/plum.ts'
export { purple as purpleDark } from './legacy/dark/purple.ts'
export { red as redDark } from './legacy/dark/red.ts'
export { sage as sageDark } from './legacy/dark/sage.ts'
export { sand as sandDark } from './legacy/dark/sand.ts'
export { sky as skyDark } from './legacy/dark/sky.ts'
export { slate as slateDark } from './legacy/dark/slate.ts'
export { teal as tealDark } from './legacy/dark/teal.ts'
export { tomato as tomatoDark } from './legacy/dark/tomato.ts'
export { violet as violetDark } from './legacy/dark/violet.ts'
export { yellow as yellowDark } from './legacy/dark/yellow.ts'

export { amberA as amberDarkA } from './legacy/dark/amberA.ts'
export { blueA as blueDarkA } from './legacy/dark/blueA.ts'
export { bronzeA as bronzeDarkA } from './legacy/dark/bronzeA.ts'
export { brownA as brownDarkA } from './legacy/dark/brownA.ts'
export { crimsonA as crimsonDarkA } from './legacy/dark/crimsonA.ts'
export { cyanA as cyanDarkA } from './legacy/dark/cyanA.ts'
export { goldA as goldDarkA } from './legacy/dark/goldA.ts'
export { grassA as grassDarkA } from './legacy/dark/grassA.ts'
export { grayA as grayDarkA } from './legacy/dark/grayA.ts'
export { greenA as greenDarkA } from './legacy/dark/greenA.ts'
export { indigoA as indigoDarkA } from './legacy/dark/indigoA.ts'
export { limeA as limeDarkA } from './legacy/dark/limeA.ts'
export { mauveA as mauveDarkA } from './legacy/dark/mauveA.ts'
export { mintA as mintDarkA } from './legacy/dark/mintA.ts'
export { oliveA as oliveDarkA } from './legacy/dark/oliveA.ts'
export { orangeA as orangeDarkA } from './legacy/dark/orangeA.ts'
export { pinkA as pinkDarkA } from './legacy/dark/pinkA.ts'
export { plumA as plumDarkA } from './legacy/dark/plumA.ts'
export { purpleA as purpleDarkA } from './legacy/dark/purpleA.ts'
export { redA as redDarkA } from './legacy/dark/redA.ts'
export { sageA as sageDarkA } from './legacy/dark/sageA.ts'
export { sandA as sandDarkA } from './legacy/dark/sandA.ts'
export { skyA as skyDarkA } from './legacy/dark/skyA.ts'
export { slateA as slateDarkA } from './legacy/dark/slateA.ts'
export { tealA as tealDarkA } from './legacy/dark/tealA.ts'
export { tomatoA as tomatoDarkA } from './legacy/dark/tomatoA.ts'
export { violetA as violetDarkA } from './legacy/dark/violetA.ts'
export { yellowA as yellowDarkA } from './legacy/dark/yellowA.ts'

export { amber } from './legacy/light/amber.ts'
export { blue } from './legacy/light/blue.ts'
export { bronze } from './legacy/light/bronze.ts'
export { brown } from './legacy/light/brown.ts'
export { crimson } from './legacy/light/crimson.ts'
export { cyan } from './legacy/light/cyan.ts'
export { gold } from './legacy/light/gold.ts'
export { grass } from './legacy/light/grass.ts'
export { gray } from './legacy/light/gray.ts'
export { green } from './legacy/light/green.ts'
export { indigo } from './legacy/light/indigo.ts'
export { lime } from './legacy/light/lime.ts'
export { mauve } from './legacy/light/mauve.ts'
export { mint } from './legacy/light/mint.ts'
export { olive } from './legacy/light/olive.ts'
export { orange } from './legacy/light/orange.ts'
export { pink } from './legacy/light/pink.ts'
export { plum } from './legacy/light/plum.ts'
export { purple } from './legacy/light/purple.ts'
export { red } from './legacy/light/red.ts'
export { sage } from './legacy/light/sage.ts'
export { sand } from './legacy/light/sand.ts'
export { sky } from './legacy/light/sky.ts'
export { slate } from './legacy/light/slate.ts'
export { teal } from './legacy/light/teal.ts'
export { tomato } from './legacy/light/tomato.ts'
export { violet } from './legacy/light/violet.ts'
export { yellow } from './legacy/light/yellow.ts'

export { amberA } from './legacy/light/amberA.ts'
export { blueA } from './legacy/light/blueA.ts'
export { bronzeA } from './legacy/light/bronzeA.ts'
export { brownA } from './legacy/light/brownA.ts'
export { crimsonA } from './legacy/light/crimsonA.ts'
export { cyanA } from './legacy/light/cyanA.ts'
export { goldA } from './legacy/light/goldA.ts'
export { grassA } from './legacy/light/grassA.ts'
export { grayA } from './legacy/light/grayA.ts'
export { greenA } from './legacy/light/greenA.ts'
export { indigoA } from './legacy/light/indigoA.ts'
export { limeA } from './legacy/light/limeA.ts'
export { mauveA } from './legacy/light/mauveA.ts'
export { mintA } from './legacy/light/mintA.ts'
export { oliveA } from './legacy/light/oliveA.ts'
export { orangeA } from './legacy/light/orangeA.ts'
export { pinkA } from './legacy/light/pinkA.ts'
export { plumA } from './legacy/light/plumA.ts'
export { purpleA } from './legacy/light/purpleA.ts'
export { redA } from './legacy/light/redA.ts'
export { sageA } from './legacy/light/sageA.ts'
export { sandA } from './legacy/light/sandA.ts'
export { skyA } from './legacy/light/skyA.ts'
export { slateA } from './legacy/light/slateA.ts'
export { tealA } from './legacy/light/tealA.ts'
export { tomatoA } from './legacy/light/tomatoA.ts'
export { violetA } from './legacy/light/violetA.ts'
export { yellowA } from './legacy/light/yellowA.ts'

export { blackA } from './blackA.ts'
export { whiteA } from './whiteA.ts'
