import { ethers } from 'ethers';
import { create } from 'zustand';
import { devtools, persist } from 'zustand/middleware';

import { safeInvoke } from '../utils/tauri-check';

export type Wallet = {
  address: string;
  mnemonic: string;
  privateKey: string;
  isAutoGenerated: boolean;
  createdAt: number;
  backedUp: boolean;
  lastBackupPrompt: number;
};

export enum NetworkType {
  HanzoMainnet = 'hanzo-mainnet',
  HanzoTestnet = 'hanzo-testnet',
  ZooMainnet = 'zoo-mainnet',
  ZooTestnet = 'zoo-testnet',
  ZooDevnet = 'zoo-devnet',
  BaseSepolia = 'base-sepolia',
  Custom = 'custom',
}

export interface NetworkConfig {
  name: string;
  chainId: number;
  rpcUrl: string;
  blockExplorer: string;
  nativeCurrency: {
    name: string;
    symbol: string;
    decimals: number;
  };
  isMiningEnabled: boolean;
}

export const NETWORKS: Record<NetworkType, NetworkConfig> = {
  [NetworkType.HanzoMainnet]: {
    name: 'Hanzo Mainnet',
    chainId: 36900,
    rpcUrl: 'https://rpc.hanzo.network',
    blockExplorer: 'https://explorer.hanzo.network',
    nativeCurrency: { name: 'AI Token', symbol: 'AI', decimals: 18 },
    isMiningEnabled: true,
  },
  [NetworkType.HanzoTestnet]: {
    name: 'Hanzo Testnet',
    chainId: 36901,
    rpcUrl: 'https://rpc.hanzo-test.network',
    blockExplorer: 'https://explorer.hanzo-test.network',
    nativeCurrency: { name: 'Test AI', symbol: 'tAI', decimals: 18 },
    isMiningEnabled: true,
  },
  [NetworkType.ZooMainnet]: {
    name: 'Zoo Mainnet',
    chainId: 200200,
    rpcUrl: 'https://rpc.zoo.network',
    blockExplorer: 'https://explorer.zoo.network',
    nativeCurrency: { name: 'Zoo Token', symbol: 'ZOO', decimals: 18 },
    isMiningEnabled: true,
  },
  [NetworkType.ZooTestnet]: {
    name: 'Zoo Testnet',
    chainId: 200201,
    rpcUrl: 'https://rpc.zoo-test.network',
    blockExplorer: 'https://explorer.zoo-test.network',
    nativeCurrency: { name: 'Test Zoo', symbol: 'tZOO', decimals: 18 },
    isMiningEnabled: true,
  },
  [NetworkType.ZooDevnet]: {
    name: 'Zoo Devnet',
    chainId: 200202,
    rpcUrl: 'https://rpc.zoo-dev.network',
    blockExplorer: 'https://explorer.zoo-dev.network',
    nativeCurrency: { name: 'Dev Zoo', symbol: 'dZOO', decimals: 18 },
    isMiningEnabled: true,
  },
  [NetworkType.BaseSepolia]: {
    name: 'Base Sepolia',
    chainId: 84532,
    rpcUrl: 'https://sepolia.base.org',
    blockExplorer: 'https://sepolia.basescan.org',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
    isMiningEnabled: false,
  },
  [NetworkType.Custom]: {
    name: 'Custom Network',
    chainId: 0,
    rpcUrl: 'http://127.0.0.1:8545',
    blockExplorer: '',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
    isMiningEnabled: false,
  },
};

type WalletStore = {
  wallet: Wallet | null;
  isInitialized: boolean;
  selectedNetwork: NetworkType;
  showBackupPrompt: boolean;

  createWallet: () => Promise<Wallet>;
  importWallet: (mnemonic: string) => Wallet;
  clearSensitiveData: () => void;
  setWallet: (wallet: Wallet | null) => void;
  getWalletAddress: () => string | null;
  markAsBackedUp: () => void;
  dismissBackupPrompt: () => void;
  setSelectedNetwork: (network: NetworkType) => void;
  getNetworkConfig: () => NetworkConfig;
  saveMnemonicSecurely: (mnemonic: string) => Promise<void>;
  loadMnemonicSecurely: () => Promise<string | null>;
};

export const useWallet = create<WalletStore>()(
  devtools(
    persist(
      (set, get) => ({
        wallet: null,
        isInitialized: false,
        selectedNetwork: NetworkType.HanzoMainnet,
        showBackupPrompt: false,

        createWallet: async () => {
          const wallet = ethers.Wallet.createRandom();
          const mnemonic = wallet.mnemonic?.phrase || '';

          const newWallet: Wallet = {
            address: wallet.address,
            mnemonic,
            privateKey: wallet.privateKey,
            isAutoGenerated: true,
            createdAt: Date.now(),
            backedUp: false,
            lastBackupPrompt: Date.now(),
          };

          await get().saveMnemonicSecurely(mnemonic);

          set({
            wallet: newWallet,
            isInitialized: true,
            showBackupPrompt: true,
          });
          return newWallet;
        },

        importWallet: (mnemonic: string) => {
          const wallet = ethers.Wallet.fromPhrase(mnemonic.trim());
          const newWallet: Wallet = {
            address: wallet.address,
            mnemonic: mnemonic.trim(),
            privateKey: wallet.privateKey,
            isAutoGenerated: false,
            createdAt: Date.now(),
            backedUp: true,
            lastBackupPrompt: Date.now(),
          };

          void get().saveMnemonicSecurely(mnemonic.trim());

          set({ wallet: newWallet, isInitialized: true });
          return newWallet;
        },

        clearSensitiveData: () => {
          const current = get().wallet;
          if (current) {
            set({
              wallet: {
                ...current,
                mnemonic: '',
                privateKey: '',
              },
            });
          }
        },

        setWallet: (wallet: Wallet | null) => {
          set({ wallet, isInitialized: true });
        },

        getWalletAddress: () => {
          const { wallet } = get();
          return wallet?.address || null;
        },

        markAsBackedUp: () => {
          const current = get().wallet;
          if (current) {
            set({
              wallet: { ...current, backedUp: true },
              showBackupPrompt: false,
            });
          }
        },

        dismissBackupPrompt: () => {
          const current = get().wallet;
          if (current) {
            set({
              wallet: { ...current, lastBackupPrompt: Date.now() },
              showBackupPrompt: false,
            });
          }
        },

        setSelectedNetwork: (network: NetworkType) => {
          set({ selectedNetwork: network });
        },

        getNetworkConfig: () => {
          const { selectedNetwork } = get();
          return NETWORKS[selectedNetwork];
        },

        saveMnemonicSecurely: async (mnemonic: string) => {
          await safeInvoke('secure_storage_set', {
            key: 'wallet_mnemonic',
            value: mnemonic,
          });
        },

        loadMnemonicSecurely: async () => {
          return await safeInvoke<string>('secure_storage_get', {
            key: 'wallet_mnemonic',
          });
        },
      }),
      {
        name: 'hanzo-wallet',
        partialize: (state) => ({
          wallet: state.wallet
            ? {
                address: state.wallet.address,
                isAutoGenerated: state.wallet.isAutoGenerated,
                createdAt: state.wallet.createdAt,
                backedUp: state.wallet.backedUp,
                lastBackupPrompt: state.wallet.lastBackupPrompt,
                mnemonic: '',
                privateKey: '',
              }
            : null,
          isInitialized: state.isInitialized,
          selectedNetwork: state.selectedNetwork,
        }),
      },
    ),
  ),
);
