"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.useMergeRefs = exports.StyleSheet = exports.processColor = exports.InteractionManager = exports.useStable = exports.useLayoutEffect = exports.useHover = exports.useEvent = exports.useElementLayout = exports.unitlessNumbers = exports.UIManager = exports.TextInputState = exports.setValueForStyles = exports.createSheet = exports.flattenStyle = exports.Platform = exports.pick = exports.normalizeColor = exports.multiplyStyleLengthValue = exports.isWebColor = exports.isSelectionValid = exports.ImageLoader = exports.getBoundingClientRect = exports.dismissKeyboard = exports.createEventHandle = exports.createTransformValue = exports.createReactDOMStyle = exports.stylesFromProps = exports.createDOMProps = exports.canUseDOM = exports.AccessibilityUtil = exports.colorProps = exports.TextAncestorContext = exports.usePlatformMethods = void 0;
__exportStar(require("./modules/AssetRegistry/index"), exports);
__exportStar(require("./modules/forwardedProps/index"), exports);
__exportStar(require("./modules/mergeRefs/index"), exports);
__exportStar(require("./modules/modality/index"), exports);
__exportStar(require("./modules/useLocale/index"), exports);
var index_1 = require("./modules/usePlatformMethods/index");
Object.defineProperty(exports, "usePlatformMethods", { enumerable: true, get: function () { return index_1.usePlatformMethods; } });
var TextAncestorContext_1 = require("./TextAncestorContext");
Object.defineProperty(exports, "TextAncestorContext", { enumerable: true, get: function () { return TextAncestorContext_1.TextAncestorContext; } });
__exportStar(require("@hanzogui/react-native-use-pressable"), exports);
__exportStar(require("@hanzogui/react-native-use-responder-events"), exports);
var colorProps_1 = require("./colorProps");
Object.defineProperty(exports, "colorProps", { enumerable: true, get: function () { return colorProps_1.colorProps; } });
var index_2 = require("./modules/AccessibilityUtil/index");
Object.defineProperty(exports, "AccessibilityUtil", { enumerable: true, get: function () { return index_2.AccessibilityUtil; } });
var canUseDOM_1 = require("./modules/canUseDOM");
Object.defineProperty(exports, "canUseDOM", { enumerable: true, get: function () { return canUseDOM_1.canUseDOM; } });
var index_3 = require("./modules/createDOMProps/index");
Object.defineProperty(exports, "createDOMProps", { enumerable: true, get: function () { return index_3.createDOMProps; } });
var index_4 = require("./modules/createDOMProps/index");
Object.defineProperty(exports, "stylesFromProps", { enumerable: true, get: function () { return index_4.stylesFromProps; } });
var createReactDOMStyle_1 = require("./StyleSheet/compiler/createReactDOMStyle");
Object.defineProperty(exports, "createReactDOMStyle", { enumerable: true, get: function () { return createReactDOMStyle_1.createReactDOMStyle; } });
Object.defineProperty(exports, "createTransformValue", { enumerable: true, get: function () { return createReactDOMStyle_1.createTransformValue; } });
var index_5 = require("./modules/createEventHandle/index");
Object.defineProperty(exports, "createEventHandle", { enumerable: true, get: function () { return index_5.createEventHandle; } });
var index_6 = require("./modules/dismissKeyboard/index");
Object.defineProperty(exports, "dismissKeyboard", { enumerable: true, get: function () { return index_6.dismissKeyboard; } });
var index_7 = require("./modules/getBoundingClientRect/index");
Object.defineProperty(exports, "getBoundingClientRect", { enumerable: true, get: function () { return index_7.getBoundingClientRect; } });
var index_8 = require("./modules/ImageLoader/index");
Object.defineProperty(exports, "ImageLoader", { enumerable: true, get: function () { return index_8.ImageLoader; } });
var index_9 = require("./modules/isSelectionValid/index");
Object.defineProperty(exports, "isSelectionValid", { enumerable: true, get: function () { return index_9.isSelectionValid; } });
var index_10 = require("./modules/isWebColor/index");
Object.defineProperty(exports, "isWebColor", { enumerable: true, get: function () { return index_10.isWebColor; } });
var index_11 = require("./modules/multiplyStyleLengthValue/index");
Object.defineProperty(exports, "multiplyStyleLengthValue", { enumerable: true, get: function () { return index_11.multiplyStyleLengthValue; } });
var index_12 = require("./modules/normalizeColor/index");
Object.defineProperty(exports, "normalizeColor", { enumerable: true, get: function () { return index_12.normalizeColor; } });
var index_13 = require("./modules/pick/index");
Object.defineProperty(exports, "pick", { enumerable: true, get: function () { return index_13.pick; } });
var index_14 = require("./modules/Platform/index");
Object.defineProperty(exports, "Platform", { enumerable: true, get: function () { return index_14.Platform; } });
__exportStar(require("./StyleSheet/preprocess"), exports);
var index_15 = require("./StyleSheet/index");
Object.defineProperty(exports, "flattenStyle", { enumerable: true, get: function () { return index_15.flatten; } });
var index_16 = require("./StyleSheet/dom/index");
Object.defineProperty(exports, "createSheet", { enumerable: true, get: function () { return index_16.createSheet; } });
var index_17 = require("./modules/requestIdleCallback/index");
Object.defineProperty(exports, "requestIdleCallback", { enumerable: true, get: function () { return index_17.requestIdleCallback; } });
var index_18 = require("./modules/setValueForStyles/index");
Object.defineProperty(exports, "setValueForStyles", { enumerable: true, get: function () { return index_18.setValueForStyles; } });
var index_19 = require("./modules/TextInputState/index");
Object.defineProperty(exports, "TextInputState", { enumerable: true, get: function () { return index_19.TextInputState; } });
var index_20 = require("./modules/UIManager/index");
Object.defineProperty(exports, "UIManager", { enumerable: true, get: function () { return index_20.UIManager; } });
var index_21 = require("./modules/unitlessNumbers/index");
Object.defineProperty(exports, "unitlessNumbers", { enumerable: true, get: function () { return index_21.unitlessNumbers; } });
var index_22 = require("./modules/useElementLayout/index");
Object.defineProperty(exports, "useElementLayout", { enumerable: true, get: function () { return index_22.useElementLayout; } });
var index_23 = require("./modules/useEvent/index");
Object.defineProperty(exports, "useEvent", { enumerable: true, get: function () { return index_23.useEvent; } });
var index_24 = require("./modules/useHover/index");
Object.defineProperty(exports, "useHover", { enumerable: true, get: function () { return index_24.useHover; } });
var index_25 = require("./modules/useLayoutEffect/index");
Object.defineProperty(exports, "useLayoutEffect", { enumerable: true, get: function () { return index_25.useLayoutEffectImpl; } });
var index_26 = require("./modules/useStable/index");
Object.defineProperty(exports, "useStable", { enumerable: true, get: function () { return index_26.useStable; } });
var InteractionManager_1 = require("./modules/InteractionManager");
Object.defineProperty(exports, "InteractionManager", { enumerable: true, get: function () { return InteractionManager_1.InteractionManager; } });
__exportStar(require("./modules/invariant"), exports);
var index_27 = require("./modules/processColor/index");
Object.defineProperty(exports, "processColor", { enumerable: true, get: function () { return index_27.processColor; } });
var index_28 = require("./StyleSheet/index");
Object.defineProperty(exports, "StyleSheet", { enumerable: true, get: function () { return index_28.StyleSheet; } });
var index_29 = require("./modules/useMergeRefs/index");
Object.defineProperty(exports, "useMergeRefs", { enumerable: true, get: function () { return index_29.useMergeRefs; } });
