export declare const palettes: {
    light_hanzo: string[];
    light_lux: string[];
    light_zoo: string[];
    light_pars: string[];
    dark_hanzo: string[];
    dark_lux: string[];
    dark_zoo: string[];
    dark_pars: string[];
    dark_blue: string[];
    dark_gray: string[];
    dark_green: string[];
    dark_orange: string[];
    dark_pink: string[];
    dark_purple: string[];
    dark_red: string[];
    dark_yellow: string[];
    light_blue: string[];
    light_gray: string[];
    light_green: string[];
    light_orange: string[];
    light_pink: string[];
    light_purple: string[];
    light_red: string[];
    light_yellow: string[];
    light: string[];
    dark: string[];
};
//# sourceMappingURL=palettes.d.ts.map