import type { Variable } from '@hanzogui/web';
export declare const size: {
    $0: number;
    '$0.25': number;
    '$0.5': number;
    '$0.75': number;
    $1: number;
    '$1.5': number;
    $2: number;
    '$2.5': number;
    $3: number;
    '$3.5': number;
    $4: number;
    $true: number;
    '$4.5': number;
    $5: number;
    $6: number;
    $7: number;
    $8: number;
    $9: number;
    $10: number;
    $11: number;
    $12: number;
    $13: number;
    $14: number;
    $15: number;
    $16: number;
    $17: number;
    $18: number;
    $19: number;
    $20: number;
};
type SizeKeysIn = keyof typeof size;
type Sizes = {
    [Key in SizeKeysIn extends `$${infer Key}` ? Key : SizeKeysIn]: number;
};
type SizeKeys = `${keyof Sizes extends `${infer K}` ? K : never}`;
type SizeKeysWithNegatives = Exclude<`-${SizeKeys extends `$${infer Key}` ? Key : SizeKeys}`, '-0'> | SizeKeys;
type SizeKeysWithNegativesString = `$${SizeKeysWithNegatives}`;
export declare const space: {
    [Key in SizeKeysWithNegativesString]: Key extends keyof Sizes ? Sizes[Key] : number;
};
export declare const zIndex: {
    0: number;
    1: number;
    2: number;
    3: number;
    4: number;
    5: number;
};
export declare const colorTokens: {
    light: {
        blue: any;
        gray: any;
        green: any;
        orange: any;
        pink: any;
        purple: any;
        red: any;
        yellow: any;
    };
    dark: {
        blue: any;
        gray: any;
        green: any;
        orange: any;
        pink: any;
        purple: any;
        red: any;
        yellow: any;
    };
};
export declare const darkColors: any;
export declare const lightColors: any;
export declare const color: {};
export declare const radius: {
    0: number;
    1: number;
    2: number;
    3: number;
    4: number;
    true: number;
    5: number;
    6: number;
    7: number;
    8: number;
    9: number;
    10: number;
    11: number;
    12: number;
};
export declare const tokens: {
    color: {};
    space: {
        $0: Variable<number>;
        "$0.25": Variable<number>;
        "$0.5": Variable<number>;
        "$0.75": Variable<number>;
        $1: Variable<number>;
        "$1.5": Variable<number>;
        $2: Variable<number>;
        "$2.5": Variable<number>;
        $3: Variable<number>;
        "$3.5": Variable<number>;
        $4: Variable<number>;
        $true: Variable<number>;
        "$4.5": Variable<number>;
        $5: Variable<number>;
        $6: Variable<number>;
        $7: Variable<number>;
        $8: Variable<number>;
        $9: Variable<number>;
        $10: Variable<number>;
        $11: Variable<number>;
        $12: Variable<number>;
        $13: Variable<number>;
        $14: Variable<number>;
        $15: Variable<number>;
        $16: Variable<number>;
        $17: Variable<number>;
        $18: Variable<number>;
        $19: Variable<number>;
        $20: Variable<number>;
        "$-0.25": Variable<number>;
        "$-0.5": Variable<number>;
        "$-0.75": Variable<number>;
        "$-1": Variable<number>;
        "$-1.5": Variable<number>;
        "$-2": Variable<number>;
        "$-2.5": Variable<number>;
        "$-3": Variable<number>;
        "$-3.5": Variable<number>;
        "$-4": Variable<number>;
        "$-true": Variable<number>;
        "$-4.5": Variable<number>;
        "$-5": Variable<number>;
        "$-6": Variable<number>;
        "$-7": Variable<number>;
        "$-8": Variable<number>;
        "$-9": Variable<number>;
        "$-10": Variable<number>;
        "$-11": Variable<number>;
        "$-12": Variable<number>;
        "$-13": Variable<number>;
        "$-14": Variable<number>;
        "$-15": Variable<number>;
        "$-16": Variable<number>;
        "$-17": Variable<number>;
        "$-18": Variable<number>;
        "$-19": Variable<number>;
        "$-20": Variable<number>;
    };
    size: {
        $0: Variable<number>;
        "$0.25": Variable<number>;
        "$0.5": Variable<number>;
        "$0.75": Variable<number>;
        $1: Variable<number>;
        "$1.5": Variable<number>;
        $2: Variable<number>;
        "$2.5": Variable<number>;
        $3: Variable<number>;
        "$3.5": Variable<number>;
        $4: Variable<number>;
        $true: Variable<number>;
        "$4.5": Variable<number>;
        $5: Variable<number>;
        $6: Variable<number>;
        $7: Variable<number>;
        $8: Variable<number>;
        $9: Variable<number>;
        $10: Variable<number>;
        $11: Variable<number>;
        $12: Variable<number>;
        $13: Variable<number>;
        $14: Variable<number>;
        $15: Variable<number>;
        $16: Variable<number>;
        $17: Variable<number>;
        $18: Variable<number>;
        $19: Variable<number>;
        $20: Variable<number>;
    };
    radius: {
        0: Variable<number>;
        1: Variable<number>;
        2: Variable<number>;
        3: Variable<number>;
        4: Variable<number>;
        true: Variable<number>;
        5: Variable<number>;
        6: Variable<number>;
        7: Variable<number>;
        8: Variable<number>;
        9: Variable<number>;
        10: Variable<number>;
        11: Variable<number>;
        12: Variable<number>;
    };
    zIndex: {
        0: Variable<number>;
        1: Variable<number>;
        2: Variable<number>;
        3: Variable<number>;
        4: Variable<number>;
        5: Variable<number>;
    };
} & Omit<{
    color: {};
    radius: {
        0: Variable<number>;
        1: Variable<number>;
        2: Variable<number>;
        3: Variable<number>;
        4: Variable<number>;
        true: Variable<number>;
        5: Variable<number>;
        6: Variable<number>;
        7: Variable<number>;
        8: Variable<number>;
        9: Variable<number>;
        10: Variable<number>;
        11: Variable<number>;
        12: Variable<number>;
    };
    zIndex: {
        0: Variable<number>;
        1: Variable<number>;
        2: Variable<number>;
        3: Variable<number>;
        4: Variable<number>;
        5: Variable<number>;
    };
    space: {
        $0: Variable<number>;
        "$0.25": Variable<number>;
        "$0.5": Variable<number>;
        "$0.75": Variable<number>;
        $1: Variable<number>;
        "$1.5": Variable<number>;
        $2: Variable<number>;
        "$2.5": Variable<number>;
        $3: Variable<number>;
        "$3.5": Variable<number>;
        $4: Variable<number>;
        $true: Variable<number>;
        "$4.5": Variable<number>;
        $5: Variable<number>;
        $6: Variable<number>;
        $7: Variable<number>;
        $8: Variable<number>;
        $9: Variable<number>;
        $10: Variable<number>;
        $11: Variable<number>;
        $12: Variable<number>;
        $13: Variable<number>;
        $14: Variable<number>;
        $15: Variable<number>;
        $16: Variable<number>;
        $17: Variable<number>;
        $18: Variable<number>;
        $19: Variable<number>;
        $20: Variable<number>;
        "$-0.25": Variable<number>;
        "$-0.5": Variable<number>;
        "$-0.75": Variable<number>;
        "$-1": Variable<number>;
        "$-1.5": Variable<number>;
        "$-2": Variable<number>;
        "$-2.5": Variable<number>;
        "$-3": Variable<number>;
        "$-3.5": Variable<number>;
        "$-4": Variable<number>;
        "$-true": Variable<number>;
        "$-4.5": Variable<number>;
        "$-5": Variable<number>;
        "$-6": Variable<number>;
        "$-7": Variable<number>;
        "$-8": Variable<number>;
        "$-9": Variable<number>;
        "$-10": Variable<number>;
        "$-11": Variable<number>;
        "$-12": Variable<number>;
        "$-13": Variable<number>;
        "$-14": Variable<number>;
        "$-15": Variable<number>;
        "$-16": Variable<number>;
        "$-17": Variable<number>;
        "$-18": Variable<number>;
        "$-19": Variable<number>;
        "$-20": Variable<number>;
    };
    size: {
        $0: Variable<number>;
        "$0.25": Variable<number>;
        "$0.5": Variable<number>;
        "$0.75": Variable<number>;
        $1: Variable<number>;
        "$1.5": Variable<number>;
        $2: Variable<number>;
        "$2.5": Variable<number>;
        $3: Variable<number>;
        "$3.5": Variable<number>;
        $4: Variable<number>;
        $true: Variable<number>;
        "$4.5": Variable<number>;
        $5: Variable<number>;
        $6: Variable<number>;
        $7: Variable<number>;
        $8: Variable<number>;
        $9: Variable<number>;
        $10: Variable<number>;
        $11: Variable<number>;
        $12: Variable<number>;
        $13: Variable<number>;
        $14: Variable<number>;
        $15: Variable<number>;
        $16: Variable<number>;
        $17: Variable<number>;
        $18: Variable<number>;
        $19: Variable<number>;
        $20: Variable<number>;
    };
}, "color" | "space" | "size" | "radius" | "zIndex">;
export type hello = 'asdad';
export {};
//# sourceMappingURL=tokens.d.ts.map