export declare const configWithoutAnimations: {
    themes: Record<"light" | "dark" | "light_orange" | "light_yellow" | "light_green" | "light_blue" | "light_purple" | "light_pink" | "light_red" | "dark_orange" | "dark_yellow" | "dark_green" | "dark_blue" | "dark_purple" | "dark_pink" | "dark_red" | "light_alt1" | "light_alt2" | "light_active" | "dark_alt1" | "dark_alt2" | "dark_active" | "light_orange_alt1" | "light_orange_alt2" | "light_orange_active" | "light_yellow_alt1" | "light_yellow_alt2" | "light_yellow_active" | "light_green_alt1" | "light_green_alt2" | "light_green_active" | "light_blue_alt1" | "light_blue_alt2" | "light_blue_active" | "light_purple_alt1" | "light_purple_alt2" | "light_purple_active" | "light_pink_alt1" | "light_pink_alt2" | "light_pink_active" | "light_red_alt1" | "light_red_alt2" | "light_red_active" | "dark_orange_alt1" | "dark_orange_alt2" | "dark_orange_active" | "dark_yellow_alt1" | "dark_yellow_alt2" | "dark_yellow_active" | "dark_green_alt1" | "dark_green_alt2" | "dark_green_active" | "dark_blue_alt1" | "dark_blue_alt2" | "dark_blue_active" | "dark_purple_alt1" | "dark_purple_alt2" | "dark_purple_active" | "dark_pink_alt1" | "dark_pink_alt2" | "dark_pink_active" | "dark_red_alt1" | "dark_red_alt2" | "dark_red_active", {
        color1: string;
        color2: string;
        color3: string;
        color4: string;
        color5: string;
        color6: string;
        color7: string;
        color8: string;
        color9: string;
        color10: string;
        color11: string;
        color12: string;
        background: string;
        backgroundHover: string;
        backgroundPress: string;
        backgroundFocus: string;
        backgroundStrong: string;
        backgroundTransparent: string;
        color: string;
        colorHover: string;
        colorPress: string;
        colorFocus: string;
        colorTransparent: string;
        borderColor: string;
        borderColorHover: string;
        borderColorFocus: string;
        borderColorPress: string;
        placeholderColor: string;
        blue1: string;
        blue2: string;
        blue3: string;
        blue4: string;
        blue5: string;
        blue6: string;
        blue7: string;
        blue8: string;
        blue9: string;
        blue10: string;
        blue11: string;
        blue12: string;
        gray1: string;
        gray2: string;
        gray3: string;
        gray4: string;
        gray5: string;
        gray6: string;
        gray7: string;
        gray8: string;
        gray9: string;
        gray10: string;
        gray11: string;
        gray12: string;
        green1: string;
        green2: string;
        green3: string;
        green4: string;
        green5: string;
        green6: string;
        green7: string;
        green8: string;
        green9: string;
        green10: string;
        green11: string;
        green12: string;
        orange1: string;
        orange2: string;
        orange3: string;
        orange4: string;
        orange5: string;
        orange6: string;
        orange7: string;
        orange8: string;
        orange9: string;
        orange10: string;
        orange11: string;
        orange12: string;
        pink1: string;
        pink2: string;
        pink3: string;
        pink4: string;
        pink5: string;
        pink6: string;
        pink7: string;
        pink8: string;
        pink9: string;
        pink10: string;
        pink11: string;
        pink12: string;
        purple1: string;
        purple2: string;
        purple3: string;
        purple4: string;
        purple5: string;
        purple6: string;
        purple7: string;
        purple8: string;
        purple9: string;
        purple10: string;
        purple11: string;
        purple12: string;
        red1: string;
        red2: string;
        red3: string;
        red4: string;
        red5: string;
        red6: string;
        red7: string;
        red8: string;
        red9: string;
        red10: string;
        red11: string;
        red12: string;
        yellow1: string;
        yellow2: string;
        yellow3: string;
        yellow4: string;
        yellow5: string;
        yellow6: string;
        yellow7: string;
        yellow8: string;
        yellow9: string;
        yellow10: string;
        yellow11: string;
        yellow12: string;
        shadowColor: string;
        shadowColorHover: string;
        shadowColorPress: string;
        shadowColorFocus: string;
    }>;
    media: {
        xl: {
            maxWidth: number;
        };
        lg: {
            maxWidth: number;
        };
        md: {
            maxWidth: number;
        };
        sm: {
            maxWidth: number;
        };
        xs: {
            maxWidth: number;
        };
        xxs: {
            maxWidth: number;
        };
        gtXs: {
            minWidth: number;
        };
        gtSm: {
            minWidth: number;
        };
        gtMd: {
            minWidth: number;
        };
        gtLg: {
            minWidth: number;
        };
        gtXl: {
            minWidth: number;
        };
    };
    shorthands: {
        readonly ussel: "userSelect";
        readonly cur: "cursor";
        readonly pe: "pointerEvents";
        readonly col: "color";
        readonly ff: "fontFamily";
        readonly fos: "fontSize";
        readonly fost: "fontStyle";
        readonly fow: "fontWeight";
        readonly ls: "letterSpacing";
        readonly lh: "lineHeight";
        readonly ta: "textAlign";
        readonly tt: "textTransform";
        readonly ww: "wordWrap";
        readonly ac: "alignContent";
        readonly ai: "alignItems";
        readonly als: "alignSelf";
        readonly b: "bottom";
        readonly bc: "backgroundColor";
        readonly bg: "backgroundColor";
        readonly bbc: "borderBottomColor";
        readonly bblr: "borderBottomLeftRadius";
        readonly bbrr: "borderBottomRightRadius";
        readonly bbw: "borderBottomWidth";
        readonly blc: "borderLeftColor";
        readonly blw: "borderLeftWidth";
        readonly boc: "borderColor";
        readonly br: "borderRadius";
        readonly bs: "borderStyle";
        readonly brw: "borderRightWidth";
        readonly brc: "borderRightColor";
        readonly btc: "borderTopColor";
        readonly btlr: "borderTopLeftRadius";
        readonly btrr: "borderTopRightRadius";
        readonly btw: "borderTopWidth";
        readonly bw: "borderWidth";
        readonly dsp: "display";
        readonly f: "flex";
        readonly fb: "flexBasis";
        readonly fd: "flexDirection";
        readonly fg: "flexGrow";
        readonly fs: "flexShrink";
        readonly fw: "flexWrap";
        readonly h: "height";
        readonly jc: "justifyContent";
        readonly l: "left";
        readonly m: "margin";
        readonly mah: "maxHeight";
        readonly maw: "maxWidth";
        readonly mb: "marginBottom";
        readonly mih: "minHeight";
        readonly miw: "minWidth";
        readonly ml: "marginLeft";
        readonly mr: "marginRight";
        readonly mt: "marginTop";
        readonly mx: "marginHorizontal";
        readonly my: "marginVertical";
        readonly o: "opacity";
        readonly ov: "overflow";
        readonly p: "padding";
        readonly pb: "paddingBottom";
        readonly pl: "paddingLeft";
        readonly pos: "position";
        readonly pr: "paddingRight";
        readonly pt: "paddingTop";
        readonly px: "paddingHorizontal";
        readonly py: "paddingVertical";
        readonly r: "right";
        readonly shac: "shadowColor";
        readonly shar: "shadowRadius";
        readonly shof: "shadowOffset";
        readonly shop: "shadowOpacity";
        readonly t: "top";
        readonly w: "width";
        readonly zi: "zIndex";
    };
    tokens: {
        color: {
            yellow1Dark: import("@hanzo/gui-web").Variable<string>;
            yellow2Dark: import("@hanzo/gui-web").Variable<string>;
            yellow3Dark: import("@hanzo/gui-web").Variable<string>;
            yellow4Dark: import("@hanzo/gui-web").Variable<string>;
            yellow5Dark: import("@hanzo/gui-web").Variable<string>;
            yellow6Dark: import("@hanzo/gui-web").Variable<string>;
            yellow7Dark: import("@hanzo/gui-web").Variable<string>;
            yellow8Dark: import("@hanzo/gui-web").Variable<string>;
            yellow9Dark: import("@hanzo/gui-web").Variable<string>;
            yellow10Dark: import("@hanzo/gui-web").Variable<string>;
            yellow11Dark: import("@hanzo/gui-web").Variable<string>;
            yellow12Dark: import("@hanzo/gui-web").Variable<string>;
            red1Dark: import("@hanzo/gui-web").Variable<string>;
            red2Dark: import("@hanzo/gui-web").Variable<string>;
            red3Dark: import("@hanzo/gui-web").Variable<string>;
            red4Dark: import("@hanzo/gui-web").Variable<string>;
            red5Dark: import("@hanzo/gui-web").Variable<string>;
            red6Dark: import("@hanzo/gui-web").Variable<string>;
            red7Dark: import("@hanzo/gui-web").Variable<string>;
            red8Dark: import("@hanzo/gui-web").Variable<string>;
            red9Dark: import("@hanzo/gui-web").Variable<string>;
            red10Dark: import("@hanzo/gui-web").Variable<string>;
            red11Dark: import("@hanzo/gui-web").Variable<string>;
            red12Dark: import("@hanzo/gui-web").Variable<string>;
            purple1Dark: import("@hanzo/gui-web").Variable<string>;
            purple2Dark: import("@hanzo/gui-web").Variable<string>;
            purple3Dark: import("@hanzo/gui-web").Variable<string>;
            purple4Dark: import("@hanzo/gui-web").Variable<string>;
            purple5Dark: import("@hanzo/gui-web").Variable<string>;
            purple6Dark: import("@hanzo/gui-web").Variable<string>;
            purple7Dark: import("@hanzo/gui-web").Variable<string>;
            purple8Dark: import("@hanzo/gui-web").Variable<string>;
            purple9Dark: import("@hanzo/gui-web").Variable<string>;
            purple10Dark: import("@hanzo/gui-web").Variable<string>;
            purple11Dark: import("@hanzo/gui-web").Variable<string>;
            purple12Dark: import("@hanzo/gui-web").Variable<string>;
            pink1Dark: import("@hanzo/gui-web").Variable<string>;
            pink2Dark: import("@hanzo/gui-web").Variable<string>;
            pink3Dark: import("@hanzo/gui-web").Variable<string>;
            pink4Dark: import("@hanzo/gui-web").Variable<string>;
            pink5Dark: import("@hanzo/gui-web").Variable<string>;
            pink6Dark: import("@hanzo/gui-web").Variable<string>;
            pink7Dark: import("@hanzo/gui-web").Variable<string>;
            pink8Dark: import("@hanzo/gui-web").Variable<string>;
            pink9Dark: import("@hanzo/gui-web").Variable<string>;
            pink10Dark: import("@hanzo/gui-web").Variable<string>;
            pink11Dark: import("@hanzo/gui-web").Variable<string>;
            pink12Dark: import("@hanzo/gui-web").Variable<string>;
            orange1Dark: import("@hanzo/gui-web").Variable<string>;
            orange2Dark: import("@hanzo/gui-web").Variable<string>;
            orange3Dark: import("@hanzo/gui-web").Variable<string>;
            orange4Dark: import("@hanzo/gui-web").Variable<string>;
            orange5Dark: import("@hanzo/gui-web").Variable<string>;
            orange6Dark: import("@hanzo/gui-web").Variable<string>;
            orange7Dark: import("@hanzo/gui-web").Variable<string>;
            orange8Dark: import("@hanzo/gui-web").Variable<string>;
            orange9Dark: import("@hanzo/gui-web").Variable<string>;
            orange10Dark: import("@hanzo/gui-web").Variable<string>;
            orange11Dark: import("@hanzo/gui-web").Variable<string>;
            orange12Dark: import("@hanzo/gui-web").Variable<string>;
            green1Dark: import("@hanzo/gui-web").Variable<string>;
            green2Dark: import("@hanzo/gui-web").Variable<string>;
            green3Dark: import("@hanzo/gui-web").Variable<string>;
            green4Dark: import("@hanzo/gui-web").Variable<string>;
            green5Dark: import("@hanzo/gui-web").Variable<string>;
            green6Dark: import("@hanzo/gui-web").Variable<string>;
            green7Dark: import("@hanzo/gui-web").Variable<string>;
            green8Dark: import("@hanzo/gui-web").Variable<string>;
            green9Dark: import("@hanzo/gui-web").Variable<string>;
            green10Dark: import("@hanzo/gui-web").Variable<string>;
            green11Dark: import("@hanzo/gui-web").Variable<string>;
            green12Dark: import("@hanzo/gui-web").Variable<string>;
            gray1Dark: import("@hanzo/gui-web").Variable<string>;
            gray2Dark: import("@hanzo/gui-web").Variable<string>;
            gray3Dark: import("@hanzo/gui-web").Variable<string>;
            gray4Dark: import("@hanzo/gui-web").Variable<string>;
            gray5Dark: import("@hanzo/gui-web").Variable<string>;
            gray6Dark: import("@hanzo/gui-web").Variable<string>;
            gray7Dark: import("@hanzo/gui-web").Variable<string>;
            gray8Dark: import("@hanzo/gui-web").Variable<string>;
            gray9Dark: import("@hanzo/gui-web").Variable<string>;
            gray10Dark: import("@hanzo/gui-web").Variable<string>;
            gray11Dark: import("@hanzo/gui-web").Variable<string>;
            gray12Dark: import("@hanzo/gui-web").Variable<string>;
            blue1Dark: import("@hanzo/gui-web").Variable<string>;
            blue2Dark: import("@hanzo/gui-web").Variable<string>;
            blue3Dark: import("@hanzo/gui-web").Variable<string>;
            blue4Dark: import("@hanzo/gui-web").Variable<string>;
            blue5Dark: import("@hanzo/gui-web").Variable<string>;
            blue6Dark: import("@hanzo/gui-web").Variable<string>;
            blue7Dark: import("@hanzo/gui-web").Variable<string>;
            blue8Dark: import("@hanzo/gui-web").Variable<string>;
            blue9Dark: import("@hanzo/gui-web").Variable<string>;
            blue10Dark: import("@hanzo/gui-web").Variable<string>;
            blue11Dark: import("@hanzo/gui-web").Variable<string>;
            blue12Dark: import("@hanzo/gui-web").Variable<string>;
            yellow1Light: import("@hanzo/gui-web").Variable<string>;
            yellow2Light: import("@hanzo/gui-web").Variable<string>;
            yellow3Light: import("@hanzo/gui-web").Variable<string>;
            yellow4Light: import("@hanzo/gui-web").Variable<string>;
            yellow5Light: import("@hanzo/gui-web").Variable<string>;
            yellow6Light: import("@hanzo/gui-web").Variable<string>;
            yellow7Light: import("@hanzo/gui-web").Variable<string>;
            yellow8Light: import("@hanzo/gui-web").Variable<string>;
            yellow9Light: import("@hanzo/gui-web").Variable<string>;
            yellow10Light: import("@hanzo/gui-web").Variable<string>;
            yellow11Light: import("@hanzo/gui-web").Variable<string>;
            yellow12Light: import("@hanzo/gui-web").Variable<string>;
            red1Light: import("@hanzo/gui-web").Variable<string>;
            red2Light: import("@hanzo/gui-web").Variable<string>;
            red3Light: import("@hanzo/gui-web").Variable<string>;
            red4Light: import("@hanzo/gui-web").Variable<string>;
            red5Light: import("@hanzo/gui-web").Variable<string>;
            red6Light: import("@hanzo/gui-web").Variable<string>;
            red7Light: import("@hanzo/gui-web").Variable<string>;
            red8Light: import("@hanzo/gui-web").Variable<string>;
            red9Light: import("@hanzo/gui-web").Variable<string>;
            red10Light: import("@hanzo/gui-web").Variable<string>;
            red11Light: import("@hanzo/gui-web").Variable<string>;
            red12Light: import("@hanzo/gui-web").Variable<string>;
            purple1Light: import("@hanzo/gui-web").Variable<string>;
            purple2Light: import("@hanzo/gui-web").Variable<string>;
            purple3Light: import("@hanzo/gui-web").Variable<string>;
            purple4Light: import("@hanzo/gui-web").Variable<string>;
            purple5Light: import("@hanzo/gui-web").Variable<string>;
            purple6Light: import("@hanzo/gui-web").Variable<string>;
            purple7Light: import("@hanzo/gui-web").Variable<string>;
            purple8Light: import("@hanzo/gui-web").Variable<string>;
            purple9Light: import("@hanzo/gui-web").Variable<string>;
            purple10Light: import("@hanzo/gui-web").Variable<string>;
            purple11Light: import("@hanzo/gui-web").Variable<string>;
            purple12Light: import("@hanzo/gui-web").Variable<string>;
            pink1Light: import("@hanzo/gui-web").Variable<string>;
            pink2Light: import("@hanzo/gui-web").Variable<string>;
            pink3Light: import("@hanzo/gui-web").Variable<string>;
            pink4Light: import("@hanzo/gui-web").Variable<string>;
            pink5Light: import("@hanzo/gui-web").Variable<string>;
            pink6Light: import("@hanzo/gui-web").Variable<string>;
            pink7Light: import("@hanzo/gui-web").Variable<string>;
            pink8Light: import("@hanzo/gui-web").Variable<string>;
            pink9Light: import("@hanzo/gui-web").Variable<string>;
            pink10Light: import("@hanzo/gui-web").Variable<string>;
            pink11Light: import("@hanzo/gui-web").Variable<string>;
            pink12Light: import("@hanzo/gui-web").Variable<string>;
            orange1Light: import("@hanzo/gui-web").Variable<string>;
            orange2Light: import("@hanzo/gui-web").Variable<string>;
            orange3Light: import("@hanzo/gui-web").Variable<string>;
            orange4Light: import("@hanzo/gui-web").Variable<string>;
            orange5Light: import("@hanzo/gui-web").Variable<string>;
            orange6Light: import("@hanzo/gui-web").Variable<string>;
            orange7Light: import("@hanzo/gui-web").Variable<string>;
            orange8Light: import("@hanzo/gui-web").Variable<string>;
            orange9Light: import("@hanzo/gui-web").Variable<string>;
            orange10Light: import("@hanzo/gui-web").Variable<string>;
            orange11Light: import("@hanzo/gui-web").Variable<string>;
            orange12Light: import("@hanzo/gui-web").Variable<string>;
            green1Light: import("@hanzo/gui-web").Variable<string>;
            green2Light: import("@hanzo/gui-web").Variable<string>;
            green3Light: import("@hanzo/gui-web").Variable<string>;
            green4Light: import("@hanzo/gui-web").Variable<string>;
            green5Light: import("@hanzo/gui-web").Variable<string>;
            green6Light: import("@hanzo/gui-web").Variable<string>;
            green7Light: import("@hanzo/gui-web").Variable<string>;
            green8Light: import("@hanzo/gui-web").Variable<string>;
            green9Light: import("@hanzo/gui-web").Variable<string>;
            green10Light: import("@hanzo/gui-web").Variable<string>;
            green11Light: import("@hanzo/gui-web").Variable<string>;
            green12Light: import("@hanzo/gui-web").Variable<string>;
            gray1Light: import("@hanzo/gui-web").Variable<string>;
            gray2Light: import("@hanzo/gui-web").Variable<string>;
            gray3Light: import("@hanzo/gui-web").Variable<string>;
            gray4Light: import("@hanzo/gui-web").Variable<string>;
            gray5Light: import("@hanzo/gui-web").Variable<string>;
            gray6Light: import("@hanzo/gui-web").Variable<string>;
            gray7Light: import("@hanzo/gui-web").Variable<string>;
            gray8Light: import("@hanzo/gui-web").Variable<string>;
            gray9Light: import("@hanzo/gui-web").Variable<string>;
            gray10Light: import("@hanzo/gui-web").Variable<string>;
            gray11Light: import("@hanzo/gui-web").Variable<string>;
            gray12Light: import("@hanzo/gui-web").Variable<string>;
            blue1Light: import("@hanzo/gui-web").Variable<string>;
            blue2Light: import("@hanzo/gui-web").Variable<string>;
            blue3Light: import("@hanzo/gui-web").Variable<string>;
            blue4Light: import("@hanzo/gui-web").Variable<string>;
            blue5Light: import("@hanzo/gui-web").Variable<string>;
            blue6Light: import("@hanzo/gui-web").Variable<string>;
            blue7Light: import("@hanzo/gui-web").Variable<string>;
            blue8Light: import("@hanzo/gui-web").Variable<string>;
            blue9Light: import("@hanzo/gui-web").Variable<string>;
            blue10Light: import("@hanzo/gui-web").Variable<string>;
            blue11Light: import("@hanzo/gui-web").Variable<string>;
            blue12Light: import("@hanzo/gui-web").Variable<string>;
        };
        space: {
            $0: import("@hanzo/gui-web").Variable<number>;
            "$0.25": import("@hanzo/gui-web").Variable<number>;
            "$0.5": import("@hanzo/gui-web").Variable<number>;
            "$0.75": import("@hanzo/gui-web").Variable<number>;
            $1: import("@hanzo/gui-web").Variable<number>;
            "$1.5": import("@hanzo/gui-web").Variable<number>;
            $2: import("@hanzo/gui-web").Variable<number>;
            "$2.5": import("@hanzo/gui-web").Variable<number>;
            $3: import("@hanzo/gui-web").Variable<number>;
            "$3.5": import("@hanzo/gui-web").Variable<number>;
            $4: import("@hanzo/gui-web").Variable<number>;
            $true: import("@hanzo/gui-web").Variable<number>;
            "$4.5": import("@hanzo/gui-web").Variable<number>;
            $5: import("@hanzo/gui-web").Variable<number>;
            $6: import("@hanzo/gui-web").Variable<number>;
            $7: import("@hanzo/gui-web").Variable<number>;
            $8: import("@hanzo/gui-web").Variable<number>;
            $9: import("@hanzo/gui-web").Variable<number>;
            $10: import("@hanzo/gui-web").Variable<number>;
            $11: import("@hanzo/gui-web").Variable<number>;
            $12: import("@hanzo/gui-web").Variable<number>;
            $13: import("@hanzo/gui-web").Variable<number>;
            $14: import("@hanzo/gui-web").Variable<number>;
            $15: import("@hanzo/gui-web").Variable<number>;
            $16: import("@hanzo/gui-web").Variable<number>;
            $17: import("@hanzo/gui-web").Variable<number>;
            $18: import("@hanzo/gui-web").Variable<number>;
            $19: import("@hanzo/gui-web").Variable<number>;
            $20: import("@hanzo/gui-web").Variable<number>;
            "$-0.25": import("@hanzo/gui-web").Variable<number>;
            "$-0.5": import("@hanzo/gui-web").Variable<number>;
            "$-0.75": import("@hanzo/gui-web").Variable<number>;
            "$-1": import("@hanzo/gui-web").Variable<number>;
            "$-1.5": import("@hanzo/gui-web").Variable<number>;
            "$-2": import("@hanzo/gui-web").Variable<number>;
            "$-2.5": import("@hanzo/gui-web").Variable<number>;
            "$-3": import("@hanzo/gui-web").Variable<number>;
            "$-3.5": import("@hanzo/gui-web").Variable<number>;
            "$-4": import("@hanzo/gui-web").Variable<number>;
            "$-true": import("@hanzo/gui-web").Variable<number>;
            "$-4.5": import("@hanzo/gui-web").Variable<number>;
            "$-5": import("@hanzo/gui-web").Variable<number>;
            "$-6": import("@hanzo/gui-web").Variable<number>;
            "$-7": import("@hanzo/gui-web").Variable<number>;
            "$-8": import("@hanzo/gui-web").Variable<number>;
            "$-9": import("@hanzo/gui-web").Variable<number>;
            "$-10": import("@hanzo/gui-web").Variable<number>;
            "$-11": import("@hanzo/gui-web").Variable<number>;
            "$-12": import("@hanzo/gui-web").Variable<number>;
            "$-13": import("@hanzo/gui-web").Variable<number>;
            "$-14": import("@hanzo/gui-web").Variable<number>;
            "$-15": import("@hanzo/gui-web").Variable<number>;
            "$-16": import("@hanzo/gui-web").Variable<number>;
            "$-17": import("@hanzo/gui-web").Variable<number>;
            "$-18": import("@hanzo/gui-web").Variable<number>;
            "$-19": import("@hanzo/gui-web").Variable<number>;
            "$-20": import("@hanzo/gui-web").Variable<number>;
        };
        size: {
            $0: import("@hanzo/gui-web").Variable<number>;
            "$0.25": import("@hanzo/gui-web").Variable<number>;
            "$0.5": import("@hanzo/gui-web").Variable<number>;
            "$0.75": import("@hanzo/gui-web").Variable<number>;
            $1: import("@hanzo/gui-web").Variable<number>;
            "$1.5": import("@hanzo/gui-web").Variable<number>;
            $2: import("@hanzo/gui-web").Variable<number>;
            "$2.5": import("@hanzo/gui-web").Variable<number>;
            $3: import("@hanzo/gui-web").Variable<number>;
            "$3.5": import("@hanzo/gui-web").Variable<number>;
            $4: import("@hanzo/gui-web").Variable<number>;
            $true: import("@hanzo/gui-web").Variable<number>;
            "$4.5": import("@hanzo/gui-web").Variable<number>;
            $5: import("@hanzo/gui-web").Variable<number>;
            $6: import("@hanzo/gui-web").Variable<number>;
            $7: import("@hanzo/gui-web").Variable<number>;
            $8: import("@hanzo/gui-web").Variable<number>;
            $9: import("@hanzo/gui-web").Variable<number>;
            $10: import("@hanzo/gui-web").Variable<number>;
            $11: import("@hanzo/gui-web").Variable<number>;
            $12: import("@hanzo/gui-web").Variable<number>;
            $13: import("@hanzo/gui-web").Variable<number>;
            $14: import("@hanzo/gui-web").Variable<number>;
            $15: import("@hanzo/gui-web").Variable<number>;
            $16: import("@hanzo/gui-web").Variable<number>;
            $17: import("@hanzo/gui-web").Variable<number>;
            $18: import("@hanzo/gui-web").Variable<number>;
            $19: import("@hanzo/gui-web").Variable<number>;
            $20: import("@hanzo/gui-web").Variable<number>;
        };
        radius: {
            0: import("@hanzo/gui-web").Variable<number>;
            1: import("@hanzo/gui-web").Variable<number>;
            2: import("@hanzo/gui-web").Variable<number>;
            3: import("@hanzo/gui-web").Variable<number>;
            4: import("@hanzo/gui-web").Variable<number>;
            true: import("@hanzo/gui-web").Variable<number>;
            5: import("@hanzo/gui-web").Variable<number>;
            6: import("@hanzo/gui-web").Variable<number>;
            7: import("@hanzo/gui-web").Variable<number>;
            8: import("@hanzo/gui-web").Variable<number>;
            9: import("@hanzo/gui-web").Variable<number>;
            10: import("@hanzo/gui-web").Variable<number>;
            11: import("@hanzo/gui-web").Variable<number>;
            12: import("@hanzo/gui-web").Variable<number>;
        };
        zIndex: {
            0: import("@hanzo/gui-web").Variable<number>;
            1: import("@hanzo/gui-web").Variable<number>;
            2: import("@hanzo/gui-web").Variable<number>;
            3: import("@hanzo/gui-web").Variable<number>;
            4: import("@hanzo/gui-web").Variable<number>;
            5: import("@hanzo/gui-web").Variable<number>;
        };
    } & Omit<{
        color: {
            yellow1Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow2Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow3Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow4Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow5Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow6Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow7Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow8Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow9Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow10Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow11Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow12Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red1Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red2Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red3Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red4Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red5Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red6Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red7Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red8Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red9Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red10Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red11Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red12Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple1Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple2Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple3Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple4Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple5Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple6Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple7Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple8Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple9Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple10Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple11Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple12Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink1Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink2Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink3Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink4Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink5Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink6Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink7Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink8Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink9Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink10Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink11Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink12Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange1Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange2Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange3Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange4Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange5Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange6Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange7Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange8Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange9Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange10Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange11Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange12Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green1Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green2Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green3Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green4Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green5Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green6Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green7Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green8Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green9Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green10Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green11Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green12Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray1Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray2Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray3Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray4Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray5Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray6Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray7Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray8Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray9Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray10Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray11Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray12Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue1Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue2Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue3Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue4Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue5Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue6Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue7Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue8Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue9Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue10Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue11Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue12Dark: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow1Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow2Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow3Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow4Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow5Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow6Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow7Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow8Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow9Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow10Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow11Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            yellow12Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red1Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red2Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red3Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red4Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red5Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red6Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red7Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red8Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red9Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red10Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red11Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            red12Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple1Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple2Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple3Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple4Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple5Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple6Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple7Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple8Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple9Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple10Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple11Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            purple12Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink1Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink2Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink3Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink4Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink5Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink6Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink7Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink8Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink9Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink10Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink11Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            pink12Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange1Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange2Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange3Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange4Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange5Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange6Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange7Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange8Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange9Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange10Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange11Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            orange12Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green1Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green2Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green3Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green4Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green5Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green6Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green7Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green8Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green9Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green10Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green11Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            green12Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray1Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray2Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray3Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray4Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray5Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray6Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray7Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray8Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray9Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray10Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray11Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            gray12Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue1Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue2Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue3Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue4Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue5Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue6Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue7Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue8Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue9Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue10Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue11Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
            blue12Light: import("@hanzo/gui-web").Variable<string | import("@hanzo/gui-web").Variable<string>>;
        };
        radius: {
            0: import("@hanzo/gui-web").Variable<number>;
            1: import("@hanzo/gui-web").Variable<number>;
            2: import("@hanzo/gui-web").Variable<number>;
            3: import("@hanzo/gui-web").Variable<number>;
            4: import("@hanzo/gui-web").Variable<number>;
            true: import("@hanzo/gui-web").Variable<number>;
            5: import("@hanzo/gui-web").Variable<number>;
            6: import("@hanzo/gui-web").Variable<number>;
            7: import("@hanzo/gui-web").Variable<number>;
            8: import("@hanzo/gui-web").Variable<number>;
            9: import("@hanzo/gui-web").Variable<number>;
            10: import("@hanzo/gui-web").Variable<number>;
            11: import("@hanzo/gui-web").Variable<number>;
            12: import("@hanzo/gui-web").Variable<number>;
        };
        zIndex: {
            0: import("@hanzo/gui-web").Variable<number>;
            1: import("@hanzo/gui-web").Variable<number>;
            2: import("@hanzo/gui-web").Variable<number>;
            3: import("@hanzo/gui-web").Variable<number>;
            4: import("@hanzo/gui-web").Variable<number>;
            5: import("@hanzo/gui-web").Variable<number>;
        };
        space: {
            $0: import("@hanzo/gui-web").Variable<number>;
            "$0.25": import("@hanzo/gui-web").Variable<number>;
            "$0.5": import("@hanzo/gui-web").Variable<number>;
            "$0.75": import("@hanzo/gui-web").Variable<number>;
            $1: import("@hanzo/gui-web").Variable<number>;
            "$1.5": import("@hanzo/gui-web").Variable<number>;
            $2: import("@hanzo/gui-web").Variable<number>;
            "$2.5": import("@hanzo/gui-web").Variable<number>;
            $3: import("@hanzo/gui-web").Variable<number>;
            "$3.5": import("@hanzo/gui-web").Variable<number>;
            $4: import("@hanzo/gui-web").Variable<number>;
            $true: import("@hanzo/gui-web").Variable<number>;
            "$4.5": import("@hanzo/gui-web").Variable<number>;
            $5: import("@hanzo/gui-web").Variable<number>;
            $6: import("@hanzo/gui-web").Variable<number>;
            $7: import("@hanzo/gui-web").Variable<number>;
            $8: import("@hanzo/gui-web").Variable<number>;
            $9: import("@hanzo/gui-web").Variable<number>;
            $10: import("@hanzo/gui-web").Variable<number>;
            $11: import("@hanzo/gui-web").Variable<number>;
            $12: import("@hanzo/gui-web").Variable<number>;
            $13: import("@hanzo/gui-web").Variable<number>;
            $14: import("@hanzo/gui-web").Variable<number>;
            $15: import("@hanzo/gui-web").Variable<number>;
            $16: import("@hanzo/gui-web").Variable<number>;
            $17: import("@hanzo/gui-web").Variable<number>;
            $18: import("@hanzo/gui-web").Variable<number>;
            $19: import("@hanzo/gui-web").Variable<number>;
            $20: import("@hanzo/gui-web").Variable<number>;
            "$-0.25": import("@hanzo/gui-web").Variable<number>;
            "$-0.5": import("@hanzo/gui-web").Variable<number>;
            "$-0.75": import("@hanzo/gui-web").Variable<number>;
            "$-1": import("@hanzo/gui-web").Variable<number>;
            "$-1.5": import("@hanzo/gui-web").Variable<number>;
            "$-2": import("@hanzo/gui-web").Variable<number>;
            "$-2.5": import("@hanzo/gui-web").Variable<number>;
            "$-3": import("@hanzo/gui-web").Variable<number>;
            "$-3.5": import("@hanzo/gui-web").Variable<number>;
            "$-4": import("@hanzo/gui-web").Variable<number>;
            "$-true": import("@hanzo/gui-web").Variable<number>;
            "$-4.5": import("@hanzo/gui-web").Variable<number>;
            "$-5": import("@hanzo/gui-web").Variable<number>;
            "$-6": import("@hanzo/gui-web").Variable<number>;
            "$-7": import("@hanzo/gui-web").Variable<number>;
            "$-8": import("@hanzo/gui-web").Variable<number>;
            "$-9": import("@hanzo/gui-web").Variable<number>;
            "$-10": import("@hanzo/gui-web").Variable<number>;
            "$-11": import("@hanzo/gui-web").Variable<number>;
            "$-12": import("@hanzo/gui-web").Variable<number>;
            "$-13": import("@hanzo/gui-web").Variable<number>;
            "$-14": import("@hanzo/gui-web").Variable<number>;
            "$-15": import("@hanzo/gui-web").Variable<number>;
            "$-16": import("@hanzo/gui-web").Variable<number>;
            "$-17": import("@hanzo/gui-web").Variable<number>;
            "$-18": import("@hanzo/gui-web").Variable<number>;
            "$-19": import("@hanzo/gui-web").Variable<number>;
            "$-20": import("@hanzo/gui-web").Variable<number>;
        };
        size: {
            $0: import("@hanzo/gui-web").Variable<number>;
            "$0.25": import("@hanzo/gui-web").Variable<number>;
            "$0.5": import("@hanzo/gui-web").Variable<number>;
            "$0.75": import("@hanzo/gui-web").Variable<number>;
            $1: import("@hanzo/gui-web").Variable<number>;
            "$1.5": import("@hanzo/gui-web").Variable<number>;
            $2: import("@hanzo/gui-web").Variable<number>;
            "$2.5": import("@hanzo/gui-web").Variable<number>;
            $3: import("@hanzo/gui-web").Variable<number>;
            "$3.5": import("@hanzo/gui-web").Variable<number>;
            $4: import("@hanzo/gui-web").Variable<number>;
            $true: import("@hanzo/gui-web").Variable<number>;
            "$4.5": import("@hanzo/gui-web").Variable<number>;
            $5: import("@hanzo/gui-web").Variable<number>;
            $6: import("@hanzo/gui-web").Variable<number>;
            $7: import("@hanzo/gui-web").Variable<number>;
            $8: import("@hanzo/gui-web").Variable<number>;
            $9: import("@hanzo/gui-web").Variable<number>;
            $10: import("@hanzo/gui-web").Variable<number>;
            $11: import("@hanzo/gui-web").Variable<number>;
            $12: import("@hanzo/gui-web").Variable<number>;
            $13: import("@hanzo/gui-web").Variable<number>;
            $14: import("@hanzo/gui-web").Variable<number>;
            $15: import("@hanzo/gui-web").Variable<number>;
            $16: import("@hanzo/gui-web").Variable<number>;
            $17: import("@hanzo/gui-web").Variable<number>;
            $18: import("@hanzo/gui-web").Variable<number>;
            $19: import("@hanzo/gui-web").Variable<number>;
            $20: import("@hanzo/gui-web").Variable<number>;
        };
    }, "size" | "color" | "space" | "radius" | "zIndex">;
    fonts: {
        heading: import("@hanzo/gui-web").FillInFont<{
            size: {
                5: number;
                6: number;
                9: number;
                10: number;
            };
            transform: {
                6: "uppercase";
                7: "none";
            };
            weight: {
                6: string;
                7: string;
            };
            color: {
                6: string;
                7: string;
            };
            letterSpacing: {
                5: number;
                6: number;
                7: number;
                8: number;
                9: number;
                10: number;
                12: number;
                14: number;
                15: number;
            };
            face: {
                700: {
                    normal: string;
                };
                800: {
                    normal: string;
                };
                900: {
                    normal: string;
                };
            };
        }, 9 | 15 | 1 | 10 | 3 | 2 | 5 | 6 | 16 | 11 | 12 | 14 | 4 | 7 | 8 | 13 | "true">;
        body: import("@hanzo/gui-web").FillInFont<import("@hanzo/gui-web").GenericFont, 9 | 15 | 1 | 10 | 3 | 2 | 5 | 6 | 16 | 11 | 12 | 14 | 4 | 7 | 8 | 13 | "true">;
        mono: {
            weight: {
                1: string;
            };
            size: {
                1: number;
                2: number;
                3: number;
                4: number;
                5: number;
                6: number;
                7: number;
                8: number;
                9: number;
                10: number;
                11: number;
                12: number;
                13: number;
                14: number;
                15: number;
                16: number;
            };
        };
        silkscreen: import("@hanzo/gui-web").FillInFont<import("@hanzo/gui-web").GenericFont, 9 | 15 | 1 | 10 | 3 | 2 | 5 | 6 | 16 | 11 | 12 | 14 | 4 | 7 | 8 | 13>;
    };
    selectionStyles: (theme: Record<string, string>) => {
        backgroundColor: string;
        color: string;
    } | null;
    settings: {
        defaultFont: string;
        shouldAddPrefersColorThemes: true;
        mediaQueryDefaultActive: {
            xl: boolean;
            lg: boolean;
            md: boolean;
            sm: boolean;
            xs: boolean;
            xxs: boolean;
        };
    };
};
//# sourceMappingURL=config.d.ts.map