export declare const shorthands: {
    readonly ussel: "userSelect";
    readonly cur: "cursor";
    readonly pe: "pointerEvents";
    readonly col: "color";
    readonly ff: "fontFamily";
    readonly fos: "fontSize";
    readonly fost: "fontStyle";
    readonly fow: "fontWeight";
    readonly ls: "letterSpacing";
    readonly lh: "lineHeight";
    readonly ta: "textAlign";
    readonly tt: "textTransform";
    readonly ww: "wordWrap";
    readonly ac: "alignContent";
    readonly ai: "alignItems";
    readonly als: "alignSelf";
    readonly b: "bottom";
    readonly bg: "backgroundColor";
    readonly bbc: "borderBottomColor";
    readonly bblr: "borderBottomLeftRadius";
    readonly bbrr: "borderBottomRightRadius";
    readonly bbw: "borderBottomWidth";
    readonly blc: "borderLeftColor";
    readonly blw: "borderLeftWidth";
    readonly bc: "borderColor";
    readonly br: "borderRadius";
    readonly bs: "borderStyle";
    readonly brw: "borderRightWidth";
    readonly brc: "borderRightColor";
    readonly btc: "borderTopColor";
    readonly btlr: "borderTopLeftRadius";
    readonly btrr: "borderTopRightRadius";
    readonly btw: "borderTopWidth";
    readonly bw: "borderWidth";
    readonly dsp: "display";
    readonly f: "flex";
    readonly fb: "flexBasis";
    readonly fd: "flexDirection";
    readonly fg: "flexGrow";
    readonly fs: "flexShrink";
    readonly fw: "flexWrap";
    readonly h: "height";
    readonly jc: "justifyContent";
    readonly l: "left";
    readonly m: "margin";
    readonly mah: "maxHeight";
    readonly maw: "maxWidth";
    readonly mb: "marginBottom";
    readonly mih: "minHeight";
    readonly miw: "minWidth";
    readonly ml: "marginLeft";
    readonly mr: "marginRight";
    readonly mt: "marginTop";
    readonly mx: "marginHorizontal";
    readonly my: "marginVertical";
    readonly o: "opacity";
    readonly ov: "overflow";
    readonly p: "padding";
    readonly pb: "paddingBottom";
    readonly pl: "paddingLeft";
    readonly pos: "position";
    readonly pr: "paddingRight";
    readonly pt: "paddingTop";
    readonly px: "paddingHorizontal";
    readonly py: "paddingVertical";
    readonly r: "right";
    readonly shac: "shadowColor";
    readonly shar: "shadowRadius";
    readonly shof: "shadowOffset";
    readonly shop: "shadowOpacity";
    readonly t: "top";
    readonly w: "width";
    readonly zi: "zIndex";
};
export { animations } from './v3-animations';
export { tokens, themes } from '@hanzogui/themes/v3-themes';
export { fonts } from './fonts';
export { media, mediaQueryDefaultActive } from './media';
export declare const selectionStyles: (theme: any) => {
    backgroundColor: any;
    color: any;
} | null;
export declare const config: {
    animations: import("@hanzogui/web").AnimationDriver<{
        '0ms': string;
        '30ms': string;
        '50ms': string;
        '75ms': string;
        '100ms': string;
        '200ms': string;
        '250ms': string;
        '300ms': string;
        '400ms': string;
        '500ms': string;
        superBouncy: string;
        bouncy: string;
        kindaBouncy: string;
        superLazy: string;
        lazy: string;
        medium: string;
        slowest: string;
        slow: string;
        quick: string;
        quickLessBouncy: string;
        tooltip: string;
        quicker: string;
        quickerLessBouncy: string;
        quickest: string;
        quickestLessBouncy: string;
    }>;
    themes: import("@hanzogui/themes/v3-themes").ThemesOut;
    media: {
        xl: {
            maxWidth: number;
        };
        lg: {
            maxWidth: number;
        };
        md: {
            maxWidth: number;
        };
        sm: {
            maxWidth: number;
        };
        xs: {
            maxWidth: number;
        };
        xxs: {
            maxWidth: number;
        };
        gtXs: {
            minWidth: number;
        };
        gtSm: {
            minWidth: number;
        };
        gtMd: {
            minWidth: number;
        };
        gtLg: {
            minWidth: number;
        };
        gtXl: {
            minWidth: number;
        };
    };
    shorthands: {
        readonly ussel: "userSelect";
        readonly cur: "cursor";
        readonly pe: "pointerEvents";
        readonly col: "color";
        readonly ff: "fontFamily";
        readonly fos: "fontSize";
        readonly fost: "fontStyle";
        readonly fow: "fontWeight";
        readonly ls: "letterSpacing";
        readonly lh: "lineHeight";
        readonly ta: "textAlign";
        readonly tt: "textTransform";
        readonly ww: "wordWrap";
        readonly ac: "alignContent";
        readonly ai: "alignItems";
        readonly als: "alignSelf";
        readonly b: "bottom";
        readonly bg: "backgroundColor";
        readonly bbc: "borderBottomColor";
        readonly bblr: "borderBottomLeftRadius";
        readonly bbrr: "borderBottomRightRadius";
        readonly bbw: "borderBottomWidth";
        readonly blc: "borderLeftColor";
        readonly blw: "borderLeftWidth";
        readonly bc: "borderColor";
        readonly br: "borderRadius";
        readonly bs: "borderStyle";
        readonly brw: "borderRightWidth";
        readonly brc: "borderRightColor";
        readonly btc: "borderTopColor";
        readonly btlr: "borderTopLeftRadius";
        readonly btrr: "borderTopRightRadius";
        readonly btw: "borderTopWidth";
        readonly bw: "borderWidth";
        readonly dsp: "display";
        readonly f: "flex";
        readonly fb: "flexBasis";
        readonly fd: "flexDirection";
        readonly fg: "flexGrow";
        readonly fs: "flexShrink";
        readonly fw: "flexWrap";
        readonly h: "height";
        readonly jc: "justifyContent";
        readonly l: "left";
        readonly m: "margin";
        readonly mah: "maxHeight";
        readonly maw: "maxWidth";
        readonly mb: "marginBottom";
        readonly mih: "minHeight";
        readonly miw: "minWidth";
        readonly ml: "marginLeft";
        readonly mr: "marginRight";
        readonly mt: "marginTop";
        readonly mx: "marginHorizontal";
        readonly my: "marginVertical";
        readonly o: "opacity";
        readonly ov: "overflow";
        readonly p: "padding";
        readonly pb: "paddingBottom";
        readonly pl: "paddingLeft";
        readonly pos: "position";
        readonly pr: "paddingRight";
        readonly pt: "paddingTop";
        readonly px: "paddingHorizontal";
        readonly py: "paddingVertical";
        readonly r: "right";
        readonly shac: "shadowColor";
        readonly shar: "shadowRadius";
        readonly shof: "shadowOffset";
        readonly shop: "shadowOpacity";
        readonly t: "top";
        readonly w: "width";
        readonly zi: "zIndex";
    };
    tokens: {
        color: {
            yellow1Dark: import("@hanzogui/web").Variable<string>;
            yellow2Dark: import("@hanzogui/web").Variable<string>;
            yellow3Dark: import("@hanzogui/web").Variable<string>;
            yellow4Dark: import("@hanzogui/web").Variable<string>;
            yellow5Dark: import("@hanzogui/web").Variable<string>;
            yellow6Dark: import("@hanzogui/web").Variable<string>;
            yellow7Dark: import("@hanzogui/web").Variable<string>;
            yellow8Dark: import("@hanzogui/web").Variable<string>;
            yellow9Dark: import("@hanzogui/web").Variable<string>;
            yellow10Dark: import("@hanzogui/web").Variable<string>;
            yellow11Dark: import("@hanzogui/web").Variable<string>;
            yellow12Dark: import("@hanzogui/web").Variable<string>;
            red1Dark: import("@hanzogui/web").Variable<string>;
            red2Dark: import("@hanzogui/web").Variable<string>;
            red3Dark: import("@hanzogui/web").Variable<string>;
            red4Dark: import("@hanzogui/web").Variable<string>;
            red5Dark: import("@hanzogui/web").Variable<string>;
            red6Dark: import("@hanzogui/web").Variable<string>;
            red7Dark: import("@hanzogui/web").Variable<string>;
            red8Dark: import("@hanzogui/web").Variable<string>;
            red9Dark: import("@hanzogui/web").Variable<string>;
            red10Dark: import("@hanzogui/web").Variable<string>;
            red11Dark: import("@hanzogui/web").Variable<string>;
            red12Dark: import("@hanzogui/web").Variable<string>;
            purple1Dark: import("@hanzogui/web").Variable<string>;
            purple2Dark: import("@hanzogui/web").Variable<string>;
            purple3Dark: import("@hanzogui/web").Variable<string>;
            purple4Dark: import("@hanzogui/web").Variable<string>;
            purple5Dark: import("@hanzogui/web").Variable<string>;
            purple6Dark: import("@hanzogui/web").Variable<string>;
            purple7Dark: import("@hanzogui/web").Variable<string>;
            purple8Dark: import("@hanzogui/web").Variable<string>;
            purple9Dark: import("@hanzogui/web").Variable<string>;
            purple10Dark: import("@hanzogui/web").Variable<string>;
            purple11Dark: import("@hanzogui/web").Variable<string>;
            purple12Dark: import("@hanzogui/web").Variable<string>;
            pink1Dark: import("@hanzogui/web").Variable<string>;
            pink2Dark: import("@hanzogui/web").Variable<string>;
            pink3Dark: import("@hanzogui/web").Variable<string>;
            pink4Dark: import("@hanzogui/web").Variable<string>;
            pink5Dark: import("@hanzogui/web").Variable<string>;
            pink6Dark: import("@hanzogui/web").Variable<string>;
            pink7Dark: import("@hanzogui/web").Variable<string>;
            pink8Dark: import("@hanzogui/web").Variable<string>;
            pink9Dark: import("@hanzogui/web").Variable<string>;
            pink10Dark: import("@hanzogui/web").Variable<string>;
            pink11Dark: import("@hanzogui/web").Variable<string>;
            pink12Dark: import("@hanzogui/web").Variable<string>;
            orange1Dark: import("@hanzogui/web").Variable<string>;
            orange2Dark: import("@hanzogui/web").Variable<string>;
            orange3Dark: import("@hanzogui/web").Variable<string>;
            orange4Dark: import("@hanzogui/web").Variable<string>;
            orange5Dark: import("@hanzogui/web").Variable<string>;
            orange6Dark: import("@hanzogui/web").Variable<string>;
            orange7Dark: import("@hanzogui/web").Variable<string>;
            orange8Dark: import("@hanzogui/web").Variable<string>;
            orange9Dark: import("@hanzogui/web").Variable<string>;
            orange10Dark: import("@hanzogui/web").Variable<string>;
            orange11Dark: import("@hanzogui/web").Variable<string>;
            orange12Dark: import("@hanzogui/web").Variable<string>;
            green1Dark: import("@hanzogui/web").Variable<string>;
            green2Dark: import("@hanzogui/web").Variable<string>;
            green3Dark: import("@hanzogui/web").Variable<string>;
            green4Dark: import("@hanzogui/web").Variable<string>;
            green5Dark: import("@hanzogui/web").Variable<string>;
            green6Dark: import("@hanzogui/web").Variable<string>;
            green7Dark: import("@hanzogui/web").Variable<string>;
            green8Dark: import("@hanzogui/web").Variable<string>;
            green9Dark: import("@hanzogui/web").Variable<string>;
            green10Dark: import("@hanzogui/web").Variable<string>;
            green11Dark: import("@hanzogui/web").Variable<string>;
            green12Dark: import("@hanzogui/web").Variable<string>;
            gray1Dark: import("@hanzogui/web").Variable<string>;
            gray2Dark: import("@hanzogui/web").Variable<string>;
            gray3Dark: import("@hanzogui/web").Variable<string>;
            gray4Dark: import("@hanzogui/web").Variable<string>;
            gray5Dark: import("@hanzogui/web").Variable<string>;
            gray6Dark: import("@hanzogui/web").Variable<string>;
            gray7Dark: import("@hanzogui/web").Variable<string>;
            gray8Dark: import("@hanzogui/web").Variable<string>;
            gray9Dark: import("@hanzogui/web").Variable<string>;
            gray10Dark: import("@hanzogui/web").Variable<string>;
            gray11Dark: import("@hanzogui/web").Variable<string>;
            gray12Dark: import("@hanzogui/web").Variable<string>;
            blue1Dark: import("@hanzogui/web").Variable<string>;
            blue2Dark: import("@hanzogui/web").Variable<string>;
            blue3Dark: import("@hanzogui/web").Variable<string>;
            blue4Dark: import("@hanzogui/web").Variable<string>;
            blue5Dark: import("@hanzogui/web").Variable<string>;
            blue6Dark: import("@hanzogui/web").Variable<string>;
            blue7Dark: import("@hanzogui/web").Variable<string>;
            blue8Dark: import("@hanzogui/web").Variable<string>;
            blue9Dark: import("@hanzogui/web").Variable<string>;
            blue10Dark: import("@hanzogui/web").Variable<string>;
            blue11Dark: import("@hanzogui/web").Variable<string>;
            blue12Dark: import("@hanzogui/web").Variable<string>;
            yellow1Light: import("@hanzogui/web").Variable<string>;
            yellow2Light: import("@hanzogui/web").Variable<string>;
            yellow3Light: import("@hanzogui/web").Variable<string>;
            yellow4Light: import("@hanzogui/web").Variable<string>;
            yellow5Light: import("@hanzogui/web").Variable<string>;
            yellow6Light: import("@hanzogui/web").Variable<string>;
            yellow7Light: import("@hanzogui/web").Variable<string>;
            yellow8Light: import("@hanzogui/web").Variable<string>;
            yellow9Light: import("@hanzogui/web").Variable<string>;
            yellow10Light: import("@hanzogui/web").Variable<string>;
            yellow11Light: import("@hanzogui/web").Variable<string>;
            yellow12Light: import("@hanzogui/web").Variable<string>;
            red1Light: import("@hanzogui/web").Variable<string>;
            red2Light: import("@hanzogui/web").Variable<string>;
            red3Light: import("@hanzogui/web").Variable<string>;
            red4Light: import("@hanzogui/web").Variable<string>;
            red5Light: import("@hanzogui/web").Variable<string>;
            red6Light: import("@hanzogui/web").Variable<string>;
            red7Light: import("@hanzogui/web").Variable<string>;
            red8Light: import("@hanzogui/web").Variable<string>;
            red9Light: import("@hanzogui/web").Variable<string>;
            red10Light: import("@hanzogui/web").Variable<string>;
            red11Light: import("@hanzogui/web").Variable<string>;
            red12Light: import("@hanzogui/web").Variable<string>;
            purple1Light: import("@hanzogui/web").Variable<string>;
            purple2Light: import("@hanzogui/web").Variable<string>;
            purple3Light: import("@hanzogui/web").Variable<string>;
            purple4Light: import("@hanzogui/web").Variable<string>;
            purple5Light: import("@hanzogui/web").Variable<string>;
            purple6Light: import("@hanzogui/web").Variable<string>;
            purple7Light: import("@hanzogui/web").Variable<string>;
            purple8Light: import("@hanzogui/web").Variable<string>;
            purple9Light: import("@hanzogui/web").Variable<string>;
            purple10Light: import("@hanzogui/web").Variable<string>;
            purple11Light: import("@hanzogui/web").Variable<string>;
            purple12Light: import("@hanzogui/web").Variable<string>;
            pink1Light: import("@hanzogui/web").Variable<string>;
            pink2Light: import("@hanzogui/web").Variable<string>;
            pink3Light: import("@hanzogui/web").Variable<string>;
            pink4Light: import("@hanzogui/web").Variable<string>;
            pink5Light: import("@hanzogui/web").Variable<string>;
            pink6Light: import("@hanzogui/web").Variable<string>;
            pink7Light: import("@hanzogui/web").Variable<string>;
            pink8Light: import("@hanzogui/web").Variable<string>;
            pink9Light: import("@hanzogui/web").Variable<string>;
            pink10Light: import("@hanzogui/web").Variable<string>;
            pink11Light: import("@hanzogui/web").Variable<string>;
            pink12Light: import("@hanzogui/web").Variable<string>;
            orange1Light: import("@hanzogui/web").Variable<string>;
            orange2Light: import("@hanzogui/web").Variable<string>;
            orange3Light: import("@hanzogui/web").Variable<string>;
            orange4Light: import("@hanzogui/web").Variable<string>;
            orange5Light: import("@hanzogui/web").Variable<string>;
            orange6Light: import("@hanzogui/web").Variable<string>;
            orange7Light: import("@hanzogui/web").Variable<string>;
            orange8Light: import("@hanzogui/web").Variable<string>;
            orange9Light: import("@hanzogui/web").Variable<string>;
            orange10Light: import("@hanzogui/web").Variable<string>;
            orange11Light: import("@hanzogui/web").Variable<string>;
            orange12Light: import("@hanzogui/web").Variable<string>;
            green1Light: import("@hanzogui/web").Variable<string>;
            green2Light: import("@hanzogui/web").Variable<string>;
            green3Light: import("@hanzogui/web").Variable<string>;
            green4Light: import("@hanzogui/web").Variable<string>;
            green5Light: import("@hanzogui/web").Variable<string>;
            green6Light: import("@hanzogui/web").Variable<string>;
            green7Light: import("@hanzogui/web").Variable<string>;
            green8Light: import("@hanzogui/web").Variable<string>;
            green9Light: import("@hanzogui/web").Variable<string>;
            green10Light: import("@hanzogui/web").Variable<string>;
            green11Light: import("@hanzogui/web").Variable<string>;
            green12Light: import("@hanzogui/web").Variable<string>;
            gray1Light: import("@hanzogui/web").Variable<string>;
            gray2Light: import("@hanzogui/web").Variable<string>;
            gray3Light: import("@hanzogui/web").Variable<string>;
            gray4Light: import("@hanzogui/web").Variable<string>;
            gray5Light: import("@hanzogui/web").Variable<string>;
            gray6Light: import("@hanzogui/web").Variable<string>;
            gray7Light: import("@hanzogui/web").Variable<string>;
            gray8Light: import("@hanzogui/web").Variable<string>;
            gray9Light: import("@hanzogui/web").Variable<string>;
            gray10Light: import("@hanzogui/web").Variable<string>;
            gray11Light: import("@hanzogui/web").Variable<string>;
            gray12Light: import("@hanzogui/web").Variable<string>;
            blue1Light: import("@hanzogui/web").Variable<string>;
            blue2Light: import("@hanzogui/web").Variable<string>;
            blue3Light: import("@hanzogui/web").Variable<string>;
            blue4Light: import("@hanzogui/web").Variable<string>;
            blue5Light: import("@hanzogui/web").Variable<string>;
            blue6Light: import("@hanzogui/web").Variable<string>;
            blue7Light: import("@hanzogui/web").Variable<string>;
            blue8Light: import("@hanzogui/web").Variable<string>;
            blue9Light: import("@hanzogui/web").Variable<string>;
            blue10Light: import("@hanzogui/web").Variable<string>;
            blue11Light: import("@hanzogui/web").Variable<string>;
            blue12Light: import("@hanzogui/web").Variable<string>;
            white0: import("@hanzogui/web").Variable<string>;
            white075: import("@hanzogui/web").Variable<string>;
            white05: import("@hanzogui/web").Variable<string>;
            white025: import("@hanzogui/web").Variable<string>;
            black0: import("@hanzogui/web").Variable<string>;
            black075: import("@hanzogui/web").Variable<string>;
            black05: import("@hanzogui/web").Variable<string>;
            black025: import("@hanzogui/web").Variable<string>;
            white1: import("@hanzogui/web").Variable<string>;
            white2: import("@hanzogui/web").Variable<string>;
            white3: import("@hanzogui/web").Variable<string>;
            white4: import("@hanzogui/web").Variable<string>;
            white5: import("@hanzogui/web").Variable<string>;
            white6: import("@hanzogui/web").Variable<string>;
            white7: import("@hanzogui/web").Variable<string>;
            white8: import("@hanzogui/web").Variable<string>;
            white9: import("@hanzogui/web").Variable<string>;
            white10: import("@hanzogui/web").Variable<string>;
            white11: import("@hanzogui/web").Variable<string>;
            white12: import("@hanzogui/web").Variable<string>;
            black1: import("@hanzogui/web").Variable<string>;
            black2: import("@hanzogui/web").Variable<string>;
            black3: import("@hanzogui/web").Variable<string>;
            black4: import("@hanzogui/web").Variable<string>;
            black5: import("@hanzogui/web").Variable<string>;
            black6: import("@hanzogui/web").Variable<string>;
            black7: import("@hanzogui/web").Variable<string>;
            black8: import("@hanzogui/web").Variable<string>;
            black9: import("@hanzogui/web").Variable<string>;
            black10: import("@hanzogui/web").Variable<string>;
            black11: import("@hanzogui/web").Variable<string>;
            black12: import("@hanzogui/web").Variable<string>;
        };
        space: {
            0: import("@hanzogui/web").Variable<number>;
            0.25: import("@hanzogui/web").Variable<number>;
            0.5: import("@hanzogui/web").Variable<number>;
            0.75: import("@hanzogui/web").Variable<number>;
            1: import("@hanzogui/web").Variable<number>;
            1.5: import("@hanzogui/web").Variable<number>;
            2: import("@hanzogui/web").Variable<number>;
            2.5: import("@hanzogui/web").Variable<number>;
            3: import("@hanzogui/web").Variable<number>;
            3.5: import("@hanzogui/web").Variable<number>;
            4: import("@hanzogui/web").Variable<number>;
            true: import("@hanzogui/web").Variable<number>;
            4.5: import("@hanzogui/web").Variable<number>;
            5: import("@hanzogui/web").Variable<number>;
            6: import("@hanzogui/web").Variable<number>;
            7: import("@hanzogui/web").Variable<number>;
            8: import("@hanzogui/web").Variable<number>;
            9: import("@hanzogui/web").Variable<number>;
            10: import("@hanzogui/web").Variable<number>;
            11: import("@hanzogui/web").Variable<number>;
            12: import("@hanzogui/web").Variable<number>;
            13: import("@hanzogui/web").Variable<number>;
            14: import("@hanzogui/web").Variable<number>;
            15: import("@hanzogui/web").Variable<number>;
            16: import("@hanzogui/web").Variable<number>;
            17: import("@hanzogui/web").Variable<number>;
            18: import("@hanzogui/web").Variable<number>;
            19: import("@hanzogui/web").Variable<number>;
            20: import("@hanzogui/web").Variable<number>;
            [-0.25]: import("@hanzogui/web").Variable<number>;
            [-0.5]: import("@hanzogui/web").Variable<number>;
            [-0.75]: import("@hanzogui/web").Variable<number>;
            [-1]: import("@hanzogui/web").Variable<number>;
            [-1.5]: import("@hanzogui/web").Variable<number>;
            [-2]: import("@hanzogui/web").Variable<number>;
            [-2.5]: import("@hanzogui/web").Variable<number>;
            [-3]: import("@hanzogui/web").Variable<number>;
            [-3.5]: import("@hanzogui/web").Variable<number>;
            [-4]: import("@hanzogui/web").Variable<number>;
            "-true": import("@hanzogui/web").Variable<number>;
            [-4.5]: import("@hanzogui/web").Variable<number>;
            [-5]: import("@hanzogui/web").Variable<number>;
            [-6]: import("@hanzogui/web").Variable<number>;
            [-7]: import("@hanzogui/web").Variable<number>;
            [-8]: import("@hanzogui/web").Variable<number>;
            [-9]: import("@hanzogui/web").Variable<number>;
            [-10]: import("@hanzogui/web").Variable<number>;
            [-11]: import("@hanzogui/web").Variable<number>;
            [-12]: import("@hanzogui/web").Variable<number>;
            [-13]: import("@hanzogui/web").Variable<number>;
            [-14]: import("@hanzogui/web").Variable<number>;
            [-15]: import("@hanzogui/web").Variable<number>;
            [-16]: import("@hanzogui/web").Variable<number>;
            [-17]: import("@hanzogui/web").Variable<number>;
            [-18]: import("@hanzogui/web").Variable<number>;
            [-19]: import("@hanzogui/web").Variable<number>;
            [-20]: import("@hanzogui/web").Variable<number>;
        };
        size: {
            $0: import("@hanzogui/web").Variable<number>;
            "$0.25": import("@hanzogui/web").Variable<number>;
            "$0.5": import("@hanzogui/web").Variable<number>;
            "$0.75": import("@hanzogui/web").Variable<number>;
            $1: import("@hanzogui/web").Variable<number>;
            "$1.5": import("@hanzogui/web").Variable<number>;
            $2: import("@hanzogui/web").Variable<number>;
            "$2.5": import("@hanzogui/web").Variable<number>;
            $3: import("@hanzogui/web").Variable<number>;
            "$3.5": import("@hanzogui/web").Variable<number>;
            $4: import("@hanzogui/web").Variable<number>;
            $true: import("@hanzogui/web").Variable<number>;
            "$4.5": import("@hanzogui/web").Variable<number>;
            $5: import("@hanzogui/web").Variable<number>;
            $6: import("@hanzogui/web").Variable<number>;
            $7: import("@hanzogui/web").Variable<number>;
            $8: import("@hanzogui/web").Variable<number>;
            $9: import("@hanzogui/web").Variable<number>;
            $10: import("@hanzogui/web").Variable<number>;
            $11: import("@hanzogui/web").Variable<number>;
            $12: import("@hanzogui/web").Variable<number>;
            $13: import("@hanzogui/web").Variable<number>;
            $14: import("@hanzogui/web").Variable<number>;
            $15: import("@hanzogui/web").Variable<number>;
            $16: import("@hanzogui/web").Variable<number>;
            $17: import("@hanzogui/web").Variable<number>;
            $18: import("@hanzogui/web").Variable<number>;
            $19: import("@hanzogui/web").Variable<number>;
            $20: import("@hanzogui/web").Variable<number>;
        };
        radius: {
            0: import("@hanzogui/web").Variable<number>;
            1: import("@hanzogui/web").Variable<number>;
            2: import("@hanzogui/web").Variable<number>;
            3: import("@hanzogui/web").Variable<number>;
            4: import("@hanzogui/web").Variable<number>;
            true: import("@hanzogui/web").Variable<number>;
            5: import("@hanzogui/web").Variable<number>;
            6: import("@hanzogui/web").Variable<number>;
            7: import("@hanzogui/web").Variable<number>;
            8: import("@hanzogui/web").Variable<number>;
            9: import("@hanzogui/web").Variable<number>;
            10: import("@hanzogui/web").Variable<number>;
            11: import("@hanzogui/web").Variable<number>;
            12: import("@hanzogui/web").Variable<number>;
        };
        zIndex: {
            0: import("@hanzogui/web").Variable<number>;
            1: import("@hanzogui/web").Variable<number>;
            2: import("@hanzogui/web").Variable<number>;
            3: import("@hanzogui/web").Variable<number>;
            4: import("@hanzogui/web").Variable<number>;
            5: import("@hanzogui/web").Variable<number>;
        };
    } & Omit<{
        radius: {
            0: import("@hanzogui/web").Variable<number>;
            1: import("@hanzogui/web").Variable<number>;
            2: import("@hanzogui/web").Variable<number>;
            3: import("@hanzogui/web").Variable<number>;
            4: import("@hanzogui/web").Variable<number>;
            true: import("@hanzogui/web").Variable<number>;
            5: import("@hanzogui/web").Variable<number>;
            6: import("@hanzogui/web").Variable<number>;
            7: import("@hanzogui/web").Variable<number>;
            8: import("@hanzogui/web").Variable<number>;
            9: import("@hanzogui/web").Variable<number>;
            10: import("@hanzogui/web").Variable<number>;
            11: import("@hanzogui/web").Variable<number>;
            12: import("@hanzogui/web").Variable<number>;
        };
        zIndex: {
            0: import("@hanzogui/web").Variable<number>;
            1: import("@hanzogui/web").Variable<number>;
            2: import("@hanzogui/web").Variable<number>;
            3: import("@hanzogui/web").Variable<number>;
            4: import("@hanzogui/web").Variable<number>;
            5: import("@hanzogui/web").Variable<number>;
        };
        space: {
            0: import("@hanzogui/web").Variable<number>;
            0.25: import("@hanzogui/web").Variable<number>;
            0.5: import("@hanzogui/web").Variable<number>;
            0.75: import("@hanzogui/web").Variable<number>;
            1: import("@hanzogui/web").Variable<number>;
            1.5: import("@hanzogui/web").Variable<number>;
            2: import("@hanzogui/web").Variable<number>;
            2.5: import("@hanzogui/web").Variable<number>;
            3: import("@hanzogui/web").Variable<number>;
            3.5: import("@hanzogui/web").Variable<number>;
            4: import("@hanzogui/web").Variable<number>;
            true: import("@hanzogui/web").Variable<number>;
            4.5: import("@hanzogui/web").Variable<number>;
            5: import("@hanzogui/web").Variable<number>;
            6: import("@hanzogui/web").Variable<number>;
            7: import("@hanzogui/web").Variable<number>;
            8: import("@hanzogui/web").Variable<number>;
            9: import("@hanzogui/web").Variable<number>;
            10: import("@hanzogui/web").Variable<number>;
            11: import("@hanzogui/web").Variable<number>;
            12: import("@hanzogui/web").Variable<number>;
            13: import("@hanzogui/web").Variable<number>;
            14: import("@hanzogui/web").Variable<number>;
            15: import("@hanzogui/web").Variable<number>;
            16: import("@hanzogui/web").Variable<number>;
            17: import("@hanzogui/web").Variable<number>;
            18: import("@hanzogui/web").Variable<number>;
            19: import("@hanzogui/web").Variable<number>;
            20: import("@hanzogui/web").Variable<number>;
            [-0.25]: import("@hanzogui/web").Variable<number>;
            [-0.5]: import("@hanzogui/web").Variable<number>;
            [-0.75]: import("@hanzogui/web").Variable<number>;
            [-1]: import("@hanzogui/web").Variable<number>;
            [-1.5]: import("@hanzogui/web").Variable<number>;
            [-2]: import("@hanzogui/web").Variable<number>;
            [-2.5]: import("@hanzogui/web").Variable<number>;
            [-3]: import("@hanzogui/web").Variable<number>;
            [-3.5]: import("@hanzogui/web").Variable<number>;
            [-4]: import("@hanzogui/web").Variable<number>;
            "-true": import("@hanzogui/web").Variable<number>;
            [-4.5]: import("@hanzogui/web").Variable<number>;
            [-5]: import("@hanzogui/web").Variable<number>;
            [-6]: import("@hanzogui/web").Variable<number>;
            [-7]: import("@hanzogui/web").Variable<number>;
            [-8]: import("@hanzogui/web").Variable<number>;
            [-9]: import("@hanzogui/web").Variable<number>;
            [-10]: import("@hanzogui/web").Variable<number>;
            [-11]: import("@hanzogui/web").Variable<number>;
            [-12]: import("@hanzogui/web").Variable<number>;
            [-13]: import("@hanzogui/web").Variable<number>;
            [-14]: import("@hanzogui/web").Variable<number>;
            [-15]: import("@hanzogui/web").Variable<number>;
            [-16]: import("@hanzogui/web").Variable<number>;
            [-17]: import("@hanzogui/web").Variable<number>;
            [-18]: import("@hanzogui/web").Variable<number>;
            [-19]: import("@hanzogui/web").Variable<number>;
            [-20]: import("@hanzogui/web").Variable<number>;
        };
        size: {
            $0: import("@hanzogui/web").Variable<number>;
            "$0.25": import("@hanzogui/web").Variable<number>;
            "$0.5": import("@hanzogui/web").Variable<number>;
            "$0.75": import("@hanzogui/web").Variable<number>;
            $1: import("@hanzogui/web").Variable<number>;
            "$1.5": import("@hanzogui/web").Variable<number>;
            $2: import("@hanzogui/web").Variable<number>;
            "$2.5": import("@hanzogui/web").Variable<number>;
            $3: import("@hanzogui/web").Variable<number>;
            "$3.5": import("@hanzogui/web").Variable<number>;
            $4: import("@hanzogui/web").Variable<number>;
            $true: import("@hanzogui/web").Variable<number>;
            "$4.5": import("@hanzogui/web").Variable<number>;
            $5: import("@hanzogui/web").Variable<number>;
            $6: import("@hanzogui/web").Variable<number>;
            $7: import("@hanzogui/web").Variable<number>;
            $8: import("@hanzogui/web").Variable<number>;
            $9: import("@hanzogui/web").Variable<number>;
            $10: import("@hanzogui/web").Variable<number>;
            $11: import("@hanzogui/web").Variable<number>;
            $12: import("@hanzogui/web").Variable<number>;
            $13: import("@hanzogui/web").Variable<number>;
            $14: import("@hanzogui/web").Variable<number>;
            $15: import("@hanzogui/web").Variable<number>;
            $16: import("@hanzogui/web").Variable<number>;
            $17: import("@hanzogui/web").Variable<number>;
            $18: import("@hanzogui/web").Variable<number>;
            $19: import("@hanzogui/web").Variable<number>;
            $20: import("@hanzogui/web").Variable<number>;
        };
        color: {
            yellow1Dark: import("@hanzogui/web").Variable<string>;
            yellow2Dark: import("@hanzogui/web").Variable<string>;
            yellow3Dark: import("@hanzogui/web").Variable<string>;
            yellow4Dark: import("@hanzogui/web").Variable<string>;
            yellow5Dark: import("@hanzogui/web").Variable<string>;
            yellow6Dark: import("@hanzogui/web").Variable<string>;
            yellow7Dark: import("@hanzogui/web").Variable<string>;
            yellow8Dark: import("@hanzogui/web").Variable<string>;
            yellow9Dark: import("@hanzogui/web").Variable<string>;
            yellow10Dark: import("@hanzogui/web").Variable<string>;
            yellow11Dark: import("@hanzogui/web").Variable<string>;
            yellow12Dark: import("@hanzogui/web").Variable<string>;
            red1Dark: import("@hanzogui/web").Variable<string>;
            red2Dark: import("@hanzogui/web").Variable<string>;
            red3Dark: import("@hanzogui/web").Variable<string>;
            red4Dark: import("@hanzogui/web").Variable<string>;
            red5Dark: import("@hanzogui/web").Variable<string>;
            red6Dark: import("@hanzogui/web").Variable<string>;
            red7Dark: import("@hanzogui/web").Variable<string>;
            red8Dark: import("@hanzogui/web").Variable<string>;
            red9Dark: import("@hanzogui/web").Variable<string>;
            red10Dark: import("@hanzogui/web").Variable<string>;
            red11Dark: import("@hanzogui/web").Variable<string>;
            red12Dark: import("@hanzogui/web").Variable<string>;
            purple1Dark: import("@hanzogui/web").Variable<string>;
            purple2Dark: import("@hanzogui/web").Variable<string>;
            purple3Dark: import("@hanzogui/web").Variable<string>;
            purple4Dark: import("@hanzogui/web").Variable<string>;
            purple5Dark: import("@hanzogui/web").Variable<string>;
            purple6Dark: import("@hanzogui/web").Variable<string>;
            purple7Dark: import("@hanzogui/web").Variable<string>;
            purple8Dark: import("@hanzogui/web").Variable<string>;
            purple9Dark: import("@hanzogui/web").Variable<string>;
            purple10Dark: import("@hanzogui/web").Variable<string>;
            purple11Dark: import("@hanzogui/web").Variable<string>;
            purple12Dark: import("@hanzogui/web").Variable<string>;
            pink1Dark: import("@hanzogui/web").Variable<string>;
            pink2Dark: import("@hanzogui/web").Variable<string>;
            pink3Dark: import("@hanzogui/web").Variable<string>;
            pink4Dark: import("@hanzogui/web").Variable<string>;
            pink5Dark: import("@hanzogui/web").Variable<string>;
            pink6Dark: import("@hanzogui/web").Variable<string>;
            pink7Dark: import("@hanzogui/web").Variable<string>;
            pink8Dark: import("@hanzogui/web").Variable<string>;
            pink9Dark: import("@hanzogui/web").Variable<string>;
            pink10Dark: import("@hanzogui/web").Variable<string>;
            pink11Dark: import("@hanzogui/web").Variable<string>;
            pink12Dark: import("@hanzogui/web").Variable<string>;
            orange1Dark: import("@hanzogui/web").Variable<string>;
            orange2Dark: import("@hanzogui/web").Variable<string>;
            orange3Dark: import("@hanzogui/web").Variable<string>;
            orange4Dark: import("@hanzogui/web").Variable<string>;
            orange5Dark: import("@hanzogui/web").Variable<string>;
            orange6Dark: import("@hanzogui/web").Variable<string>;
            orange7Dark: import("@hanzogui/web").Variable<string>;
            orange8Dark: import("@hanzogui/web").Variable<string>;
            orange9Dark: import("@hanzogui/web").Variable<string>;
            orange10Dark: import("@hanzogui/web").Variable<string>;
            orange11Dark: import("@hanzogui/web").Variable<string>;
            orange12Dark: import("@hanzogui/web").Variable<string>;
            green1Dark: import("@hanzogui/web").Variable<string>;
            green2Dark: import("@hanzogui/web").Variable<string>;
            green3Dark: import("@hanzogui/web").Variable<string>;
            green4Dark: import("@hanzogui/web").Variable<string>;
            green5Dark: import("@hanzogui/web").Variable<string>;
            green6Dark: import("@hanzogui/web").Variable<string>;
            green7Dark: import("@hanzogui/web").Variable<string>;
            green8Dark: import("@hanzogui/web").Variable<string>;
            green9Dark: import("@hanzogui/web").Variable<string>;
            green10Dark: import("@hanzogui/web").Variable<string>;
            green11Dark: import("@hanzogui/web").Variable<string>;
            green12Dark: import("@hanzogui/web").Variable<string>;
            gray1Dark: import("@hanzogui/web").Variable<string>;
            gray2Dark: import("@hanzogui/web").Variable<string>;
            gray3Dark: import("@hanzogui/web").Variable<string>;
            gray4Dark: import("@hanzogui/web").Variable<string>;
            gray5Dark: import("@hanzogui/web").Variable<string>;
            gray6Dark: import("@hanzogui/web").Variable<string>;
            gray7Dark: import("@hanzogui/web").Variable<string>;
            gray8Dark: import("@hanzogui/web").Variable<string>;
            gray9Dark: import("@hanzogui/web").Variable<string>;
            gray10Dark: import("@hanzogui/web").Variable<string>;
            gray11Dark: import("@hanzogui/web").Variable<string>;
            gray12Dark: import("@hanzogui/web").Variable<string>;
            blue1Dark: import("@hanzogui/web").Variable<string>;
            blue2Dark: import("@hanzogui/web").Variable<string>;
            blue3Dark: import("@hanzogui/web").Variable<string>;
            blue4Dark: import("@hanzogui/web").Variable<string>;
            blue5Dark: import("@hanzogui/web").Variable<string>;
            blue6Dark: import("@hanzogui/web").Variable<string>;
            blue7Dark: import("@hanzogui/web").Variable<string>;
            blue8Dark: import("@hanzogui/web").Variable<string>;
            blue9Dark: import("@hanzogui/web").Variable<string>;
            blue10Dark: import("@hanzogui/web").Variable<string>;
            blue11Dark: import("@hanzogui/web").Variable<string>;
            blue12Dark: import("@hanzogui/web").Variable<string>;
            yellow1Light: import("@hanzogui/web").Variable<string>;
            yellow2Light: import("@hanzogui/web").Variable<string>;
            yellow3Light: import("@hanzogui/web").Variable<string>;
            yellow4Light: import("@hanzogui/web").Variable<string>;
            yellow5Light: import("@hanzogui/web").Variable<string>;
            yellow6Light: import("@hanzogui/web").Variable<string>;
            yellow7Light: import("@hanzogui/web").Variable<string>;
            yellow8Light: import("@hanzogui/web").Variable<string>;
            yellow9Light: import("@hanzogui/web").Variable<string>;
            yellow10Light: import("@hanzogui/web").Variable<string>;
            yellow11Light: import("@hanzogui/web").Variable<string>;
            yellow12Light: import("@hanzogui/web").Variable<string>;
            red1Light: import("@hanzogui/web").Variable<string>;
            red2Light: import("@hanzogui/web").Variable<string>;
            red3Light: import("@hanzogui/web").Variable<string>;
            red4Light: import("@hanzogui/web").Variable<string>;
            red5Light: import("@hanzogui/web").Variable<string>;
            red6Light: import("@hanzogui/web").Variable<string>;
            red7Light: import("@hanzogui/web").Variable<string>;
            red8Light: import("@hanzogui/web").Variable<string>;
            red9Light: import("@hanzogui/web").Variable<string>;
            red10Light: import("@hanzogui/web").Variable<string>;
            red11Light: import("@hanzogui/web").Variable<string>;
            red12Light: import("@hanzogui/web").Variable<string>;
            purple1Light: import("@hanzogui/web").Variable<string>;
            purple2Light: import("@hanzogui/web").Variable<string>;
            purple3Light: import("@hanzogui/web").Variable<string>;
            purple4Light: import("@hanzogui/web").Variable<string>;
            purple5Light: import("@hanzogui/web").Variable<string>;
            purple6Light: import("@hanzogui/web").Variable<string>;
            purple7Light: import("@hanzogui/web").Variable<string>;
            purple8Light: import("@hanzogui/web").Variable<string>;
            purple9Light: import("@hanzogui/web").Variable<string>;
            purple10Light: import("@hanzogui/web").Variable<string>;
            purple11Light: import("@hanzogui/web").Variable<string>;
            purple12Light: import("@hanzogui/web").Variable<string>;
            pink1Light: import("@hanzogui/web").Variable<string>;
            pink2Light: import("@hanzogui/web").Variable<string>;
            pink3Light: import("@hanzogui/web").Variable<string>;
            pink4Light: import("@hanzogui/web").Variable<string>;
            pink5Light: import("@hanzogui/web").Variable<string>;
            pink6Light: import("@hanzogui/web").Variable<string>;
            pink7Light: import("@hanzogui/web").Variable<string>;
            pink8Light: import("@hanzogui/web").Variable<string>;
            pink9Light: import("@hanzogui/web").Variable<string>;
            pink10Light: import("@hanzogui/web").Variable<string>;
            pink11Light: import("@hanzogui/web").Variable<string>;
            pink12Light: import("@hanzogui/web").Variable<string>;
            orange1Light: import("@hanzogui/web").Variable<string>;
            orange2Light: import("@hanzogui/web").Variable<string>;
            orange3Light: import("@hanzogui/web").Variable<string>;
            orange4Light: import("@hanzogui/web").Variable<string>;
            orange5Light: import("@hanzogui/web").Variable<string>;
            orange6Light: import("@hanzogui/web").Variable<string>;
            orange7Light: import("@hanzogui/web").Variable<string>;
            orange8Light: import("@hanzogui/web").Variable<string>;
            orange9Light: import("@hanzogui/web").Variable<string>;
            orange10Light: import("@hanzogui/web").Variable<string>;
            orange11Light: import("@hanzogui/web").Variable<string>;
            orange12Light: import("@hanzogui/web").Variable<string>;
            green1Light: import("@hanzogui/web").Variable<string>;
            green2Light: import("@hanzogui/web").Variable<string>;
            green3Light: import("@hanzogui/web").Variable<string>;
            green4Light: import("@hanzogui/web").Variable<string>;
            green5Light: import("@hanzogui/web").Variable<string>;
            green6Light: import("@hanzogui/web").Variable<string>;
            green7Light: import("@hanzogui/web").Variable<string>;
            green8Light: import("@hanzogui/web").Variable<string>;
            green9Light: import("@hanzogui/web").Variable<string>;
            green10Light: import("@hanzogui/web").Variable<string>;
            green11Light: import("@hanzogui/web").Variable<string>;
            green12Light: import("@hanzogui/web").Variable<string>;
            gray1Light: import("@hanzogui/web").Variable<string>;
            gray2Light: import("@hanzogui/web").Variable<string>;
            gray3Light: import("@hanzogui/web").Variable<string>;
            gray4Light: import("@hanzogui/web").Variable<string>;
            gray5Light: import("@hanzogui/web").Variable<string>;
            gray6Light: import("@hanzogui/web").Variable<string>;
            gray7Light: import("@hanzogui/web").Variable<string>;
            gray8Light: import("@hanzogui/web").Variable<string>;
            gray9Light: import("@hanzogui/web").Variable<string>;
            gray10Light: import("@hanzogui/web").Variable<string>;
            gray11Light: import("@hanzogui/web").Variable<string>;
            gray12Light: import("@hanzogui/web").Variable<string>;
            blue1Light: import("@hanzogui/web").Variable<string>;
            blue2Light: import("@hanzogui/web").Variable<string>;
            blue3Light: import("@hanzogui/web").Variable<string>;
            blue4Light: import("@hanzogui/web").Variable<string>;
            blue5Light: import("@hanzogui/web").Variable<string>;
            blue6Light: import("@hanzogui/web").Variable<string>;
            blue7Light: import("@hanzogui/web").Variable<string>;
            blue8Light: import("@hanzogui/web").Variable<string>;
            blue9Light: import("@hanzogui/web").Variable<string>;
            blue10Light: import("@hanzogui/web").Variable<string>;
            blue11Light: import("@hanzogui/web").Variable<string>;
            blue12Light: import("@hanzogui/web").Variable<string>;
            white0: import("@hanzogui/web").Variable<string>;
            white075: import("@hanzogui/web").Variable<string>;
            white05: import("@hanzogui/web").Variable<string>;
            white025: import("@hanzogui/web").Variable<string>;
            black0: import("@hanzogui/web").Variable<string>;
            black075: import("@hanzogui/web").Variable<string>;
            black05: import("@hanzogui/web").Variable<string>;
            black025: import("@hanzogui/web").Variable<string>;
            white1: import("@hanzogui/web").Variable<string>;
            white2: import("@hanzogui/web").Variable<string>;
            white3: import("@hanzogui/web").Variable<string>;
            white4: import("@hanzogui/web").Variable<string>;
            white5: import("@hanzogui/web").Variable<string>;
            white6: import("@hanzogui/web").Variable<string>;
            white7: import("@hanzogui/web").Variable<string>;
            white8: import("@hanzogui/web").Variable<string>;
            white9: import("@hanzogui/web").Variable<string>;
            white10: import("@hanzogui/web").Variable<string>;
            white11: import("@hanzogui/web").Variable<string>;
            white12: import("@hanzogui/web").Variable<string>;
            black1: import("@hanzogui/web").Variable<string>;
            black2: import("@hanzogui/web").Variable<string>;
            black3: import("@hanzogui/web").Variable<string>;
            black4: import("@hanzogui/web").Variable<string>;
            black5: import("@hanzogui/web").Variable<string>;
            black6: import("@hanzogui/web").Variable<string>;
            black7: import("@hanzogui/web").Variable<string>;
            black8: import("@hanzogui/web").Variable<string>;
            black9: import("@hanzogui/web").Variable<string>;
            black10: import("@hanzogui/web").Variable<string>;
            black11: import("@hanzogui/web").Variable<string>;
            black12: import("@hanzogui/web").Variable<string>;
        };
    }, "size" | "color" | "space" | "radius" | "zIndex">;
    fonts: {
        heading: import("@hanzogui/font-geist-sans").FillInFont<{
            size: {
                5: number;
                6: number;
                9: number;
                10: number;
            };
            transform: {
                6: "uppercase";
                7: "none";
            };
            weight: {
                6: string;
                7: string;
            };
            color: {
                6: string;
                7: string;
            };
            letterSpacing: {
                5: number;
                6: number;
                7: number;
                8: number;
                9: number;
                10: number;
                12: number;
                14: number;
                15: number;
            };
            face: {
                700: {
                    normal: string;
                };
                800: {
                    normal: string;
                };
                900: {
                    normal: string;
                };
            };
        }, 9 | 15 | 1 | 10 | 3 | 2 | 5 | 6 | 16 | 13 | 4 | 7 | 8 | 12 | 14 | "true" | 11>;
        body: import("@hanzogui/font-geist-sans").FillInFont<import("@hanzogui/font-geist-sans").GenericFont, 9 | 15 | 1 | 10 | 3 | 2 | 5 | 6 | 16 | 13 | 4 | 7 | 8 | 12 | 14 | "true" | 11>;
        mono: import("@hanzogui/font-geist-sans").FillInFont<import("@hanzogui/font-geist-sans").GenericFont, 9 | 15 | 1 | 10 | 3 | 2 | 5 | 6 | 16 | 13 | 4 | 7 | 8 | 12 | 14 | "true" | 11>;
    };
    selectionStyles: (theme: any) => {
        backgroundColor: any;
        color: any;
    } | null;
    settings: {
        mediaQueryDefaultActive: {
            xl: boolean;
            lg: boolean;
            md: boolean;
            sm: boolean;
            xs: boolean;
            xxs: boolean;
        };
        defaultFont: string;
        fastSchemeChange: true;
        shouldAddPrefersColorThemes: true;
    };
};
//# sourceMappingURL=v3.d.ts.map