"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VirtualizedList = exports.SectionList = exports.FlatList = exports.Vibration = exports.Share = exports.PixelRatio = exports.PanResponder = exports.Linking = exports.Keyboard = exports.I18nManager = exports.Dimensions = exports.DeviceInfo = exports.DeviceEventEmitter = exports.DeviceEmitter = exports.Clipboard = exports.BackHandler = exports.AppState = exports.AppRegistry = exports.Appearance = exports.Alert = exports.AccessibilityInfo = exports.NativeEventEmitter = exports.Easing = exports.Animated = exports.render = exports.NativeModules = exports.unstable_createElement = exports.usePlatformMethods = exports.useMergeRefs = exports.useLayoutEffect = exports.useHover = exports.useEvent = exports.UIManager = exports.TextAncestorContext = exports.StyleSheet = exports.processStyle = exports.processColor = exports.Platform = exports.normalizeColor = exports.mergeRefs = exports.LocaleProvider = exports.isWebColor = exports.InteractionManager = exports.ImageLoader = exports.flattenStyle = exports.dismissKeyboard = exports.createDOMProps = exports.clickProps = exports.canUseDOM = exports.AccessibilityUtil = void 0;
exports.RootTagContext = exports.unstable_batchedUpdates = exports.findNodeHandle = exports.useWindowDimensions = exports.useLocaleContext = exports.useColorScheme = exports.View = exports.TextInput = exports.Text = exports.StatusBar = exports.ScrollView = exports.SafeAreaView = exports.RefreshControl = exports.Pressable = exports.Modal = exports.LogBox = exports.KeyboardAvoidingView = exports.ImageBackground = exports.Image = exports.ActivityIndicator = exports.TouchableWithoutFeedback = exports.TouchableOpacity = exports.Touchable = exports.TouchableHighlight = exports.Switch = exports.DrawerLayoutAndroid = exports.TouchableNativeFeedback = void 0;
exports.requireNativeComponent = requireNativeComponent;
var react_1 = require("react");
var react_native_web_internals_1 = require("@hanzogui/react-native-web-internals");
Object.defineProperty(exports, "AccessibilityUtil", { enumerable: true, get: function () { return react_native_web_internals_1.AccessibilityUtil; } });
Object.defineProperty(exports, "canUseDOM", { enumerable: true, get: function () { return react_native_web_internals_1.canUseDOM; } });
Object.defineProperty(exports, "clickProps", { enumerable: true, get: function () { return react_native_web_internals_1.clickProps; } });
Object.defineProperty(exports, "createDOMProps", { enumerable: true, get: function () { return react_native_web_internals_1.createDOMProps; } });
Object.defineProperty(exports, "dismissKeyboard", { enumerable: true, get: function () { return react_native_web_internals_1.dismissKeyboard; } });
Object.defineProperty(exports, "flattenStyle", { enumerable: true, get: function () { return react_native_web_internals_1.flattenStyle; } });
Object.defineProperty(exports, "ImageLoader", { enumerable: true, get: function () { return react_native_web_internals_1.ImageLoader; } });
Object.defineProperty(exports, "InteractionManager", { enumerable: true, get: function () { return react_native_web_internals_1.InteractionManager; } });
Object.defineProperty(exports, "isWebColor", { enumerable: true, get: function () { return react_native_web_internals_1.isWebColor; } });
Object.defineProperty(exports, "LocaleProvider", { enumerable: true, get: function () { return react_native_web_internals_1.LocaleProvider; } });
Object.defineProperty(exports, "mergeRefs", { enumerable: true, get: function () { return react_native_web_internals_1.mergeRefs; } });
Object.defineProperty(exports, "normalizeColor", { enumerable: true, get: function () { return react_native_web_internals_1.normalizeColor; } });
Object.defineProperty(exports, "Platform", { enumerable: true, get: function () { return react_native_web_internals_1.Platform; } });
Object.defineProperty(exports, "processColor", { enumerable: true, get: function () { return react_native_web_internals_1.processColor; } });
Object.defineProperty(exports, "processStyle", { enumerable: true, get: function () { return react_native_web_internals_1.processStyle; } });
Object.defineProperty(exports, "StyleSheet", { enumerable: true, get: function () { return react_native_web_internals_1.StyleSheet; } });
Object.defineProperty(exports, "TextAncestorContext", { enumerable: true, get: function () { return react_native_web_internals_1.TextAncestorContext; } });
Object.defineProperty(exports, "UIManager", { enumerable: true, get: function () { return react_native_web_internals_1.UIManager; } });
Object.defineProperty(exports, "useEvent", { enumerable: true, get: function () { return react_native_web_internals_1.useEvent; } });
Object.defineProperty(exports, "useHover", { enumerable: true, get: function () { return react_native_web_internals_1.useHover; } });
Object.defineProperty(exports, "useLayoutEffect", { enumerable: true, get: function () { return react_native_web_internals_1.useLayoutEffect; } });
Object.defineProperty(exports, "useMergeRefs", { enumerable: true, get: function () { return react_native_web_internals_1.useMergeRefs; } });
Object.defineProperty(exports, "usePlatformMethods", { enumerable: true, get: function () { return react_native_web_internals_1.usePlatformMethods; } });
var index_1 = require("./createElement/index");
Object.defineProperty(exports, "unstable_createElement", { enumerable: true, get: function () { return index_1.createElement; } });
var index_2 = require("./NativeModules/index");
Object.defineProperty(exports, "NativeModules", { enumerable: true, get: function () { return index_2.NativeModules; } });
var index_3 = require("./render/index");
Object.defineProperty(exports, "render", { enumerable: true, get: function () { return index_3.render; } });
// animated - keep default as these are vendor files
var Animated_1 = require("./vendor/react-native/Animated/Animated");
Object.defineProperty(exports, "Animated", { enumerable: true, get: function () { return Animated_1.default; } });
var Easing_1 = require("./vendor/react-native/Animated/Easing");
Object.defineProperty(exports, "Easing", { enumerable: true, get: function () { return Easing_1.default; } });
// react-native - keep default as these are vendor files
var NativeEventEmitter_1 = require("./vendor/react-native/EventEmitter/NativeEventEmitter");
Object.defineProperty(exports, "NativeEventEmitter", { enumerable: true, get: function () { return NativeEventEmitter_1.default; } });
// APIs
var index_4 = require("./AccessibilityInfo/index");
Object.defineProperty(exports, "AccessibilityInfo", { enumerable: true, get: function () { return index_4.AccessibilityInfo; } });
var index_5 = require("./Alert/index");
Object.defineProperty(exports, "Alert", { enumerable: true, get: function () { return index_5.Alert; } });
var index_6 = require("./Appearance/index");
Object.defineProperty(exports, "Appearance", { enumerable: true, get: function () { return index_6.Appearance; } });
var index_7 = require("./AppRegistry/index");
Object.defineProperty(exports, "AppRegistry", { enumerable: true, get: function () { return index_7.AppRegistry; } });
var index_8 = require("./AppState/index");
Object.defineProperty(exports, "AppState", { enumerable: true, get: function () { return index_8.AppState; } });
var index_9 = require("./BackHandler/index");
Object.defineProperty(exports, "BackHandler", { enumerable: true, get: function () { return index_9.BackHandler; } });
var index_10 = require("./Clipboard/index");
Object.defineProperty(exports, "Clipboard", { enumerable: true, get: function () { return index_10.Clipboard; } });
var DeviceEmitter_1 = require("./DeviceEmitter");
Object.defineProperty(exports, "DeviceEmitter", { enumerable: true, get: function () { return DeviceEmitter_1.DeviceEmitter; } });
Object.defineProperty(exports, "DeviceEventEmitter", { enumerable: true, get: function () { return DeviceEmitter_1.DeviceEmitter; } });
var index_11 = require("./DeviceInfo/index");
Object.defineProperty(exports, "DeviceInfo", { enumerable: true, get: function () { return index_11.DeviceInfo; } });
var index_12 = require("./Dimensions/index");
Object.defineProperty(exports, "Dimensions", { enumerable: true, get: function () { return index_12.Dimensions; } });
var index_13 = require("./I18nManager/index");
Object.defineProperty(exports, "I18nManager", { enumerable: true, get: function () { return index_13.I18nManager; } });
var index_14 = require("./Keyboard/index");
Object.defineProperty(exports, "Keyboard", { enumerable: true, get: function () { return index_14.Keyboard; } });
var index_15 = require("./Linking/index");
Object.defineProperty(exports, "Linking", { enumerable: true, get: function () { return index_15.Linking; } });
var index_16 = require("./PanResponder/index");
Object.defineProperty(exports, "PanResponder", { enumerable: true, get: function () { return index_16.PanResponder; } });
var index_17 = require("./PixelRatio/index");
Object.defineProperty(exports, "PixelRatio", { enumerable: true, get: function () { return index_17.PixelRatio; } });
var index_18 = require("./Share/index");
Object.defineProperty(exports, "Share", { enumerable: true, get: function () { return index_18.Share; } });
var index_19 = require("./Vibration/index");
Object.defineProperty(exports, "Vibration", { enumerable: true, get: function () { return index_19.Vibration; } });
// implemented components
var FlatList_1 = require("./FlatList");
Object.defineProperty(exports, "FlatList", { enumerable: true, get: function () { return FlatList_1.FlatList; } });
var SectionList_1 = require("./SectionList");
Object.defineProperty(exports, "SectionList", { enumerable: true, get: function () { return SectionList_1.SectionList; } });
var VirtualizedList_1 = require("./VirtualizedList");
Object.defineProperty(exports, "VirtualizedList", { enumerable: true, get: function () { return VirtualizedList_1.VirtualizedList; } });
var TouchableNativeFeedback_1 = require("./TouchableNativeFeedback");
Object.defineProperty(exports, "TouchableNativeFeedback", { enumerable: true, get: function () { return TouchableNativeFeedback_1.TouchableNativeFeedback; } });
// unimplemented
var UnimplementedView_1 = require("./UnimplementedView");
Object.defineProperty(exports, "DrawerLayoutAndroid", { enumerable: true, get: function () { return UnimplementedView_1.UnimplementedView; } });
Object.defineProperty(exports, "Switch", { enumerable: true, get: function () { return UnimplementedView_1.UnimplementedView; } });
Object.defineProperty(exports, "TouchableHighlight", { enumerable: true, get: function () { return UnimplementedView_1.UnimplementedView; } });
var TouchableOpacity_1 = require("./TouchableOpacity");
Object.defineProperty(exports, "Touchable", { enumerable: true, get: function () { return TouchableOpacity_1.TouchableOpacity; } });
Object.defineProperty(exports, "TouchableOpacity", { enumerable: true, get: function () { return TouchableOpacity_1.TouchableOpacity; } });
var TouchableWithoutFeedback_1 = require("./TouchableWithoutFeedback");
Object.defineProperty(exports, "TouchableWithoutFeedback", { enumerable: true, get: function () { return TouchableWithoutFeedback_1.TouchableWithoutFeedback; } });
// components
var index_20 = require("./ActivityIndicator/index");
Object.defineProperty(exports, "ActivityIndicator", { enumerable: true, get: function () { return index_20.ActivityIndicator; } });
var index_21 = require("./Image/index");
Object.defineProperty(exports, "Image", { enumerable: true, get: function () { return index_21.Image; } });
var index_22 = require("./ImageBackground/index");
Object.defineProperty(exports, "ImageBackground", { enumerable: true, get: function () { return index_22.ImageBackground; } });
var index_23 = require("./KeyboardAvoidingView/index");
Object.defineProperty(exports, "KeyboardAvoidingView", { enumerable: true, get: function () { return index_23.KeyboardAvoidingView; } });
var index_24 = require("./LogBox/index");
Object.defineProperty(exports, "LogBox", { enumerable: true, get: function () { return index_24.LogBox; } });
var index_25 = require("./Modal/index");
Object.defineProperty(exports, "Modal", { enumerable: true, get: function () { return index_25.Modal; } });
var index_26 = require("./Pressable/index");
Object.defineProperty(exports, "Pressable", { enumerable: true, get: function () { return index_26.Pressable; } });
var index_27 = require("./RefreshControl/index");
Object.defineProperty(exports, "RefreshControl", { enumerable: true, get: function () { return index_27.RefreshControl; } });
var index_28 = require("./SafeAreaView/index");
Object.defineProperty(exports, "SafeAreaView", { enumerable: true, get: function () { return index_28.SafeAreaView; } });
var index_29 = require("./ScrollView/index");
Object.defineProperty(exports, "ScrollView", { enumerable: true, get: function () { return index_29.ScrollView; } });
var index_30 = require("./StatusBar/index");
Object.defineProperty(exports, "StatusBar", { enumerable: true, get: function () { return index_30.StatusBar; } });
var index_31 = require("./Text/index");
Object.defineProperty(exports, "Text", { enumerable: true, get: function () { return index_31.Text; } });
var index_32 = require("./TextInput/index");
Object.defineProperty(exports, "TextInput", { enumerable: true, get: function () { return index_32.TextInput; } });
var index_33 = require("./View/index");
Object.defineProperty(exports, "View", { enumerable: true, get: function () { return index_33.View; } });
// hooks
var index_34 = require("./useColorScheme/index");
Object.defineProperty(exports, "useColorScheme", { enumerable: true, get: function () { return index_34.useColorScheme; } });
var index_35 = require("./useLocaleContext/index");
Object.defineProperty(exports, "useLocaleContext", { enumerable: true, get: function () { return index_35.useLocaleContext; } });
var index_36 = require("./useWindowDimensions/index");
Object.defineProperty(exports, "useWindowDimensions", { enumerable: true, get: function () { return index_36.useWindowDimensions; } });
function requireNativeComponent(name) {
    return function FakeComponent() {
        return null;
    };
}
var findNodeHandle = function (component) {
    throw new Error('not supported - use ref instead');
};
exports.findNodeHandle = findNodeHandle;
// compat with rn:
var react_dom_1 = require("react-dom");
Object.defineProperty(exports, "unstable_batchedUpdates", { enumerable: true, get: function () { return react_dom_1.unstable_batchedUpdates; } });
exports.RootTagContext = (0, react_1.createContext)(null);
