export { createElement as unstable_createElement } from './createElement/index';
export { AccessibilityUtil, canUseDOM, clickProps, createDOMProps, dismissKeyboard, flattenStyle, ImageLoader, InteractionManager, isWebColor, LocaleProvider, mergeRefs, normalizeColor, Platform, processColor, processStyle, StyleSheet, TextAncestorContext, UIManager, useEvent, useHover, useLayoutEffect, useMergeRefs, usePlatformMethods, } from '@hanzogui/react-native-web-internals';
export { render } from './render/index';
export { NativeModules } from './NativeModules/index';
export { default as NativeEventEmitter } from './vendor/react-native/EventEmitter/NativeEventEmitter';
export { AccessibilityInfo } from './AccessibilityInfo/index';
export { Alert } from './Alert/index';
export { Appearance } from './Appearance/index';
export { AppRegistry } from './AppRegistry/index';
export { AppState } from './AppState/index';
export { BackHandler } from './BackHandler/index';
export { Clipboard } from './Clipboard/index';
export { DeviceInfo } from './DeviceInfo/index';
export { DeviceEmitter } from './DeviceEmitter';
export { DeviceEmitter as DeviceEventEmitter } from './DeviceEmitter';
export { Dimensions } from './Dimensions/index';
export { I18nManager } from './I18nManager/index';
export { Keyboard } from './Keyboard/index';
export { Linking } from './Linking/index';
export { PanResponder } from './PanResponder/index';
export { PixelRatio } from './PixelRatio/index';
export { Share } from './Share/index';
export { Vibration } from './Vibration/index';
export { UnimplementedView as DrawerLayoutAndroid } from './UnimplementedView';
export { UnimplementedView as Switch } from './UnimplementedView';
export { UnimplementedView as VirtualizedList } from './UnimplementedView';
export { UnimplementedView as FlatList } from './UnimplementedView';
export { UnimplementedView as TouchableHighlight } from './UnimplementedView';
export { UnimplementedView as TouchableNativeFeedback } from './UnimplementedView';
export { UnimplementedView as SectionList } from './UnimplementedView';
export { TouchableOpacity as Touchable, TouchableOpacity } from './TouchableOpacity';
export { TouchableWithoutFeedback } from './TouchableWithoutFeedback';
export { ActivityIndicator } from './ActivityIndicator/index';
export { Image } from './Image/index';
export { ImageBackground } from './ImageBackground/index';
export { KeyboardAvoidingView } from './KeyboardAvoidingView/index';
export { Modal } from './Modal/index';
export { Pressable } from './Pressable/index';
export { RefreshControl } from './RefreshControl/index';
export { SafeAreaView } from './SafeAreaView/index';
export { ScrollView } from './ScrollView/index';
export type { ScrollViewRef, ScrollViewMethods } from './ScrollView/index';
export { StatusBar } from './StatusBar/index';
export { Text } from './Text/index';
export { TextInput } from './TextInput/index';
export { View } from './View/index';
export { LogBox } from './LogBox/index';
export { useColorScheme } from './useColorScheme/index';
export { useLocaleContext } from './useLocaleContext/index';
export { useWindowDimensions } from './useWindowDimensions/index';
export * from '@hanzogui/react-native-web-internals';
export declare function requireNativeComponent(name: string): () => any;
declare class AnimatedValue {
    _value: number;
    _offset: number;
    _listeners: Record<string, (state: {
        value: number;
    }) => void>;
    _nextId: number;
    constructor(value?: number);
    setValue(value: number): void;
    setOffset(offset: number): void;
    flattenOffset(): void;
    extractOffset(): void;
    addListener(callback: (state: {
        value: number;
    }) => void): string;
    removeListener(id: string): void;
    removeAllListeners(): void;
    stopAnimation(callback?: (value: number) => void): void;
    resetAnimation(callback?: (value: number) => void): void;
    interpolate(config: any): AnimatedValue;
    _notifyListeners(): void;
    __getValue(): number;
}
declare class AnimatedValueXY {
    x: AnimatedValue;
    y: AnimatedValue;
    constructor(value?: {
        x?: number;
        y?: number;
    });
    setValue(value: {
        x: number;
        y: number;
    }): void;
    setOffset(offset: {
        x: number;
        y: number;
    }): void;
    flattenOffset(): void;
    stopAnimation(callback?: (value: {
        x: number;
        y: number;
    }) => void): void;
    addListener(callback: (value: {
        x: number;
        y: number;
    }) => void): string;
    removeAllListeners(): void;
    getLayout(): {
        left: AnimatedValue;
        top: AnimatedValue;
    };
    getTranslateTransform(): ({
        translateX: AnimatedValue;
        translateY?: undefined;
    } | {
        translateY: AnimatedValue;
        translateX?: undefined;
    })[];
}
export declare const Animated: {
    View: import("react").ForwardRefExoticComponent<{
        children?: any | null;
        dir?: "ltr" | "rtl";
        focusable?: boolean | null;
        lang?: string;
        nativeID?: string | null;
        onBlur?: (e: any) => void;
        onClick?: (e: any) => void;
        onClickCapture?: (e: any) => void;
        onContextMenu?: (e: any) => void;
        onFocus?: (e: any) => void;
        onKeyDown?: (e: any) => void;
        onKeyUp?: (e: any) => void;
        onLayout?: (e: import("./types").LayoutEvent) => void;
        onMoveShouldSetResponder?: (e: any) => boolean;
        onMoveShouldSetResponderCapture?: (e: any) => boolean;
        onResponderEnd?: (e: any) => void;
        onResponderGrant?: (e: any) => void | boolean;
        onResponderMove?: (e: any) => void;
        onResponderReject?: (e: any) => void;
        onResponderRelease?: (e: any) => void;
        onResponderStart?: (e: any) => void;
        onResponderTerminate?: (e: any) => void;
        onResponderTerminationRequest?: (e: any) => boolean;
        onScrollShouldSetResponder?: (e: any) => boolean;
        onScrollShouldSetResponderCapture?: (e: any) => boolean;
        onSelectionChangeShouldSetResponder?: (e: any) => boolean;
        onSelectionChangeShouldSetResponderCapture?: (e: any) => boolean;
        onStartShouldSetResponder?: (e: any) => boolean;
        onStartShouldSetResponderCapture?: (e: any) => boolean;
        pointerEvents?: "box-none" | "none" | "box-only" | "auto";
        style?: import("./types").GenericStyleProp<import("./View/types").ViewStyle>;
        testID?: string | null;
        dataSet?: object | null;
        onMouseDown?: (e: any) => void;
        onMouseEnter?: (e: any) => void;
        onMouseLeave?: (e: any) => void;
        onMouseMove?: (e: any) => void;
        onMouseOver?: (e: any) => void;
        onMouseOut?: (e: any) => void;
        onMouseUp?: (e: any) => void;
        onScroll?: (e: any) => void;
        onTouchCancel?: (e: any) => void;
        onTouchCancelCapture?: (e: any) => void;
        onTouchEnd?: (e: any) => void;
        onTouchEndCapture?: (e: any) => void;
        onTouchMove?: (e: any) => void;
        onTouchMoveCapture?: (e: any) => void;
        onTouchStart?: (e: any) => void;
        onTouchStartCapture?: (e: any) => void;
        onWheel?: (e: any) => void;
        href?: string | null;
        hrefAttrs?: {
            download?: boolean | null;
            rel?: string | null;
            target?: string | null;
        } | null;
    } & import("./View/types").AccessibilityProps & import("react").RefAttributes<HTMLElement & import("./types").PlatformMethods>>;
    Text: import("react").ForwardRefExoticComponent<{
        accessibilityRole?: "button" | "header" | "heading" | "label" | "link" | "listitem" | "none" | "text";
        dir?: "auto" | "ltr" | "rtl";
        lang?: string;
        numberOfLines?: number | null;
        onPress?: (e: any) => void;
        selectable?: boolean;
        style?: import("./types").GenericStyleProp<import("./Text/types").TextStyle>;
        testID?: string | null;
    } & {
        children?: any | null;
        dir?: "ltr" | "rtl";
        focusable?: boolean | null;
        lang?: string;
        nativeID?: string | null;
        onBlur?: (e: any) => void;
        onClick?: (e: any) => void;
        onClickCapture?: (e: any) => void;
        onContextMenu?: (e: any) => void;
        onFocus?: (e: any) => void;
        onKeyDown?: (e: any) => void;
        onKeyUp?: (e: any) => void;
        onLayout?: (e: import("./types").LayoutEvent) => void;
        onMoveShouldSetResponder?: (e: any) => boolean;
        onMoveShouldSetResponderCapture?: (e: any) => boolean;
        onResponderEnd?: (e: any) => void;
        onResponderGrant?: (e: any) => void | boolean;
        onResponderMove?: (e: any) => void;
        onResponderReject?: (e: any) => void;
        onResponderRelease?: (e: any) => void;
        onResponderStart?: (e: any) => void;
        onResponderTerminate?: (e: any) => void;
        onResponderTerminationRequest?: (e: any) => boolean;
        onScrollShouldSetResponder?: (e: any) => boolean;
        onScrollShouldSetResponderCapture?: (e: any) => boolean;
        onSelectionChangeShouldSetResponder?: (e: any) => boolean;
        onSelectionChangeShouldSetResponderCapture?: (e: any) => boolean;
        onStartShouldSetResponder?: (e: any) => boolean;
        onStartShouldSetResponderCapture?: (e: any) => boolean;
        pointerEvents?: "box-none" | "none" | "box-only" | "auto";
        style?: import("./types").GenericStyleProp<import("./View/types").ViewStyle>;
        testID?: string | null;
        dataSet?: object | null;
        onMouseDown?: (e: any) => void;
        onMouseEnter?: (e: any) => void;
        onMouseLeave?: (e: any) => void;
        onMouseMove?: (e: any) => void;
        onMouseOver?: (e: any) => void;
        onMouseOut?: (e: any) => void;
        onMouseUp?: (e: any) => void;
        onScroll?: (e: any) => void;
        onTouchCancel?: (e: any) => void;
        onTouchCancelCapture?: (e: any) => void;
        onTouchEnd?: (e: any) => void;
        onTouchEndCapture?: (e: any) => void;
        onTouchMove?: (e: any) => void;
        onTouchMoveCapture?: (e: any) => void;
        onTouchStart?: (e: any) => void;
        onTouchStartCapture?: (e: any) => void;
        onWheel?: (e: any) => void;
        href?: string | null;
        hrefAttrs?: {
            download?: boolean | null;
            rel?: string | null;
            target?: string | null;
        } | null;
    } & import("./View/types").AccessibilityProps & import("react").RefAttributes<HTMLElement & import("./types").PlatformMethods>>;
    Image: import("react").ForwardRefExoticComponent<{
        blurRadius?: number;
        defaultSource?: import("./Image/types").Source;
        draggable?: boolean;
        onError?: (e: any) => void;
        onLayout?: (e: any) => void;
        onLoad?: (e: any) => void;
        onLoadEnd?: (e: any) => void;
        onLoadStart?: (e: any) => void;
        onProgress?: (e: any) => void;
        resizeMode?: import("./Image/types").ResizeMode;
        source?: import("./Image/types").Source;
        style?: import("./types").GenericStyleProp<import("./Image/types").ImageStyle>;
    } & {
        children?: any | null;
        dir?: "ltr" | "rtl";
        focusable?: boolean | null;
        lang?: string;
        nativeID?: string | null;
        onBlur?: (e: any) => void;
        onClick?: (e: any) => void;
        onClickCapture?: (e: any) => void;
        onContextMenu?: (e: any) => void;
        onFocus?: (e: any) => void;
        onKeyDown?: (e: any) => void;
        onKeyUp?: (e: any) => void;
        onLayout?: (e: import("./types").LayoutEvent) => void;
        onMoveShouldSetResponder?: (e: any) => boolean;
        onMoveShouldSetResponderCapture?: (e: any) => boolean;
        onResponderEnd?: (e: any) => void;
        onResponderGrant?: (e: any) => void | boolean;
        onResponderMove?: (e: any) => void;
        onResponderReject?: (e: any) => void;
        onResponderRelease?: (e: any) => void;
        onResponderStart?: (e: any) => void;
        onResponderTerminate?: (e: any) => void;
        onResponderTerminationRequest?: (e: any) => boolean;
        onScrollShouldSetResponder?: (e: any) => boolean;
        onScrollShouldSetResponderCapture?: (e: any) => boolean;
        onSelectionChangeShouldSetResponder?: (e: any) => boolean;
        onSelectionChangeShouldSetResponderCapture?: (e: any) => boolean;
        onStartShouldSetResponder?: (e: any) => boolean;
        onStartShouldSetResponderCapture?: (e: any) => boolean;
        pointerEvents?: "box-none" | "none" | "box-only" | "auto";
        style?: import("./types").GenericStyleProp<import("./View/types").ViewStyle>;
        testID?: string | null;
        dataSet?: object | null;
        onMouseDown?: (e: any) => void;
        onMouseEnter?: (e: any) => void;
        onMouseLeave?: (e: any) => void;
        onMouseMove?: (e: any) => void;
        onMouseOver?: (e: any) => void;
        onMouseOut?: (e: any) => void;
        onMouseUp?: (e: any) => void;
        onScroll?: (e: any) => void;
        onTouchCancel?: (e: any) => void;
        onTouchCancelCapture?: (e: any) => void;
        onTouchEnd?: (e: any) => void;
        onTouchEndCapture?: (e: any) => void;
        onTouchMove?: (e: any) => void;
        onTouchMoveCapture?: (e: any) => void;
        onTouchStart?: (e: any) => void;
        onTouchStartCapture?: (e: any) => void;
        onWheel?: (e: any) => void;
        href?: string | null;
        hrefAttrs?: {
            download?: boolean | null;
            rel?: string | null;
            target?: string | null;
        } | null;
    } & import("./View/types").AccessibilityProps & import("react").RefAttributes<import("react").ForwardRefExoticComponent<{
        children?: any | null;
        dir?: "ltr" | "rtl";
        focusable?: boolean | null;
        lang?: string;
        nativeID?: string | null;
        onBlur?: (e: any) => void;
        onClick?: (e: any) => void;
        onClickCapture?: (e: any) => void;
        onContextMenu?: (e: any) => void;
        onFocus?: (e: any) => void;
        onKeyDown?: (e: any) => void;
        onKeyUp?: (e: any) => void;
        onLayout?: (e: import("./types").LayoutEvent) => void;
        onMoveShouldSetResponder?: (e: any) => boolean;
        onMoveShouldSetResponderCapture?: (e: any) => boolean;
        onResponderEnd?: (e: any) => void;
        onResponderGrant?: (e: any) => void | boolean;
        onResponderMove?: (e: any) => void;
        onResponderReject?: (e: any) => void;
        onResponderRelease?: (e: any) => void;
        onResponderStart?: (e: any) => void;
        onResponderTerminate?: (e: any) => void;
        onResponderTerminationRequest?: (e: any) => boolean;
        onScrollShouldSetResponder?: (e: any) => boolean;
        onScrollShouldSetResponderCapture?: (e: any) => boolean;
        onSelectionChangeShouldSetResponder?: (e: any) => boolean;
        onSelectionChangeShouldSetResponderCapture?: (e: any) => boolean;
        onStartShouldSetResponder?: (e: any) => boolean;
        onStartShouldSetResponderCapture?: (e: any) => boolean;
        pointerEvents?: "box-none" | "none" | "box-only" | "auto";
        style?: import("./types").GenericStyleProp<import("./View/types").ViewStyle>;
        testID?: string | null;
        dataSet?: object | null;
        onMouseDown?: (e: any) => void;
        onMouseEnter?: (e: any) => void;
        onMouseLeave?: (e: any) => void;
        onMouseMove?: (e: any) => void;
        onMouseOver?: (e: any) => void;
        onMouseOut?: (e: any) => void;
        onMouseUp?: (e: any) => void;
        onScroll?: (e: any) => void;
        onTouchCancel?: (e: any) => void;
        onTouchCancelCapture?: (e: any) => void;
        onTouchEnd?: (e: any) => void;
        onTouchEndCapture?: (e: any) => void;
        onTouchMove?: (e: any) => void;
        onTouchMoveCapture?: (e: any) => void;
        onTouchStart?: (e: any) => void;
        onTouchStartCapture?: (e: any) => void;
        onWheel?: (e: any) => void;
        href?: string | null;
        hrefAttrs?: {
            download?: boolean | null;
            rel?: string | null;
            target?: string | null;
        } | null;
    } & import("./View/types").AccessibilityProps & import("react").RefAttributes<HTMLElement & import("./types").PlatformMethods>>>>;
    ScrollView: any;
    FlatList: import("react").ForwardRefExoticComponent<{
        children?: any | null;
        dir?: "ltr" | "rtl";
        focusable?: boolean | null;
        lang?: string;
        nativeID?: string | null;
        onBlur?: (e: any) => void;
        onClick?: (e: any) => void;
        onClickCapture?: (e: any) => void;
        onContextMenu?: (e: any) => void;
        onFocus?: (e: any) => void;
        onKeyDown?: (e: any) => void;
        onKeyUp?: (e: any) => void;
        onLayout?: (e: import("./types").LayoutEvent) => void;
        onMoveShouldSetResponder?: (e: any) => boolean;
        onMoveShouldSetResponderCapture?: (e: any) => boolean;
        onResponderEnd?: (e: any) => void;
        onResponderGrant?: (e: any) => void | boolean;
        onResponderMove?: (e: any) => void;
        onResponderReject?: (e: any) => void;
        onResponderRelease?: (e: any) => void;
        onResponderStart?: (e: any) => void;
        onResponderTerminate?: (e: any) => void;
        onResponderTerminationRequest?: (e: any) => boolean;
        onScrollShouldSetResponder?: (e: any) => boolean;
        onScrollShouldSetResponderCapture?: (e: any) => boolean;
        onSelectionChangeShouldSetResponder?: (e: any) => boolean;
        onSelectionChangeShouldSetResponderCapture?: (e: any) => boolean;
        onStartShouldSetResponder?: (e: any) => boolean;
        onStartShouldSetResponderCapture?: (e: any) => boolean;
        pointerEvents?: "box-none" | "none" | "box-only" | "auto";
        style?: import("./types").GenericStyleProp<import("./View/types").ViewStyle>;
        testID?: string | null;
        dataSet?: object | null;
        onMouseDown?: (e: any) => void;
        onMouseEnter?: (e: any) => void;
        onMouseLeave?: (e: any) => void;
        onMouseMove?: (e: any) => void;
        onMouseOver?: (e: any) => void;
        onMouseOut?: (e: any) => void;
        onMouseUp?: (e: any) => void;
        onScroll?: (e: any) => void;
        onTouchCancel?: (e: any) => void;
        onTouchCancelCapture?: (e: any) => void;
        onTouchEnd?: (e: any) => void;
        onTouchEndCapture?: (e: any) => void;
        onTouchMove?: (e: any) => void;
        onTouchMoveCapture?: (e: any) => void;
        onTouchStart?: (e: any) => void;
        onTouchStartCapture?: (e: any) => void;
        onWheel?: (e: any) => void;
        href?: string | null;
        hrefAttrs?: {
            download?: boolean | null;
            rel?: string | null;
            target?: string | null;
        } | null;
    } & import("./View/types").AccessibilityProps & import("react").RefAttributes<HTMLElement & import("./types").PlatformMethods>>;
    SectionList: import("react").ForwardRefExoticComponent<{
        children?: any | null;
        dir?: "ltr" | "rtl";
        focusable?: boolean | null;
        lang?: string;
        nativeID?: string | null;
        onBlur?: (e: any) => void;
        onClick?: (e: any) => void;
        onClickCapture?: (e: any) => void;
        onContextMenu?: (e: any) => void;
        onFocus?: (e: any) => void;
        onKeyDown?: (e: any) => void;
        onKeyUp?: (e: any) => void;
        onLayout?: (e: import("./types").LayoutEvent) => void;
        onMoveShouldSetResponder?: (e: any) => boolean;
        onMoveShouldSetResponderCapture?: (e: any) => boolean;
        onResponderEnd?: (e: any) => void;
        onResponderGrant?: (e: any) => void | boolean;
        onResponderMove?: (e: any) => void;
        onResponderReject?: (e: any) => void;
        onResponderRelease?: (e: any) => void;
        onResponderStart?: (e: any) => void;
        onResponderTerminate?: (e: any) => void;
        onResponderTerminationRequest?: (e: any) => boolean;
        onScrollShouldSetResponder?: (e: any) => boolean;
        onScrollShouldSetResponderCapture?: (e: any) => boolean;
        onSelectionChangeShouldSetResponder?: (e: any) => boolean;
        onSelectionChangeShouldSetResponderCapture?: (e: any) => boolean;
        onStartShouldSetResponder?: (e: any) => boolean;
        onStartShouldSetResponderCapture?: (e: any) => boolean;
        pointerEvents?: "box-none" | "none" | "box-only" | "auto";
        style?: import("./types").GenericStyleProp<import("./View/types").ViewStyle>;
        testID?: string | null;
        dataSet?: object | null;
        onMouseDown?: (e: any) => void;
        onMouseEnter?: (e: any) => void;
        onMouseLeave?: (e: any) => void;
        onMouseMove?: (e: any) => void;
        onMouseOver?: (e: any) => void;
        onMouseOut?: (e: any) => void;
        onMouseUp?: (e: any) => void;
        onScroll?: (e: any) => void;
        onTouchCancel?: (e: any) => void;
        onTouchCancelCapture?: (e: any) => void;
        onTouchEnd?: (e: any) => void;
        onTouchEndCapture?: (e: any) => void;
        onTouchMove?: (e: any) => void;
        onTouchMoveCapture?: (e: any) => void;
        onTouchStart?: (e: any) => void;
        onTouchStartCapture?: (e: any) => void;
        onWheel?: (e: any) => void;
        href?: string | null;
        hrefAttrs?: {
            download?: boolean | null;
            rel?: string | null;
            target?: string | null;
        } | null;
    } & import("./View/types").AccessibilityProps & import("react").RefAttributes<HTMLElement & import("./types").PlatformMethods>>;
    Value: typeof AnimatedValue;
    ValueXY: typeof AnimatedValueXY;
    timing: () => {
        start: (cb?: any) => any;
        stop: () => void;
        reset: () => void;
    };
    spring: () => {
        start: (cb?: any) => any;
        stop: () => void;
        reset: () => void;
    };
    decay: () => {
        start: (cb?: any) => any;
        stop: () => void;
        reset: () => void;
    };
    sequence: () => {
        start: (cb?: any) => any;
        stop: () => void;
        reset: () => void;
    };
    parallel: () => {
        start: (cb?: any) => any;
        stop: () => void;
        reset: () => void;
    };
    stagger: () => {
        start: (cb?: any) => any;
        stop: () => void;
        reset: () => void;
    };
    loop: () => {
        start: (cb?: any) => any;
        stop: () => void;
        reset: () => void;
    };
    event: () => () => void;
    add: (a: any, b: any) => AnimatedValue;
    subtract: (a: any, b: any) => AnimatedValue;
    multiply: (a: any, b: any) => AnimatedValue;
    divide: (a: any, b: any) => AnimatedValue;
    modulo: (a: any, b: any) => AnimatedValue;
    diffClamp: (a: any, min: number, max: number) => AnimatedValue;
    delay: () => {
        start: (cb?: any) => any;
        stop: () => void;
        reset: () => void;
    };
    createAnimatedComponent: (c: any) => any;
};
export declare const Easing: {
    step0: () => number;
    step1: () => number;
    linear: (t: number) => number;
    ease: (t: number) => number;
    quad: (t: number) => number;
    cubic: (t: number) => number;
    poly: () => (t: number) => number;
    sin: (t: number) => number;
    circle: (t: number) => number;
    exp: (t: number) => number;
    elastic: () => (t: number) => number;
    back: () => (t: number) => number;
    bounce: (t: number) => number;
    bezier: () => (t: number) => number;
    in: (fn: any) => any;
    out: (fn: any) => any;
    inOut: (fn: any) => any;
};
export declare const findNodeHandle: (component: any) => never;
export { unstable_batchedUpdates } from 'react-dom';
export declare const RootTagContext: import("react").Context<any>;
