"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.grayDark = exports.gray = exports.purpleDark = exports.purple = exports.pinkDark = exports.pink = exports.yellowDark = exports.yellow = exports.orangeDark = exports.orange = exports.redDark = exports.red = exports.greenDark = exports.green = exports.blueDark = exports.blue = exports.tokens = exports.themes = void 0;
var generated_v3_1 = require("./generated-v3");
Object.defineProperty(exports, "themes", { enumerable: true, get: function () { return generated_v3_1.themes; } });
var v3_themes_1 = require("./v3-themes");
Object.defineProperty(exports, "tokens", { enumerable: true, get: function () { return v3_themes_1.tokens; } });
// specific colors since we have cjs here
var legacy_1 = require("@hanzogui/colors/legacy");
Object.defineProperty(exports, "blue", { enumerable: true, get: function () { return legacy_1.blue; } });
Object.defineProperty(exports, "blueDark", { enumerable: true, get: function () { return legacy_1.blueDark; } });
var legacy_2 = require("@hanzogui/colors/legacy");
Object.defineProperty(exports, "green", { enumerable: true, get: function () { return legacy_2.green; } });
Object.defineProperty(exports, "greenDark", { enumerable: true, get: function () { return legacy_2.greenDark; } });
var legacy_3 = require("@hanzogui/colors/legacy");
Object.defineProperty(exports, "red", { enumerable: true, get: function () { return legacy_3.red; } });
Object.defineProperty(exports, "redDark", { enumerable: true, get: function () { return legacy_3.redDark; } });
var legacy_4 = require("@hanzogui/colors/legacy");
Object.defineProperty(exports, "orange", { enumerable: true, get: function () { return legacy_4.orange; } });
Object.defineProperty(exports, "orangeDark", { enumerable: true, get: function () { return legacy_4.orangeDark; } });
var legacy_5 = require("@hanzogui/colors/legacy");
Object.defineProperty(exports, "yellow", { enumerable: true, get: function () { return legacy_5.yellow; } });
Object.defineProperty(exports, "yellowDark", { enumerable: true, get: function () { return legacy_5.yellowDark; } });
var legacy_6 = require("@hanzogui/colors/legacy");
Object.defineProperty(exports, "pink", { enumerable: true, get: function () { return legacy_6.pink; } });
Object.defineProperty(exports, "pinkDark", { enumerable: true, get: function () { return legacy_6.pinkDark; } });
var legacy_7 = require("@hanzogui/colors/legacy");
Object.defineProperty(exports, "purple", { enumerable: true, get: function () { return legacy_7.purple; } });
Object.defineProperty(exports, "purpleDark", { enumerable: true, get: function () { return legacy_7.purpleDark; } });
var legacy_8 = require("@hanzogui/colors/legacy");
Object.defineProperty(exports, "gray", { enumerable: true, get: function () { return legacy_8.gray; } });
Object.defineProperty(exports, "grayDark", { enumerable: true, get: function () { return legacy_8.grayDark; } });
