name: Changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    name: Changelog
    runs-on: [self-hosted, linux, amd64]
    # needs: release

    steps:
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ github.token }}'
          prerelease: false
