name: Changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    name: Changelog
    runs-on: ubuntu-latest  # TODO: hanzo-build-linux-amd64 when ARC runners are deployed
    # needs: release

    steps:
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ github.token }}'
          prerelease: false
